### ISSUE TITLE
[Offline imagery] UI for managing offline areas

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#10]
Allows download of selected mbtiles for offline use. Related to #113.

**Comment by gino-m** [comment]
Thanks for taking this one on @scolsen.

Some mocks for reference:
![image](https://user-images.githubusercontent.com/228050/55904574-2f6ace80-5b9e-11e9-94b5-b14be289eae1.png) ![image](https://user-images.githubusercontent.com/228050/55904591-3560af80-5b9e-11e9-8a19-a997fcb9b768.png) ![image](https://user-images.githubusercontent.com/228050/55904618-47425280-5b9e-11e9-8b50-9f26836d6af0.png)

Please ping me when you get to it and I'll PM you the test data URL.

**Comment by scolsen** [comment]
Remaining work:
- [ ] Add icon next to "Offline maps" menu option
- [ ] Add top app bar with title "Offline maps", subtitle "Tap to toggle offline areas", and back ("up") arrow
- [ ] Show default offline area extends defined in GeoJSON.
- [ ] Tap to toggle areas; selected areas opaque, unselected ones semi-opaque
- [ ] Update work queue when toggling on and off
- [ ]  Listen to work queue and download imagery in background
- [ ] Abort pending download if deselected
- [ ] Remove deselected areas from device

**Comment by scolsen** [comment]
- [ ] Refactor BasemapSelector -> OfflineMaps

**Comment by gino-m** [comment]
Done, and merged into #481.
