### ISSUE TITLE
[Code health] Replace event objects with single values where appropriate

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#100]
Since view models are stateful, we shouldn't need to push additional information into the stream (e.g., `EditRecordViewModel` has `SaveRecordRequest` and `EditRecordRequest` which contain identifying info on which record is being saved). Since there's already shared state, we're no longer using pure FRP anyway, so the extra objects add boilerplate w/o much advantage.

**Comment by scolsen** [comment]
@gino-m assigning to you for code-health cleanup, feel free to assign back if you don't have the bandwith!

**Comment by gino-m** [comment]
@shobhitagarwal1612 @scolsen @rachaprince We should think carefully about this while migrating to Flow (#668, #1581, #1593):

* Events are usually hot streams modeled by `SharedFlow` - no replay on subscribe
* State is usually modeled by a hot streams like `StateFlow`, `SharedStateFlow`, or `LiveData`. - replay on subscribe
* Data and other streaming operations are usually cold streams modeled by `Flow`.

HTH!
Gino

**Comment by scolsen** [comment]
> @shobhitagarwal1612 @scolsen @rachaprince We should think carefully about this while migrating to Flow (#668, #1581, #1593):
> 
> * Events are usually hot streams modeled by `SharedFlow` - no replay on subscribe
> * State is usually modeled by a hot streams like `StateFlow`, `SharedStateFlow`, or `LiveData`. - replay on subscribe
> * Data and other streaming operations are usually cold streams modeled by `Flow`.
> 
> HTH! Gino

sgtm, a few notes about `SharedFlow` and `StateFlow`:

1. `SharedFlow` does support replays and keeps a replay cache of a configurable number of elements. We'll want to make sure we set it to `0` (this is the default for the `shareIn` converter) when using it to model events.
2. `SharedFlow` also uses a buffer (I think of 64 elements) by default, which is also a factor to consider in some cases, but probably won't matter to us most of the time.
3. `MutableSharedFlow` is like `SharedFlow` but will not use a buffer.
4. `MutableStateFlow` might be better for events as its default behavior is to conflate emissions when its value is updated 
    
     > So a slow collector skips fast updates, but always collects the most recently emitted value.

StateFlows only re-emit the latest value: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/.

**Comment by gino-m** [comment]
> > @shobhitagarwal1612 @scolsen @rachaprince We should think carefully about this while migrating to Flow (#668, #1581, #1593):
> > 
> > * Events are usually hot streams modeled by `SharedFlow` - no replay on subscribe
> > * State is usually modeled by a hot streams like `StateFlow`, `SharedStateFlow`, or `LiveData`. - replay on subscribe
> > * Data and other streaming operations are usually cold streams modeled by `Flow`.
> > 
> > HTH! Gino
> 
> sgtm, a few notes about `SharedFlow` and `StateFlow`:
> 
> 1. `SharedFlow` does support replays and keeps a replay cache of a configurable number of elements. We'll want to make sure we set it to `0` (this is the default for the `shareIn` converter) when using it to model events.
> 2. `SharedFlow` also uses a buffer (I think of 64 elements) by default, which is also a factor to consider in some cases, but probably won't matter to us most of the time.
> 3. `MutableSharedFlow` is like `SharedFlow` but will not use a buffer.
> 4. `MutableStateFlow` might be better for events as its default behavior is to conflate emissions when its value is updated
>    > So a slow collector skips fast updates, but always collects the most recently emitted value.
> 
> StateFlows only re-emit the latest value: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/.

Afaik, `SharedFlow` doesn't use a buffer by default; we'd need to set with the `extraBufferCapacity` param. Please cmiiw. Also, when I tried to use `SharedFlow` without a buffer I ran into failing `tryEmit` calls. I needed a buffer of at least 1 for them to work, but I don't quite understand the mechanics. Any ideas?

**Comment by scolsen** [comment]
> Afaik, SharedFlow doesn't use a buffer by default; we'd need to set with the extraBufferCapacity param. Please cmiiw. Also, when I tried to use SharedFlow without a buffer I ran into failing tryEmit calls. I needed a buffer of at least 1 for them to work, but I don't quite understand the mechanics. Any ideas?

The type `SharedFlow` doesn't technically specify a buffer, but in practice all the flow operators one uses to create them will have default buffer sizes. `MutableSharedFlow` is maybe one exception to this as far as I can tell, and doesn't have a buffer by default but a `SharedFlow` created via `shareIn` and other operators will have a buffer by default. I sent over a doc separately that covers this in greater detail. The use of buffers might not impact us negatively in practice, so it might just be a non-issue. Just something for us to look into a bit more and consider.
