### ISSUE TITLE
Should FieldViewModels exist?

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1006]
We always re-create `*FieldViewModel` as a screen can have multiple fields of same type. Does it mean that ViewModel shouldn't exist and all the logic should live in the views instead?

@scolsen @gino-m Wdyt?

**Comment by gino-m** [comment]
> We always re-create `*FieldViewModel` as a screen can have multiple fields of same type. Does it mean that ViewModel shouldn't exist and all the logic should live in the views instead?

From my understanding I don't think so.. The real benefit comes from reduced complexity due to us keeping low-level Android-specific view logic (View) separate from app-specific UI behavior and state (ViewModel), and from the increased testability that comes with it. Besides, the fact that VMs usually have a longer lifecycle than views is opaque to those views, since we must always assume they can be destroyed as well.

**Comment by shobhitagarwal1612** [comment]
I was trying to replace the custom view model factory with the androidx provided solution. Turns out, the api doesn't provide a way to force create a new VM instance. It always returns the last created one. That made me wonder whether what we are doing is the correct approach or not.

**Comment by gino-m** [comment]
> I was trying to replace the custom view model factory with the androidx provided solution. Turns out, the api doesn't provide a way to force create a new VM instance. It always returns the last created one. That made me wonder whether we are using VMs correctly or not.

Iiuc `ViewModelProviders` returns the last instance for a given `Fragment` or `FragmentActivity`. I was thinking about this last night; should anything with its own ViewModel be defined as a Fragment? In that case the androidx helpers would make sense, and they would get their own lifecycle hooks.

**Comment by gino-m** [comment]
Hi @dturner! Qq - if individual form fields have their own ViewModels, is it advisable to implement individual form components as Fragments? Or is that too heavyweight for things like form fields?

**Comment by shobhitagarwal1612** [comment]
This isn't relevant anymore due to migration to tasks. (since tasks have both fragment and viewmodel)
