### ISSUE TITLE
[Add/edit observation] Attach user and timestamp on save

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#101]
Broke while working on #57. This is blocking because permissions model only allows Contributors to edit their own Records, which won't be possible if we don't know who created the record.

**Comment by gino-m** [comment]
@shobhitagarwal1612 @scolsen Any thoughts on how we should represent this internally? Some initial options:

1. Store entire `User` (internal id, email, display name, profile url) or some subset of those fields in each `Feature` and `Observation` and related mutation entities to track and visualize owner in app (i.e. "Submitted by X on..".  Display name can be shown without additional queries, but separate process would be needed to keep them updated in remote db.
2. Cache users in separate table in local db, store only internal id in `Feature` and `Observation`. One extra query (remote and local) for each unique user would be needed when loading record list.

I'm leaning towards #1, because I believe Ground users are more concerned about read performance and Firestore hosting costs than about a potential lag in display names, especially since when working offline there's no way to fetch the latest display names from remote anyway.

Any thoughts?

**Comment by gino-m** [comment]
Haven't heard back so proceeding with Option 1 for now since it's the shortest path. We can either normalize user data, or create offline triggers to update display names and profile pics later if necessary

**Comment by shobhitagarwal1612** [comment]
Sorry for the late reply. 

I'm in favor of option 2 because that would not require us to sync the updated user info in the respective `feature` and `observation`. Regarding read performance, we can modify our `Repositories` to load user data from local db first and then fetch from remote.

**Comment by gino-m** [comment]
> I'm in favor of option 2 because that would not require us to sync the updated user info in the existing `feature` and `observation` entries. Regarding read performance, we can modify our `Repositories` to load user data from local db first and then fetch from remote.

In Firebase you don't have anything like "joins", in which case we would need to send one request for each unique user across all synced Features, and the same for all synced Observations. We would also need to keep all of these users on-device in the User table, and join on that table or create some cache when loading.

Overall this seems to be a lot more work to implement. I'm almost done implementing #1, but we can discuss this further and revisit once we have something working?

**Comment by gino-m** [comment]
Duplicate of #79.
