### ISSUE TITLE
[Docs] Simplify Readme

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#102]
The current `README` is a bit heavy--arguably it should only contain a brief description of the project and the necessary environment setup steps. We can safely assume most contributors are familiar with github and using git, so we should move the more detailed git related instructions into the wiki for those who need them and point to them in the README.md. Keeping the README short and sweet will hopefully make the project more inviting and help contributors get up and running quickly.

Related: #89

**Comment by gino-m** [comment]
Looks like @mmisim already did this, so closing this.
