### ISSUE TITLE
[Code coverage] Unable to open files in codecov

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1023]
Problem:
https://codecov.freshdesk.com/support/solutions/articles/43000593943-files-not-showing-in-codecov-fixing-paths-

**Comment by shobhitagarwal1612** [comment]
The above suggestion related to relative path is unrelated. Tested in https://github.com/google/ground-android/pull/1025

Needs more investigation

**Comment by gino-m** [comment]
@shobhitagarwal1612 Is this still relevant?

**Comment by shobhitagarwal1612** [comment]
Yes. This is still valid

**Comment by gino-m** [comment]
@shobhitagarwal1612 Could you PTAL or close?

**Comment by shobhitagarwal1612** [comment]
Ok. I'll take another pass at this one.
