### ISSUE TITLE
[Code coverage] Merge integration test coverage with unit test coverage

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1024]
Right now, we generate reports for integration tests and pull to cloud bucket. But don't use it anywhere.

We should update the jacoco plugin to merge both .exec files and generate combined report.

**Comment by gino-m** [comment]
We should have good unit test coverage independent of integration tests, so putting this in Icebox for now.

**Comment by gino-m** [comment]
We've disabled integration tests, so marking as obsolete. @shobhitagarwal1612 please reopen if this is incorrect.
