### ISSUE TITLE
[Add polygon] When drawing, last edge is only updated when map stops moving

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1057]
We should update the edge on camera move rather than on drag finished.

@shobhitagarwal1612 Also related to your last PR.. could you PTAL?

**Comment by shobhitagarwal1612** [comment]
SGTM

**Comment by shobhitagarwal1612** [comment]
I created a sample PR with the changes. It shows some performance issues. Possible reasons:

1. We create a new instance of `Point` and `CameraPosition` on each position update.
2. `PolygonDrawingView` listens to position updates regardless of visibility.

**Comment by gino-m** [comment]
Is `GoogleMapsAdapter#setMapFeatures` updating only the changed features as it should, or is it updating all features on each change?

**Comment by shobhitagarwal1612** [comment]
Features are only being updated when the map stops moving. IMO, just the unregulated creation of objects on each camera motion is behind the cause. (Plus a couple of more optimisations)

**Comment by scolsen** [comment]
@shobhitagarwal1612 for current status -- would you like to take this on as well?

**Comment by shobhitagarwal1612** [comment]
Closing in favor of https://github.com/google/ground-android/issues/1839
