### ISSUE TITLE
[Sign in] If user isn't in pass list they can no longer open to app

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1060]
Users can't open the app to change the logged in user once they try to sign in without being in the passlist

**Comment by gino-m** [comment]
Hi @JSunde! Any chance you could look into this one?

**Comment by JSunde** [comment]
Do you have any thoughts on how we should resolve this? I was taking a quick look and it seems like we would ideally be getting a UserSignInError in this case and we could indicate that the user isn't in the pass list, but it seems like the user is being properly signed in and then we're getting the PERMISSION_DENIED exception from Firestore.

I was thinking we could maybe sign the user out when we get the Firestore exception, but I'm guessing there may be other scenarios where we want to be able to handle the permission denied exception without logging the user out.

**Comment by gino-m** [comment]
> Do you have any thoughts on how we should resolve this? I was taking a quick look and it seems like we would ideally be getting a UserSignInError in this case and we could indicate that the user isn't in the pass list, but it seems like the user is being properly signed in and then we're getting the PERMISSION_DENIED exception from Firestore.
> 
> I was thinking we could maybe sign the user out when we get the Firestore exception, but I'm guessing there may be other scenarios where we want to be able to handle the permission denied exception without logging the user out.

In this case does the PERMISSION_DENIED error occur when fetching the survey list? If so perhaps we can sign the user out only when it's received at that step?

That said, I don't think we will ever receive that error from our Firebase queries; the queries should already include a filter to only fetch accessible records, so signing out anytime that error is received it probably a reasonable approach as well.

**Comment by JSunde** [comment]
I believe the PERMISSION_DENIED error might be occurring when we attempt to load the TOS.

I tried signing the user out in the ApplicationErrorManager#handleException, but I think the app is closing before the user can be signed out.

I wonder if there is a way that we can check if the user is in the pass list in the sign in flow and then sign them out before any subsequent firebase queries are made.

**Comment by shobhitagarwal1612** [comment]
What if we show a alert dialog instead of toast and provide an option to signout there if the exception is of type PERMISSION_DENIED?

**Comment by gino-m** [comment]
I think the problem in this case was that the Firebase `onCreateUser` database trigger is only called on the first sign-in. The trigger is supposed to create the user profile in `/users`, but if the user already signed into Firebase once, the trigger won't be called when the user logs in a second time. 

It appears auth triggers are not supported by 2nd gen Cloud Functions:
https://firebase.google.com/docs/functions/auth-events?gen=1st&hl=en

The existing method also has the limitation that the user profile is never updated; we always show the user name or profile pic from the user's first sign-in rather than the latest.

Removing the trigger, renaming and moving the function to an HTTP function (eh `refreshUserProfile()`), and calling it on sign-in should solve all of the above issues.

**Comment by JSunde** [comment]
When you say an HTTP function, is that defined in the Android app? Or is that an API we introduce on the web side and call from the Android app?

**Comment by gino-m** [comment]
> When you say an HTTP function, is that defined in the Android app? Or is that an API we introduce on the web side and call from the Android app?

That would be on the Firebase side, like we currently do here for import, for example:
https://github.com/google/ground-platform/blob/master/functions/src/index.ts#L50

Happy to help update that part if you'd like to team up on this.

**Comment by JSunde** [comment]
That sounds good! Would we need the new HTTP function first?

**Comment by gino-m** [comment]
> That sounds good! Would we need the new HTTP function first?

That's correct. I started looking into doing that, but it looks like it's not trivial to do auth with simple HTTP Cloud Functions. If we use 2nd gen "callable" HTTP Cloud Functions, auth is handled for us:
https://firebase.google.com/docs/functions/callable?gen=2nd

We previously punted on callable functions (https://github.com/google/ground-platform/issues/837#issuecomment-969388138) because they don't support streaming responses, but we may want to rethink this:

* We eventually need to add auth all Cloud Functions (eg #561).
* We're currently doing downloads and uploads synchronously; we may not want to do large uploads or downloads this way, since they'd be likely to timeout anyway.
* All of this is out of scope of this change; we can add a callable function for this particular use case and revisit for other functions.

I'll update once I get further.

**Comment by shobhitagarwal1612** [comment]
This has been resolved by showing a dialog with a signout button in such scenarios
