### ISSUE TITLE
Cleared photo reappears on rotating device 

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1068]
**Describe the bug**
The photo response reappears even after removing it manually. This only happens if the screen is rotated after removing the photo.

**To Reproduce**
1. Select any project which contains a photo field
2. Create a new observation and click on add photo
3. Select a new photo 
4. The selected/captured photo should be visible in the edit fragment.
5. Now, remove the photo and rotate the screen.

**Expected behavior**
Removed photo should not reappear

**Actual behavior**
We can see that the photo is visible.

**Comment by gino-m** [comment]
Probably related to #1067

**Comment by gino-m** [comment]
Possible clue:
 
https://github.com/google/ground-android/blob/96129f1c994f529d19387a3754f61d45bfd5193b/gnd/src/main/java/com/google/android/gnd/ui/editobservation/EditObservationViewModel.java#L91-L93

LiveData replays last value on observe. For a stream of events, Flowable or Observable might be more appropriate.

**Comment by gino-m** [comment]
Also, something strange I've noticed is that we have duplicate state for the form responses in the field VMs and EditObservationViewModel.responses itself. The latter gets explicitly reset on config change in the VM method `onObservationLoaded`. I think the lifecycle is a bit muddled and needs to be defined better, especially loading the form and observation wrt. config change and camera events.

**Comment by gino-m** [comment]
This is still occurring.
