### ISSUE TITLE
[Code health] Clean up `ApplicationErrorManager`

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1074]
Some quick wins:

* Inject and use EphemeralPopups directly instead of binding to Activity.
* How errors are handled depends on the use case; expose finer-grained handlers, e.g. `handlePermissionDeniedErrors`.
* Permission denied may also occur due other Firebase rules besides passlist, e.g. to lack of ACLs in project. Error message should be more general (e.g., "Permission denied").
* Consider letting `handlePermissionDeniedErrors` returns a lambda to simplify Rx syntax or use Rx `compose()`, remove `shouldInterceptException()`.
* Tests currently look for specific strings copy & pasted from resources. We should avoid change detector tests - motivation: https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html

**Comment by shobhitagarwal1612** [comment]
This is no longer relevant. The class has been removed and now error handling is done at the calling place instead of globally.
