### ISSUE TITLE
[Code health] Photos uploaded again on config change

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1080]
`lastPhotoResult` in `EditObservationViewModel` replays the last value on subscribe, which will cause the `PhotoFieldViewModel` to upload the photo again. @shobhitagarwal1612 FYI.

**Comment by gino-m** [comment]
@shobhitagarwal1612 Do you know if this was ever fixed?

**Comment by gino-m** [comment]
@shobhitagarwal1612 Gentle ping

**Comment by shobhitagarwal1612** [comment]
While testing this, I found that localMutationSyncWorker isn't getting invoked for syncing the data with firestore.

**Comment by shobhitagarwal1612** [comment]
I attempted to test the photo upload flow end-to-end and it is broken at the moment. The worker isn't able to upload the file as it can't find the locally saved file.

**Comment by shobhitagarwal1612** [comment]
Marking this as resolved. The photo is uploaded at the end of the submission, so config change doesn't re-upload the image. Will fix the bug regarding failure to upload separately
