### ISSUE TITLE
[Edit feature] Allow users to reposition point features

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#109]
Allow feature creators and project managers to move point features around on the map after they've been added.

The related sync and merge feature mutation functionality will also need to be implemented.

**Comment by sergeydolgov1** [comment]
Suggested flow for repositioning Points:
1) User clicks on a point
2) Feature (Point) Toolbar appears (empty or with some observations)
3) User clicks on the ellipsis (three dots) in the top right corner and selects "Reposition point"
4) Toolbar disappears/ Crosshair appears on the map (same flow as when user places new point)
5) User selects new location on the maps
6) When clicking on "+" (can be replaced with a V-shaped checkmark), user sees a dialog: Do you want to reposition to this location"? Two buttons: Confirm and Cancel
7) If user clicks on Confirm, dialog disappears and the Point is repositioned to the new location. If user clicks on Cancel, dialog disappears and the map pans to initial point location, centered on the point.

**Comment by sergeydolgov1** [comment]
@shobhitagarwal1612 What question is blocking us?

**Comment by gino-m** [comment]
@sergeydolgov1, @shobhitagarwal1612 and I just spoke; mocks would be ideal, but for expediency your above description is sufficient. Thanks for providing so much detail.

**Comment by gino-m** [comment]
Some ideas for potential PRs:
- [ ] Add UI flow to reposition, add mutation to db.
- [ ] Implement "update" mutation on Features (update location).

**Comment by shobhitagarwal1612** [comment]
Starting working on this now.
