### ISSUE TITLE
[Docs] Possible outdated documentation

### ISSUE THREAD

**Issue by wesleytanws** [google/ground-android#1094]
We have identified **`1`** possible instance of outdated documentation:

- [ ] [`addFeatureClicks`](https://github.com/google/ground-android/blob/c1a4c245c6818f8ed0f9f5c7a733d62ec3894cfd/gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java#L79) was renamed to [`addFeatureRequests`](https://github.com/google/ground-android/blob/a6b3d09d2257a36a6c55927bb289848156a2a46c/gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java#L82) but the change has not been reflected in the current version of the [RxJava Usage and Conventions](https://github.com/google/ground-android/wiki/RxJava-Usage-and-Conventions/7a7ced844034eebd48c4c6180d2c2cb15a8893c3) wiki page

#### About
This is part of a research project that aims to automatically detect outdated documentation in GitHub repositories. We are evaluating the validity of our approach by identifying instances of outdated documentation in real-world projects.

We hope that this research will be a step towards keeping documentation up-to-date. If this has been helpful, consider updating the documentation to keep it in sync with the source code. If this has not been helpful, consider updating this issue with an explanation, so that we can improve our approach. Thanks!

**Comment by gino-m** [comment]
Hi! The reference is a generic example, whereas the code cited is a concrete instance. The two need not be kept in sync. Thanks for reporting anyway!
