### ISSUE TITLE
[Offline support] Show notifications with data sync progress

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#110]
Blocked by #17

**Comment by shobhitagarwal1612** [comment]
Is someone working on this?

**Comment by gino-m** [comment]
> Is anyone working on this?

Not yet! Interested?

**Comment by shobhitagarwal1612** [comment]
Yes. This looks interesting.

**Comment by gino-m** [comment]
All yours! Let's discuss design before starting, please ping or set up a VC!

**Comment by shobhitagarwal1612** [comment]
Will do!
