### ISSUE TITLE
[Migration] Rename classes and members in code

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1114]
This change should be restricted to references at the code level and should not be applied to the collection and document names in Firestore:

- [x] Project -> Survey [@shobhitagarwal1612]
- [x] Layers -> Job [@shobhitagarwal1612]
- [x] Forms -> Task [@jsunde]
- [x] Feature -> LocationOfInterest [@scolsen]
- [x] Element -> Step [@JSunde]
- [x] Observation -> Submission [@JSunde]
-  User roles:
  - [x] manager -> survey-organizer  [@JSunde]
  - [x] contributor -> data-collector [@JSunde]

**Comment by JSunde** [comment]
I'll start working on renaming Observation -> Submission

**Comment by JSunde** [comment]
I don't really see any results when searching for "Question" in the codebase. @gino-m Was there something else we should be renaming to Step or is it a newer concept that doesn't already exist in the codebase?

**Comment by gino-m** [comment]
> I don't really see any results when searching for "Question" in the codebase. @gino-m Was there something else we should be renaming to Step or is it a newer concept that doesn't already exist in the codebase?

I think `Question` was never explicitly modeled because in the prototype it was 1:1 with form `Element`s. Updating the GitHub issue accordingly.

**Comment by JSunde** [comment]
What are some examples of `manager` that need to be renamed? I'm having a hard time finding it with all of the other usages like FragmentManager, LayoutManager, AuthenticationManager...

**Comment by gino-m** [comment]
> What are some examples of `manager` that need to be renamed? I'm having a hard time finding it with all of the other usages like FragmentManager, LayoutManager, AuthenticationManager...

Ah, that was referring to renaming of User roles, not the keyword "manager" anywhere it occurs. Sorry for the confusion.
