### ISSUE TITLE
[Offline imagery] Create global cloud free mosaic

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#112]
Using freely available data sources, with pyramids in mbtiles format and extends in GeoJSON.

**Comment by gino-m** [comment]
Assigning for now to make this issue easier to find - let's discuss in more detail offline once we get to it!

**Comment by gino-m** [comment]
Moved this to RC1, since for MVP we can use exports of specific areas.

**Comment by scolsen** [comment]
Closing in favor of #1596
