### ISSUE TITLE
[Sync] Create a Foreground service and notification for continuous sync status

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1125]
Create a [Foreground service](https://developer.android.com/guide/components/services#Foreground) and related placeholder notification for continuous sync status. This is also needed to be able to downloading updates and record GPS tracks in background.

**Comment by nikhil6624** [comment]
Hi @gino-m  , May I work on this feature request?

**Comment by gino-m** [comment]
Closing as obsolete.
