### ISSUE TITLE
[Model] Disambiguate "task" by merging with "step"

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1164]
When discussing the current model with @coreyleamon, it was apparent that our current use of "task" and "step" are not intuitive and self-describing:

* "Task" is currently ambiguous, with different people using it to refer to different things.
* "Sub-steps" is not ergonomic. It's much more idiomatic to say "a task can be broken into a [repeated] set of sub-tasks".
* When describing steps, "Take a photo task" is more idiomatic than "Take a photo step".

To clarify this, we agreed to do the following:

- [x] Rename `element` to `step` [@shobhitagarwal1612]
- [ ] Move `steps` up to `job` and delete `tasks`
- [ ] Rename `steps` to `tasks`

We currently also sometimes use "task" to describe "a job that needs to be done a particular location". Instead, we can simply refer to that descriptively as "job @ location", as in "where has the job been completed, vs. where does the job still need to be done".

See also https://github.com/google/ground-platform/issues/913

**Comment by shobhitagarwal1612** [comment]
@gino-m Can we close this?

**Comment by gino-m** [comment]
Yes, thank you!
