### ISSUE TITLE
[Code health] Cloud Build notifiers

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1177]
Setup alert when instrumentation tests fail on master branch

Recently, we removed running instrumentation tests for PR branches. Also, GCB doesn't provide out-of-the-box solution for build failures. 

Either setup a custom notification system for build failures or explore GCB documentation for any related features.

**Comment by shobhitagarwal1612** [comment]
https://cloud.google.com/build/docs/configuring-notifications/notifiers

**Comment by gino-m** [comment]
We spoke. @shobhitagarwal1612 reported that email notifications would require setting up and maintaining an SMTP server, which would be significantly more work. We can skip this for now and rely on chat notifications.
