### ISSUE TITLE
SharedTest reports warning "Duplicate content roots detected"

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1185]
Instrumentation tests aren't able to find shared test classes due to the following error.

```
Duplicate content roots detected: Path [/Users/ashobhit/Desktop/Code/ground-android/ground/src/sharedTest/java] of module [ground-android.ground.unitTest] was removed from modules [ground-android.ground.androidTest]
```

Related article

**Comment by shobhitagarwal1612** [comment]
According to https://issuetracker.google.com/issues/232007221 ("Duplicate content roots detected" with Android Gradle plugin 7.2.0) Google no longer supports this construct in Android Studio Chipmunk 2021.2.1.

https://issuetracker.google.com/issues/232007221#comment17 says "Source sets can no longer contain shared roots as this is impossible to represent in the IDE."

**Comment by shobhitagarwal1612** [comment]
https://stackoverflow.com/questions/72218645/shared-srcdirs-between-test-and-androidtest-unresolved-references-after-upgrade

**Comment by gino-m** [comment]
From that same article:

> Basically, create an android library (sharedTestCode), depend on it in your app via testImplementation and androidTestImplementation. In the sharedTestCode build.gradle file, depend on the app. You should now be able to create shared test data and reference them in both types of tests.

Would you like to take this one? You may want to wait until #1184 is merged, since there will probably be many merge conflicts.

**Comment by gino-m** [comment]
One more data point: Not sure if it's related, but I see the sharedTest module shows up as "test" in my version of AS Chipmunk:

![image](https://user-images.githubusercontent.com/228050/182048698-5b3c7966-e4da-4099-a387-b1ed5f98b164.png)
