### ISSUE TITLE
Cloud builds failing due to duplicate BuildConfig classes

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1197]
@shobhitagarwal1612 Is this related to the refactor of the shared test classes?

Latest log:
https://pantheon.corp.google.com/cloud-build/builds/dfa0e6be-c7d1-4e9a-a30b-0c0ac2495446;step=3?project=ground-android-gcb

**Comment by shobhitagarwal1612** [comment]
The only solution I was able to prototype was by removing the `sharedTest` module and moving the fake implementations to the main dir

**Comment by gino-m** [comment]
> The only solution I was able to prototype was by removing the `sharedTest` module and moving the fake implementations to the main dir

Does that mean the shared test classes will end up in the apk? Or they'll probably be removed since they're not referenced at runtime?
