### ISSUE TITLE
[Code health] Clean up TaskData.getDetailsText()

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1240]
The detail text for the task data should be handled in the view layer so that we can correctly generate it depending on the Response Type and the user's locale.

**Comment by gino-m** [comment]
@JSunde Could you PTAL?

**Comment by JSunde** [comment]
I'm not sure I fully understand the context of this issue that I filed 😅  TaskData#getDetailsText() is implemented by the various TaskData types so that piece is already handled, but as far as the localization goes, I don't think that would be possible since the text is either based on the user input or the multiple choice options defined in the survey which comes from the server.

I'm going to close as not planned.
