### ISSUE TITLE
[Persistence] Write Polygon holes to the local db

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#1247]
Currently, we only store the outer shell of polygons in the local database, but our model supports polygons with holes. We'll need to write the hole rings to the database as well.

**Comment by gino-m** [comment]
@JSunde Was this fixed once we started persisting geometries using proto wire format?

**Comment by JSunde** [comment]
I believe so, the GeometryWrapperTypeConverter writes the entire geometry object to a ProtoBuf
