### ISSUE TITLE
[Code health] Convert all `@Singleton`s to Kotlin `object`s

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#1310]
Kotlin has nice native support for declaring singletons using `object` declarations. Unfortunately, Dagger does not support injecting classes into `objects`, which at the moment pretty much prevents us from using an object for any construct that needs to depend on classes we'd normally inject.

If we convert all the classes we've currently marked as `@Singleton` into `objects` we can drop the several injections which should make kotlin code easier to refactor.

**Comment by gino-m** [comment]
Since we don't want to discourage using injection as a way of decoupling components, I'd think we'd want to err on the side of using `@Singleton` instead of `object`. Closing this for now until we have a stronger case for doing so.
