### ISSUE TITLE
[Code health] Merge the two HiltTestActivity classes

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1334]

**Comment by nikhil6624** [comment]
@shobhitagarwal1612 , may I resolve this please? (I have already signed Google's CLA as part of the other issue in this repo).

**Comment by shobhitagarwal1612** [comment]
Please feel free to give it a try :)

**Comment by nikhil6624** [comment]
Thanks @shobhitagarwal1612 . Could you please let me create a separate branch so that I can push my changes and then raise a pull request to Master branch.?

**Comment by gino-m** [comment]
To get started, please fork this repository and create a branch in your own repo. When ready, you can create a PR to pull commits into our repo. Please also feel free to send an early draft PR to make sure we're on the same page!

**Comment by nikhil6624** [comment]
Sure @shobhitagarwal1612 . Will do that.
