### ISSUE TITLE
[Job/LOI cards] Display number of submissions

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1347]
For discussion with @ngosue. Perhaps we can generalize "completion" by simply showing the submission count and changing styling/iconography when the count > 0. For example:

✅ 3 submissions

**Comment by JSunde** [comment]
@gino-m if there are no submissions, do we want the UI to show "0 submissions" or should we just not show this string in that case?

**Comment by gino-m** [comment]
> @gino-m if there are no submissions, do we want the UI to show "0 submissions" or should we just not show this string in that case?

As a first step "0 submissions" would work. In the future we may want to give job cards and text different treatments for 0 vs >0, but for now this should suffice.

**Comment by JSunde** [comment]
Huh... it looks like we already have this?
![image](https://github.com/google/ground-android/assets/9056308/c5a07a2a-22e0-4ba3-8d57-7e7e9c365258)

**Comment by JSunde** [comment]
And there's even a special case that says "No submissions" if there are none, so this is already done!
