### ISSUE TITLE
[Survey sync] Implement survey load and background sync

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1373]
As mentioned in #988, the current survey and LOI sync is bound to the view layer, and relies on Firestore SDK to report changes over time. 

Instead, I propose we move towards a more robust design:

1. User selects survey from survey list for the first time.
2. Survey and LOIs are loaded and stored in the local db.
3. App subscribes to [FCM](https://firebase.google.com/products/cloud-messaging) topic associated with survey ID.
4. [Firestore triggers](https://firebase.google.com/docs/functions/firestore-events) on survey and LOI write send a collapsible message (no data payload) to the related topic.
5. A custom messaging service in the app receives the ping and schedules a background worker to do a sync latest survey and LOIs to local db as soon as possible.
6. Background worker syncs latest survey and LOIs to local db.
8. When users reopen an already synced survey, remote fetch is not required since it's already done in the background.

@shobhitagarwal1612 Wdyt?

Background sync can initially refetch the survey and all LOIs. Production impl should also implement the following:

* Implement soft-deletion of LOIs (via web):
  * Mark with `state: 'deleted'` instead of deleting
  * Update `lastModified` audit info on delete
  * Periodically clean up deleted LOIs
* On sync, only fetch LOIs with `lastModified.serverTimestamp` > server timestamp at last sync. Returned LOIs marked `state: 'deleted'` should be removed from local db.
* If app has been inactive for longer than LOI TTY, IDs of all remote LOIs in survey should be fetched and missing ones deleted from local db.

@os-micmec Wdyt?

**Comment by shobhitagarwal1612** [comment]
This trigger function would be written as a cloud function, right?

**Comment by gino-m** [comment]
> This trigger function would be written as a cloud function, right?

Correct. WIP prototype in https://github.com/google/ground-platform/pull/1020/files.

**Comment by gino-m** [comment]
Prototype is working, submitting actual implementation in parts as follows:

- [ ] Add worker to sync survey definitions (jobs, tasks, etc)
- [ ] Add service to enqueue work on new messages
- [ ] Retry sync on errors
- [ ] Add ability to sync LOIs
- [ ] Handle deletion of LOIs on remote server
- [ ] Handle deletion of survey on remote server
