### ISSUE TITLE
[Code health] Rename DataSyncWorkManager to MutationSyncWorkManager

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1374]
- [ ] The name `DataSyncWorkManager` is too broad and should be named to more closely reflect its scope, eg `MutationSyncWorkManager`.
- [ ] `BaseWorkManager` and subclasses aren't `WorkManager`s. Naming them as such is potentially misleading. Suggest renaming to `*SyncService` or similar.

**Comment by EmmanuelDav** [comment]
@gino-m  I would love to handle this issue

**Comment by gino-m** [comment]
> @gino-m I would love to handle this issue

Sure, please go ahead! Be sure to sign https://cla.developers.google.com/ when you get a sec.

**Comment by EmmanuelDav** [comment]
I have created a pull request and I have signed the Agreement. I look forward to more contributions
