### ISSUE TITLE
[Build] Failing at HEAD due to ktfmt issues

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1385]
Build fails with:

`[ktfmt] Invalid formatting for: /workspace/ground/src/main/java/com/google/android/ground/ui/common/AbstractMapViewModel.kt`

I believe this may be the commit in question:
https://github.com/google/ground-android/commit/946a75fa031aefe690e212da2d9cd22d3a661f9d

@shobhitagarwal1612 Can you PTAL?

**Comment by shobhitagarwal1612** [comment]
Resolved in https://github.com/google/ground-android/pull/1384
