### ISSUE TITLE
[Code health] Rename `RemoteStorageModule` to `RemotePersistenceModule`

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1399]
The `RemoteStorageModule` handles more that "remote storage", which in our codebase refers file storage provided by Firebase Cloud Storage; it also handles remote db (Firestore) access, and UUID generation, so `RemotePersistenceModule` would be a more appropriate name.

**Comment by arun-kushwaha04** [comment]
@gino-m i would like to work on this issue if it's available.

**Comment by gino-m** [comment]
> @gino-m i would like to work on this issue if it's available.

Sure, please go ahead! Please be sure to sign the CLA at https://cla.developers.google.com/ before beginning.
