### ISSUE TITLE
[Data Collection] Add "Retake picture" button to Photo task

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1414]
Currently after the user captures a photo in the Photo data collection task the image preview is shown as well as a trash can button in the corner allowing the user to remove the photo and re-capture. Instead we want a text button below the image that says "Retake picture".

![image](https://user-images.githubusercontent.com/9056308/212108790-720dcb33-fc48-4d1d-aa6e-349bbbed0a9a.png)

**Comment by shobhitagarwal1612** [comment]
@gino-m Is this obsolete too?

**Comment by gino-m** [comment]
Is there an easy way to retake the photo today? I don't have the designs at hand.

**Comment by shobhitagarwal1612** [comment]
Users can click "Undo" button to clear the previously captured photo and then click "Take a picture" again.

**Comment by gino-m** [comment]
Ok, then closing this as obsolete.
