### ISSUE TITLE
[Code health] Replace ImmutableList with List 

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1433]
`List` in kotlin is already immutable. So, we should get rid of `toImmutableList()` usages and eventually remove `com.google.common.collect` dependency.

**Comment by scolsen** [comment]
I'm not sure that we should do this actually -- there are a few reasons to keep using `ImmutableList` instead of Kotlin's `List`. The short reason is that Kotlin's immutability is not as strong as the immutability in guava -- it's more or less immutability in name only.

**Comment by gino-m** [comment]
Alternatively, we could use kotlinx immutable https://github.com/Kotlin/kotlinx.collections.immutable

**Comment by shobhitagarwal1612** [comment]
Duplicate of #1466
