### ISSUE TITLE
[Join survey] Join survey dialog not shown after login

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1436]

**Comment by shobhitagarwal1612** [comment]
We would be getting rid of the dialog in favour of proposed home screen. Isn't this irrelevant?

**Comment by gino-m** [comment]
> We would be getting rid of the dialog in favour of proposed home screen. Isn't this irrelevant?

Not if we can implement the new home screen UI. Would you like to take that one on? Final UX is pending, but maybe you can start with the business logic?

**Comment by shobhitagarwal1612** [comment]
Closing in favour of https://github.com/google/ground-android/issues/504
