### ISSUE TITLE
Misalignment in Multiple Choice Task

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1443]
Multiple choice task radio buttons are not properly aligned. They appear to be centered between the header and the continue button, but they should be top aligned.

**Comment by JSunde** [comment]
![image](https://user-images.githubusercontent.com/9056308/214153894-18e05d33-5992-4f28-9e12-3d12d4c667fa.png)

**Comment by gino-m** [comment]
Obsolete issue.
