### ISSUE TITLE
[Data collection] Show camera inline when taking photo

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1449]
Currently the Photo Capture task intents to the camera app for the user to capture a photo, but the mocks show an embedded camera fragment allowing the user to capture a photo without leaving the app.

I'm thinking this should be p2 and not block the current prototype. What are your thoughts @gino-m?

**Comment by shobhitagarwal1612** [comment]
The latest mocks do not contain inline camera widget. Can we close this?
