### ISSUE TITLE
[Survey Selector] Auto-refresh survey list when remote data changes

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1451]
SurveyRepository currently returns `Single` list of surveys instead of `Flowable`. Because of this, the list needs to be manually refreshed. Make the remote datastore return a `Flowable` and update the new survey selector fragment.

**Comment by gino-m** [comment]
@shobhitagarwal1612 +1. Moving to Icebox for now, but we can come back to this.

Note: Let's use the "Feature" attribute instead of labels for feature type.
