### ISSUE TITLE
[Offline support] If opening feature while offline, show offline warning

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#146]

**Comment by shobhitagarwal1612** [comment]
How about using snackbars (also for other network connectivity changes)?
https://material-ui.com/components/snackbars/

**Comment by gino-m** [comment]
Snackbars are meant to appear and disappear; this issue was more geared towards a warning about the observation list that the data might be out of data since it was coming from local cache. Compare with #434. @coreyleamon in case you have anything to add here.

**Comment by coreyleamon** [comment]
Is this related to the other issue regarding a prompt for the device being offline?
Yes as @gino-m mentioned, snackbars are useful for a quick warning or validation (they can either disappear or sustain until a user closes it), but if we need to help the user make a decision as a result, a native dialog may serve better.

**Comment by gino-m** [comment]
In general I would say we need to remind the user data may be out of date, since the same could apply for all data shown in the app.

The feature sheet / observation list _could_ be an exception, since we don't pre-load observations, and when the user taps a feature while offline, all feature sheets that haven't been previously opened while online will show a message "No observations for this feature. Click + Observation to add one." or similar. It seemed like this could be misleading in the case they're offline and haven't previously loaded the list.

**Comment by gino-m** [comment]
Duplicate of #355.
