### ISSUE TITLE
[Offline support] Verify that Kotlin binary serialization allows for additive changes to classes

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1461]
@JSunde Are we able to add new fields? I assume they'd need to be nullable to be able to support objects persisted with older versions of the app? Any other constraints to be aware of?

**Comment by JSunde** [comment]
I'm having a hard time finding any documentation on whether CBOR is backwards compatible or not.

I found this github project called [Probor](https://github.com/tailhook/probor) which mentions that in addition to CBOR it has "Conventions to make schema backwards compatible", which leads me to believe that maybe CBOR isn't backwards compatible?

**Comment by JSunde** [comment]
I wonder if we should use Protobufs in that case.

[kotlinx-serialization-protobuf](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#protobuf)

**Comment by gino-m** [comment]
> I wonder if we should use Protobufs in that case.
> 
> [kotlinx-serialization-protobuf](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#protobuf)

One more reason to create shared protobufs that could eventually be used by a gRPC or other API.
