### ISSUE TITLE
[Code health] Replace immutable Guava collections with Kotlin read-only collections

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1466]
To help bring code closer to idiomatic Kotlin.

**Comment by scolsen** [comment]
Is closure of this one just waiting on elimination of Guava in tests? I'm still a bit concerned that we might be dropping Guava and adopting an experimental API a bit earlier than we really should be (it's still in [alpha](https://kotlinlang.org/docs/components-stability.html#stability-levels-explained)). The immutable collection library we've adopted is subject to future possible API changes and is not yet in a yet where any amount of stability is promised. Hopefully it's unlikely that will affect us but we should be ready to accept potentially small costs as that API stabilizes.

**Comment by gino-m** [comment]
> Is closure of this one just waiting on elimination of Guava in tests? I'm still a bit concerned that we might be dropping Guava and adopting an experimental API a bit earlier than we really should be (it's still in [alpha](https://kotlinlang.org/docs/components-stability.html#stability-levels-explained)). The immutable collection library we've adopted is subject to future possible API changes and is not yet in a yet where any amount of stability is promised. Hopefully it's unlikely that will affect us but we should be ready to accept potentially small costs as that API stabilizes.

This issue refers to libs in the Kotlin standard lib, not to https://github.com/Kotlin/kotlinx.collections.immutable.
