### ISSUE TITLE
[Job cards] Several discrepancies with UX designs

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1483]
- [x] Cards should be taller
- [x] Cards to left and right should peek onto screen
- [x] Point or polygon icon should be shown next to LOI name/ID
- [x] "Point" or "Area" should be shown when LOI has no name/ID
- [ ] Select card outline color does not correspond to color of job <-- To discuss with @vittorino 
- [ ] A message should be shown indicating the number of submissions, or "No submissions" if none.

Current impl:

![image](https://user-images.githubusercontent.com/228050/215667466-59be746e-d4b8-4611-b65e-d4283008d60b.png)

Designs:
![image](https://user-images.githubusercontent.com/228050/215666777-22bdaa3d-442d-4a8b-a0d2-c4dba225dd6c.png)

@shobhitagarwal1612 could you PTAL?

**Comment by shobhitagarwal1612** [comment]
Updated the list in description with completed tasks.

**Comment by shobhitagarwal1612** [comment]
Resuming work on this bug.
