### ISSUE TITLE
[Offline support] Allow user to add/remove accounts for offline use

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#15]
The prototype currently requests sign-in when opening the app. If the user signs out while offline, the app currently becomes unusable, since there's no way to log back in. In order to properly support offline use, account tokens will likely need to be stored locally.

- [ ] Ensure workers connect to remote using user initiating mutation, not current user
- [ ] When user removed, also remove all pending mutations 
- [ ] Verify error handling and race conditions when syncing mutations from deleted users
- [ ] List users UI
- [ ] Add user UI
- [ ] Remove user UI

**Comment by gino-m** [comment]
Hi @chinesco did you mean to close this or another issue?

**Comment by gino-m** [comment]
At the very least we should change the UI to make it harder for the user to accidentally sign out while offline. @ngosue FYI.

**Comment by scolsen** [comment]
@gino-m -- firebase should store these for us, close in favor of making it hard to log out while offline.

Closing this in favor of a bug around offline logout.

**Comment by scolsen** [comment]
Tracking against #769. Closing.
