### ISSUE TITLE
[Bug] Rendered points are not removed after switching survey

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1502]
**Describe the bug**
All points from previous survey should be removed after switching to a new survey

**To Reproduce**
1. Select a survey which contains some point LOIs
2. Ensure that the points are rendered
3. Switch to another survey which doesn't contain any LOIs

**Expected behavior**
No points or clusters should be visible

**Actual behavior**
Both points and clusters are visible

**Comment by JSunde** [comment]
I'm not able to reproduce this on the latest from head.
