### ISSUE TITLE
[Code health] Add support for manually triggering instrumentation tests for PR

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1511]
Context

[Can we create a separate check that fails until we add a specific label, and then runs once the label is added?](https://github.com/google/ground-android/pull/1505#issuecomment-1416530612)

**Comment by scolsen** [comment]
@shobhitagarwal1612 want to take this one?

**Comment by shobhitagarwal1612** [comment]
Given the flaky nature of current instrumentation tests, I would recommend converting all existing instrumentation tests to unit tests. Triggering them based on label/comments would require support from the GCB itself.

**Comment by shobhitagarwal1612** [comment]
All instrumentation tests have been converted to unit tests. Closing this for now.
