### ISSUE TITLE
Tapping an LOI should focus its respective job card, not show the old bottom sheet and zoom/pan

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1530]

**Comment by shobhitagarwal1612** [comment]
@gino-m What should be the behaviour if the click is ambiguous?

**Comment by gino-m** [comment]
> @gino-m What should be the behavior if the click is ambiguous?

We can focus on the first card associated with LOIs overlapping at that location. Users can swipe through cards to identify other LOIs.
