### ISSUE TITLE
[Code health] Update GCB docker images to android sdk tools 30.0.3

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1534]
This would speed up the overall GCB runtime by eliminating the extra download step.

**Comment by scolsen** [comment]
@shobhitagarwal1612 assigning to you for now. Let's target RC1 for this.

**Comment by shobhitagarwal1612** [comment]
We should add the instructions to the README as well since this is a routine task that needs to be done after every sdk bump.
