### ISSUE TITLE
[Data Collection] Suggest new LOI + collect data

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1541]
We want to have a special task type which is a variant of the DropAPinTask allowing the user to suggest a new LOI.

**Comment by JSunde** [comment]
The premise of this feature is that we would have some entry point to initiate a job without an associated LOI and the first task of that job would be to "Drop a pin" or "Draw an area" which would create the LOI that the submission would be associated with.

**Comment by scolsen** [comment]
@JSunde is most of the way there on this; we need to clarify some product requirements but will proceed with an initial implementation.

**Comment by gino-m** [comment]
We spoke, done!
