### ISSUE TITLE
[Data Collection] Reuse edit flow for temporary “view submission” capability

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1542]
In order to allow users to view and edit submissions we plan to reuse the existing Data Collection flow.

**Comment by JSunde** [comment]
I think this is at least partially blocked by #1542 since we will need to be able to load the job and task details for an existing submission.

**Comment by scolsen** [comment]
Also need to add a submissions list to unblock this.

**Comment by scolsen** [comment]
Also blocked on/related to #352

**Comment by gino-m** [comment]
We still don't designs for view/edit. Let's close this for now, @vittorino let's discuss designs.
