### ISSUE TITLE
[Main Map] LOI style not consistently updating when selected (tap or card swipe); currently requires zoom out and back in to update.

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#1557]
Style should update immediately upon LOI interaction (tap/card movement).

**Comment by gino-m** [comment]
@shobhitagarwal1612 Any chance you could take a look or close if already fixed?

**Comment by shobhitagarwal1612** [comment]
We are using a static styling for all LOIs. Not sure what this bug is about.
