### ISSUE TITLE
[Code health] Migrate data layers to coroutines

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1581]
- [ ] Local DAOs
- [ ] Local data store
- [x] Remote data store
- [ ] Manager / system services
- [ ] Proceed per use case / feature
- [ ] Worker

Be sure to follow [best practices](https://developer.android.com/kotlin/coroutines/coroutines-best-practices) and ensure suspend functions are main-safe.

**Comment by gino-m** [comment]
@scolsen @shobhitagarwal1612 @JSunde Shall we split this work up somehow? Maybe we'll be more likely to get it done in a reasonable time frame and it will accelerate other work?

**Comment by shobhitagarwal1612** [comment]
Just curious, how would it speed up other things?

**Comment by scolsen** [comment]
I'm happy to take at least some of the DAOs and data store as I had already experimented with converting some of them: https://github.com/google/ground-android/pull/1405.

**Comment by gino-m** [comment]
Closing in favor of #1593.
