### ISSUE TITLE
Rename local store interfaces to include `Local` prefix

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1590]
In `com.google.android.ground.persistence.local.stores`
* `MutationStore` -> `LocalMutationStore`
* `SubmissionStore` -> `LocalSubmissionStore`

**Comment by devedroy** [comment]
Hello @gino-m ,
I'm a Android developer and I'm new to contributing to opensource.
I would like to take up this issue.
Can you please assign this issue to me.
Thanks.
