### ISSUE TITLE
Migrate Rx to Coroutines

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1593]
* Events are usually hot streams modeled by `SharedFlow` - no replay on subscribe
* State is usually modeled by a hot streams like `StateFlow`, `SharedStateFlow`, or `LiveData`. - replay on subscribe
* Data and other streaming operations are usually cold streams modeled by `Flow`.

Be sure to follow [best practices](https://developer.android.com/kotlin/coroutines/coroutines-best-practices) and ensure suspend functions are main-safe.

**Comment by scolsen** [comment]
Part of coroutines migration: #1581
