### ISSUE TITLE
[Offline support] Allow user to join/leave multiple projects

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#16]
Project definitions would need to be explicitly stored locally so user can switch projects when offline.

Blocked by #19.

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612 ok to assign to you for now, as you already started this feature? Let's discuss details before starting work on it.

**Comment by shobhitagarwal1612** [comment]
@gino-m Can we close this one?

**Comment by gino-m** [comment]
Yep, thanks!
