### ISSUE TITLE
[Data Collection] Camera is not launched after permission is granted

### ISSUE THREAD

**Issue by JSunde** [google/ground-android#1600]
When completing a Photo task the user is prompted for the camera permission, however if they decline the permission they will be prompted again when pressing the "Capture photo" button, then if the permission is granted the camera should be launched, but it is not so the user must press the button again.

**Comment by gino-m** [comment]
@shobhitagarwal1612 recalls that this happens only this _first_ time the camera is opened on the device.

**Comment by scolsen** [comment]
Just saw this happen again today.

**Comment by shobhitagarwal1612** [comment]
> Just saw this happen again today.

I'm unable to repro this bug. Could you please help with the repro steps? @scolsen

**Comment by gino-m** [comment]
Iirc this only occurs on the emulator. Closing for now as WAI.
