### ISSUE TITLE
Surveys in survey list out of order

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1615]
Surveys available offline should be shown first, followed by other surveys.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/228050/223457272-b73e05a2-00b7-46a4-81f4-9af7af567817.png">

**Comment by gino-m** [comment]
@shobhitagarwal1612 PTAL?

**Comment by shobhitagarwal1612** [comment]
Will take a look. Should be a small fix.
