### ISSUE TITLE
Cleanup PolygonDrawingInfoDialogFragment and it's tests

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1664]
PolygonDrawingInfoDialogFragment is no longer used and should be cleaned up.

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 ,
I would like to take up this issue.
Can you please assign this to me?

**Comment by shobhitagarwal1612** [comment]
Hey @devedroy! Can you please resolve the bug that is already assigned to you before taking this one up?

**Comment by devedroy** [comment]
Hi @shobhitagarwal1612,
May I take up and solve this issue?
