### ISSUE TITLE
Cleanup LocationOfInterestDataTypeSelectorDialogFragment and it's tests

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1665]
LocationOfInterestDataTypeSelectorDialogFragment is no longer used and should be cleaned up.

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 
I would like to take this issue up.
Can you please assign this issue to me?

**Comment by shobhitagarwal1612** [comment]
Hey @devedroy! Can you please resolve the bug that is already assigned to you before taking this one up?

**Comment by devedroy** [comment]
Hello @shobhitagarwal1612 
Can I take this issue now?

**Comment by shobhitagarwal1612** [comment]
Sure
