### ISSUE TITLE
App crashes when attempting to create submissions as a Viewer

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1667]
```
(24.4.1) [WriteStream]: (5709729) Stream closed with status: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}.
(24.4.1) [Firestore]: Write failed at surveys/<id>/submissions/<id>: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
```

**Comment by shobhitagarwal1612** [comment]
@gino-m @vittorino Need inputs for UX mocks.

**Comment by gino-m** [comment]
> mocks

For viewers I think as a baseline we'd need to do the following:

* Disable tap on bottom cards
* Hide the "Collect data" chips
* Hide the "Suggest new LOI" card if present

@vittorino @shobhitagarwal1612 Wdyt?

**Comment by gino-m** [comment]
Note that this is low priority for pilots; we won't need view-only access there.

**Comment by shobhitagarwal1612** [comment]
The crash has been fixed, only UX improvements are left. Closing this one in favor of https://github.com/google/ground-android/issues/1838
