### ISSUE TITLE
[Offline base map] Show error on download failure

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#168]
e.g. file not found

**Comment by shobhitagarwal1612** [comment]
What exactly are we attempting to download, offline areas? Maybe we can close this issue and create one targeting the particular screen or user flow

**Comment by gino-m** [comment]
> What exactly are we attempting to download, offline areas? Maybe we can close this issue and create one targeting the particular screen or user flow

Do you think "Offline tiles" isn't clear? Any suggestion for a more intuitive prefix?

**Comment by shobhitagarwal1612** [comment]
My bad. I somehow managed to completely ignore the prefix completely as if it didn't exist in the first place 😅 

Please ignore

**Comment by gino-m** [comment]
Haha.. I thought it was because of our changing naming scheme. No worries at all!

**Comment by gino-m** [comment]
Hi @scolsen ! Is this still TBD?

**Comment by gino-m** [comment]
Merged in #539.
