### ISSUE TITLE
[Mutations Sync] Warn users and delete pending mutations on sign-out

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#1683]
We currently write *all* pending mutations stored in the local DB as the actively authenticated user in the application. This can lead to scenarios in which a mutation authored by user A is applied under the authentication token of user B, which can break expected access control hierarchies.

For the moment, we'll rectify this by deleting all pending mutations on sign-out, warning the user that this data will be lost.

**Comment by gino-m** [comment]
Ok.. let's just warn/promp them that "unsynced data will be lost" if they sign out.

**Comment by gino-m** [comment]
@amegantz Can you suggest text for a dialog that needs to communicate the following information:

* If you sign out, unsynced submissions/data will be lost and you won't be able to access this survey while offline. Are you sure?!
