### ISSUE TITLE
Once multi-user login is supported, avoid clearing local db data. This is

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1691]
currently being done to prevent one user's data to be submitted as another user after

re\-login\.

https://github.com/google/ground-android/blob/68a2f58c4d8bf8c96acb2cbd4e99d13fc29311b9/app/src/main/java/org/groundplatform/android/repository/UserRepository.kt#L89-L92

```kotlin


  override suspend fun getUser(userId: String): User = localUserStore.getUser(userId)

  override suspend fun clearUserData() {
    clearUserPreferences()
    // TODO: Once multi-user login is supported, avoid clearing local db data. This is
    //  currently being done to prevent one user's data to be submitted as another user after
    //  re-login.
    // Issue URL: https://github.com/google/ground-android/issues/1691
    localDatabase.clearAllTables()
  }

  private fun clearUserPreferences() {
    val deferredDeeplinkConsumed = localValueStore.isDeferredDeeplinkConsumed
    localValueStore.clear()
    if (deferredDeeplinkConsumed) {
      // A deferred deep link is spent once per install, so signing out must not make an already
      // consumed one eligible to be consumed again.
      localValueStore.isDeferredDeeplinkConsumed = true
    }
  }

  override suspend fun canUserSubmitData(): Boolean {
    if (

```

**Comment by gino-m** [comment]
Some states to handle:

## Sign in when not in passlist

* Show modal with eg "Contact survey organizer to obtain access":
  * "Close app" or "Sign out"
  * On "Sign out": Warn that "all unsynced data will be lost, are you sure?"

## Mutation in local db but user not in passlist

* If sync of a mutation fails, stop retrying, update mutation state
* Eventually (not now) we can add notification

**Comment by shobhitagarwal1612** [comment]
I'll start with converting the remaining remote firestore calls to corountine and then will handle the above cases at the implementation place rather than how it is being currently handled.

**Comment by gino-m** [comment]
> I'll start with converting the remaining remote firestore calls to corountine and then will handle the above cases at the implementation place rather than how it is being currently handled.

Should we generally propagate them down to the consumer of the Flow or coroutine rather than in the implementation? My motivation for this is two-fold:

1) if coroutines only handle their own errors some of the time, it's safer to try to catch them in the caller to avoid bugs due to misunderstood or changing function contracts. If we always need to handle them downstream, swallowing them upstream provides little benefit.

 2) Errors which are handled upstream in repositories and data stores are harder to report to the user. A global error toast, for ex, isn't always what we want. When errors are handled by the VMs, the error behavior is more discoverable and linked to specific interactions.

Wdyt?

**Comment by shobhitagarwal1612** [comment]
I agree with the above proposal. In hindsight, it does seem like a better design to handle everything downstream. We have more granular control over how to handle each error that way instead of forcing a single behavior in every context.

> I think an exception to the above may apply to recoverable errors, eg there's an unrecognized or missing field in the datastore, but we still want to load the rest of the object. In that case catching and logging upstream probably makes sense imo

We can audit all our remote calls and come up with a list of fields that we can live without or have a default value for. Until then, we should continue throwing errors to be on the safer side.
