### ISSUE TITLE
[Documentation] Improve language of APACHE License by adding 

### ISSUE THREAD

**Issue by OSURandle** [google/ground-android#1708]
I am a student from OSU and was hoping to contribute to this project. When looking through your documentation I noticed that the language used in the license file could use some clarification relating to the use of third party trademarks/copyrighted materials. This could help new developers (like myself) avoid making mistakes when utilizing these materials to make contributions.

**Comment by gino-m** [comment]
Hi! Thank you for the suggested edits. The license file contains the standard Apache 2.0 license. I'm not a lawyer, so I unfortunately can't verify the validity and implications of the these additions. that said, I appreciate the effort! If there's anything else you'd like to work on in our codebase please comment on an open issue and we can discuss!
