### ISSUE TITLE
Add unit tests for firebase schema converters

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1726]
package name `ground.persistence.remote.firebase.schema`

- [x] AuditInfoConverter
- [x] GeometryConverter
- [ ] JobConverter
- [ ] LoiConverter
- [ ] LoiMutationConverter
- [ ] MultipleChoiceConverter
- [ ] OptionConverter
- [ ] QuerySnapshotConverter
- [ ] SubmissionConverter (needs more coverage for remaining task types)
- [x] SubmissionMutationConverter (#1727)
- [ ] SurveyConverter
- [ ] TaskConverter
- [x] TermsOfServiceConverter
- [x] UserConverter

**Comment by gino-m** [comment]
Duplicate of #2134
