### ISSUE TITLE
Update map type selector UI based on mocks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1753]
![image](https://github.com/google/ground-android/assets/228050/6f528ede-0bee-49ed-8175-dce0435ce5db)

@shobhitagarwal1612 Is this in your wheelhouse?

@vittorino FYI.

**Comment by shobhitagarwal1612** [comment]
Yes, please assign this to me

**Comment by shobhitagarwal1612** [comment]
Last remaining task: adjust the width of the items according to screen size to remove the horizontal scrolling

**Comment by shobhitagarwal1612** [comment]
@gino-m Are we targeting this bug for the upcoming code freeze too? I thought we decided to punt on this to "Field testing" milestone

**Comment by gino-m** [comment]
I created two follow up bugs with the appropriate milestones, should be ok to close this one now.
