### ISSUE TITLE
Map lags on pan and zoom gestures

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1758]
@shobhitagarwal1612 @JSunde Have you seen the same? Any ideas why this might be? I was using our dev test survey.

I suspect this may be related to #1881 and #1882.

**Comment by gino-m** [comment]
Specifically, on drag or pinch the UI freezes for approx 100-200ms before responding normally to pan and zoom gestures.

**Comment by gino-m** [comment]
This appears to be related to https://github.com/googlemaps/android-maps-compose/issues/159. Maps SDK appears to be performing disk reads and writes on `getCameraPosition()`. Disabling StrictMode resolves the issue.

**Comment by masc-it** [comment]
hey I am having pinch to zoom issues on my moto g84 on google maps only and the behaviour is similar to that 100-200ms lag you are talking about..
