### ISSUE TITLE
Disable "download" button and show message when too many/few tiles in selected area

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1761]
The "download" button on the offline area selector map should only be enabled when there are tiles to download, and when the resulting down is below a certain size. Toasts should be shown to indicate each respective state:

* "Selected area to large. Zoom in further to download a smaller area."
* "No imagery available for the selected area."

@amegantz for exact CTA text.

**Comment by amegantz** [comment]
First toast options:
1. "Select a smaller area to download" (preferred)
2. "Zoom in to download a smaller area"

Second toast:
"No imagery to download in the selected area"
