### ISSUE TITLE
Remove global conditional handling of Firebase "Permission Denied" errors?

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1768]
`shouldInterceptException()` is being used to handle "Permission Denied" errors globally, and to ignore other Firestore errors. I understand we did this because we were calling the remote db even when the user might be offline, and  we wanted to ignore the resulting failure states. to  Since I moved survey and LOI sync to a background worker (#1429), I think now we now better differentiate online-only CUJs vs online/offline ones. @shobhitagarwal1612 If that's the case, would it make sense to always let errors propagate to the VM or UseCase and handle them there?

**Comment by gino-m** [comment]
This is likely causing issues to be swallowed, and will be done as part of #723

**Comment by shobhitagarwal1612** [comment]
We have already removed the global error handling. 

https://github.com/google/ground-android/blob/ed6656a24b18e561949ec95d447300790bd0fbab/ground/src/main/java/com/google/android/ground/MainViewModel.kt#L92C1-L93
