### ISSUE TITLE
Track whether LOIs were added as part of survey set up or data collection

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1805]
Requested by SERVIR

**Comment by JSunde** [comment]
@gino-m can you remind me what we landed on the other day?

I think we talked about adding a "source" field, but then we also talked about a potential future flow for the suggested LOIs to be approved, so then I think we were considering storing whether the field was `SUGGESTED` or `CANONICAL`.

Any thoughts on what that field should be named? Bard suggested `location_status`

**Comment by gino-m** [comment]
We chatted. For now let's just add a single boolean field `isOpportunistic`.

**Comment by JSunde** [comment]
From our sync:

Let's also plan to include an `owner` field containing the data collectors email
