### ISSUE TITLE
[Code health] Rename "responses" and "task data" to "submission data"

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1814]
- [ ] Field in `Submission` and related classes: `responses` -> `data`
- [ ] `TaskData`, `Responses` and related classes -> `SubmissionData`

@amysorto @shobhitagarwal1612  FYI

**Comment by JSunde** [comment]
I believe that's correct

**Comment by shobhitagarwal1612** [comment]
Fixed by https://github.com/google/ground-android/pull/2433
