### ISSUE TITLE
[Improve performance] Preserved map feature across config changes

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1830]
Context: https://github.com/google/ground-android/pull/1829

Map is attached to the fragment whenever it is resumed i.e. across config or navigation changes. We create a new renderer for each feature type each time the map is attached. So, in order to get rid of previously added markers, we clear the entire map as the first step. 

We should explore whether it is possible to preserve the renderer objects or somehow get reference to previously added markers. The `clear()` function removes not only markers but other features as well (overlays, polylines, polygons) which is an expensive operation.

**Comment by gino-m** [comment]
`SupportMapFragment` should preserve state across config changes automatically. We're likely creating a new instance on each config change rather than restoring the previous one.

**Comment by gino-m** [comment]
Related to #879?
