### ISSUE TITLE
Viewport not updating when location lock reenabled

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1856]
Viewport is only updated the first time location lock is enabled. Subsequent taps have no effect.

@shobhitagarwal1612 Could you PTAL?

**Comment by JSunde** [comment]
Are you still able to repro this @gino-m? I'm not seeing it on my device

**Comment by gino-m** [comment]
Yes, seeing this on Pixel 7, Android 14, API 34. To repo:

1. Enable location lock
2. Pan map to disable lock
3. Reenable lock

Expected:
Map is panned and zoomed to current location

Actual:
Nothing happens

**Comment by JSunde** [comment]
Weird, I'm also on Pixel 7 and when I follow those steps it does pan and zoom back to my location

**Comment by JSunde** [comment]
Actually, it pans back, but doesn't zoom

**Comment by gino-m** [comment]
> Actually, it pans back, but doesn't zoom

Weird, it didn't for me.. Maybe it only pans back when location changes? I'll walk around now and test.

**Comment by gino-m** [comment]
I couldn't repro in the end so this may have already been fixed.

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce it now.
