### ISSUE TITLE
Wrong map viewport is restored

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1859]
@shobhitagarwal1612 @JSunde  FYI in case you have ideas

**Comment by shobhitagarwal1612** [comment]
What is the expected behavior?

**Comment by shobhitagarwal1612** [comment]
Currently, we only persist the camera position of home screen to preferences.

**Comment by shobhitagarwal1612** [comment]
So, if we pan/zoom on offline fragment or map based tasks, the position won't be persisted to the disk.

**Comment by gino-m** [comment]
> So, if we pan/zoom on offline fragment or map based tasks, the position won't be persisted to the disk.

Presently, the home map viewport should be restored to its original location when returning from the offline areas screen. It currently doesn't do that; it returns to another previously saved location.

**Comment by gino-m** [comment]
This also happens when closing and reopening the app. It appears not all pan/zoom actions cause the last active viewport to be saved.

**Comment by shobhitagarwal1612** [comment]
The issue is happening because of this line

https://github.com/google/ground-android/blob/8700520a8ce0e46f24a15ded4c5a20116bd2eda8/ground/src/main/java/com/google/android/ground/ui/common/AbstractMapContainerFragment.kt#L60

**Comment by gino-m** [comment]
Just observed this after data collection flow; map was zoomed out to initial state instead of position before data collection.
