### ISSUE TITLE
[Offline map imagery] Add a way to cancel offline maps download

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1860]
> Looks like the dialog can be dismissed but the tile download still works in the background. We should either make the dialog non-dismissible along with a cancel button or display download progress in the UI or notification bar. Thoughts?

_Originally posted by @shobhitagarwal1612 in https://github.com/google/ground-android/issues/1846#issuecomment-1712713459_

**Comment by anandwana001** [comment]
Closing this ticket and continuing in https://github.com/google/ground-android/issues/2884
@shobhitagarwal1612
