### ISSUE TITLE
Integrate crash and latency tracker

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#188]

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612! I know you mentioned this was almost working - what was the current issue? Anything I can help with?

**Comment by shobhitagarwal1612** [comment]
Was [fabric](https://get.fabric.io/) ever integrated into ground-android? The error I'm getting could be a possible side-effect of incomplete port from fabric to firebase.

**Comment by gino-m** [comment]
> Was [fabric](https://get.fabric.io/) ever integrated into ground-android? The error I'm getting could be a possible side-effect of incomplete port from fabric to firebase.

We never explicitly set up Fabric in Ground Android, though I suppose it could have been included via transitive deps? What's the error you're seeing? Still getting a blank page in the developer console?

**Comment by shobhitagarwal1612** [comment]
I'll try again with the new Firebase project that you've created.

**Comment by gino-m** [comment]
Sgtm. Sorry for the churn!

**Comment by shobhitagarwal1612** [comment]
> W/CrashlyticsCore: Received null settings, skipping report submission!
W/CrashlyticsCore: Cannot send reports. Settings are unavailable.

Doesn't work with the newly created project too.

**Comment by gino-m** [comment]
Any ideas what the problem could be?

**Comment by gino-m** [comment]
I now can see the dashboard on two of our three dev projects. Please ping when you're around and I can point you a working instance offline (please do not share here).

**Comment by gino-m** [comment]
Let's revisit this once migrate to the new Firebase dev instance.

**Comment by shobhitagarwal1612** [comment]
Sorry, I missed the 6th Jan comment.
