### ISSUE TITLE
[Code health] Use data binding in all views

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#189]
TODO:
- [x] EditRecordFragment
- [x] RecordListAdapter
- [x] FeatureSheetFragment
- [ ] TwoLineHeader

**Comment by gino-m** [comment]
@shobhitagarwal1612 Could you kindly add/update any I missed in the description here?

**Comment by gino-m** [comment]
> @shobhitagarwal1612 Could you kindly add/update any I missed in the description here?

Are these all the ones that are pending?

**Comment by shobhitagarwal1612** [comment]
Sorry for the late reply. 

> @shobhitagarwal1612 Are these all the ones that are pending?

Yes

**Comment by gino-m** [comment]
> Sorry for the late reply.
> 
> > @shobhitagarwal1612 Are these all the ones that are pending?
> 
> Yes

Thanks for verifying!
