### ISSUE TITLE
Issues rendering polygon LOIs 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1896]
- [x] Job color isn't applied (this could be an issue with test data) - `PolygonRenderer` needs to apply style in `Feature`
- [ ] All polygon LOIs disappear after one is selected

See also #1895

@JSunde @shobhitagarwal1612 FYI in case you have ideas / time 

[Screen_recording_20230915_125357.webm](https://github.com/google/ground-android/assets/228050/fc26b9b8-732f-42fc-abed-7bf3d2d90606)

**Comment by JSunde** [comment]
I don't seem to be able to reproduce the issue where the polygons disappear after zooming in. Can you still repro that @gino-m?

**Comment by gino-m** [comment]
I cannot, ok to close this one!
