### ISSUE TITLE
Improve "Surveys are automatically synced" text

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1915]
Shown in the survey list, this makes it appear that surveys listed are automatically sync, when rather only surveys which have been opened are automatically synced.

![Screenshot_20230919_173021](https://github.com/google/ground-android/assets/228050/fd421523-5807-4d02-9008-1a2f02a193de)

A better prompt might be "Select a survey. Once opened, surveys are automatically synced for offline use."

@amegantz For final content.

**Comment by amegantz** [comment]
What does "open" mean here? Does the user have to actually start collecting data, or do they just have to select a survey without necessarily having to do any other actions?

**Comment by gino-m** [comment]
> What does "open" mean here? Does the user have to actually start collecting data, or do they just have to select a survey without necessarily having to do any other actions?

They just have to tap the survey in the list displayed here, which opens the survey. The app makes the survey available offline and starts syncing it in the background.

**Comment by amegantz** [comment]
Got it, thanks. How about:
**Title**: Select a survey
**Body**: Once a survey is opened, it will automatically be synced for offline use.
