### ISSUE TITLE
Suggest LOI "Drop a pin" flow triggered on normal LOI data collection

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1920]
Cliciking "Collect data" on an LOI job card prompts the user to drop a pin. That flow should only be triggered on jobs with `suggestLoiTaskType` set, and only on "suggest" cards.

@shobhitagarwal1612 @JSunde FYI

**Comment by JSunde** [comment]
I thought drop a pin was a regular data collection task as well as a `suggestLoiTaskType`, is that not data that we think survey organizers might want to collect for a given job?

**Comment by gino-m** [comment]
> I thought drop a pin was a regular data collection task as well as a `suggestLoiTaskType`, is that not data that we think survey organizers might want to collect for a given job?

It may also be a regular data collection task, but in this case there was no "drop a pin" task in the job.

**Comment by gino-m** [comment]
@JSunde Actually, this appears to be a problem with the web UI, task `type` is now being written as an integer instead of a string..

**Comment by JSunde** [comment]
Ahh gotcha, I misunderstood the original report.
