### ISSUE TITLE
Survey list doesn't scroll vertically

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1924]
[scrollbug.webm](https://github.com/google/ground-android/assets/228050/2b2cc65a-d249-4898-9785-de1824a7fddd)

@shobhitagarwal1612 is this in your wheelhouse? Please assign back to me if you're oversubscribed!

**Comment by shobhitagarwal1612** [comment]
I'm unable to reproduce this bug. 


https://github.com/google/ground-android/assets/8918023/178afefb-8546-4840-b210-4acd55a04361

**Comment by gino-m** [comment]
In your video, note that the last card is slightly offscreen cannot be scrolled to. In some cases, the last card is completely off the screen. See attached video and layout:


https://github.com/google/ground-android/assets/228050/a62665d9-1bce-40d0-914c-7acafc1807cc

<img width="953" alt="image" src="https://github.com/google/ground-android/assets/228050/dc93c8f2-a751-4789-ac2f-2f728daefdb5">
