### ISSUE TITLE
[Code health] Set up basic unit testing

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#193]
- [ ] Configure unit test framework
- [ ] Set up initial test as example of basic business logic (e.g., `*Manager`)
- [ ] Document basic setup

**Comment by gino-m** [comment]
Hi @deepakbansal! `SettingsManager` seems fairly self contained; all dependencies are injected and can be easily mocked. Care to start with that one, or did you have another class in mind?

**Comment by deepakbansal** [comment]
I was looking through some classes but I think I'll start with this one. Sorry, I was busy with a summit in RWC for past couple of days, couldn't make any contributions here.
I'll try to work add some tests by this weekend.

**Comment by gino-m** [comment]
> I was looking through some classes but I think I'll start with this one. Sorry, I was busy with a summit in RWC for past couple of days, couldn't make any contributions here.
> I'll try to work add some tests by this weekend.

Sgtm. Please let me know if you have any questions!
