### ISSUE TITLE
[Data collection tasks] Support conditional tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1955]
The user can add one of two conditions:

- [ ] Based on previous multiple choice answer (e.g., show/hide follow up questions if user selected "Forest" for first question)
- [ ] ~Only show when adding a new LOI~

See also https://github.com/google/ground-platform/issues/1201

**Comment by jcqli** [comment]
https://github.com/google/ground-platform/issues/1478 is tracking the web side, using this bug to track the android work

**Comment by sufyanAbbasi** [comment]
Proposed a schema in google/ground-platform/issues/1478 but raised a bunch of implementation questions. I can start working on the logic loosely based on this idea to get started, since the core logic will probably be static.

**Comment by sufyanAbbasi** [comment]
Working off of @gino-m schema proposal:
```
task: {
  ...
  "id": string
  "condition": {
    "matchType": "MATCH_ALL",
    "expressions": [
         {
            "expressionType": "ONE_OF_SELECTED",
            "taskId": "GqEBDoAoEnPbMmRbje5c",
            "optionIds": ["Po2zyacw6FVFE6gaL8km", "rVbIQmFIajZvnlSIl7n3"]
         }
      ]
    },
    ...
```

**Comment by gino-m** [comment]
Updated description with reduced scope

**Comment by sufyanAbbasi** [comment]
There is is some ambiguity to resolve about how to deal with the "Next/Done" button when the last task in the list is conditionally hidden and the current "last task" contains the condition that would enable it. It implies that we need to check that we're in this state and refresh the "Next" button on every input.

Similarly, if we violate one of the assumptions that conditions are strictly dependent on previous tasks, future task selections can actually modify the previous task lists, which is the easiest way to implement it!

**Comment by gino-m** [comment]
From the user's perspective, we wouldn't want to ask them to complete tasks which an be made irrelevant by subsequent questions, but that's something that would need to be enforced when the survey organizer is defining the survey. If it's easier to for the data collection flow to treat the conditions as if they can be out of order, then please go ahead!

**Comment by sufyanAbbasi** [comment]
Here's another edge case to consider: the user inputs a value to a conditional task, then goes back to undo a selection to hide a conditional task, but the current behavior will commit the final result to the database because we're saving the task values in `data`. Should we filter out hidden conditional tasks in the final output?

**Comment by gino-m** [comment]
> Here's another edge case to consider: the user inputs a value to a conditional task, then goes back to undo a selection to hide a conditional task, but the current behavior will commit the final result to the database because we're saving the task values in `data`. Should we filter out hidden conditional tasks in the final output?

Good catch! Yes, only "valid" data should be captured. Thanks for catching this.
