### ISSUE TITLE
Network preference for downloading offline tiles doesn't do anything

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1964]
We have a preference in settings page which is currently not used anywhere. We should consider cleaning it up or actually using it

**Comment by gino-m** [comment]
@shobhitagarwal1612 It appears the entire settings page is unused. If there aren't any settings we need we can delete it. We can always revive it if necessary.

**Comment by shobhitagarwal1612** [comment]
The other preference is actually being used when uploading images to remote storage

**Comment by gino-m** [comment]
Let's remove this toggle?
