### ISSUE TITLE
 Survey list doesn't update on remote changes (not reactive)

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1973]
@shobhitagarwal1612 FYI

Proposed logic: stream of `List<Survey>` would be derived from (pseudocode):
`onlineStatus.flatMapLatest { if (online) remoteSurveysFlow else localSurveysFlow }`

**Comment by shobhitagarwal1612** [comment]
I was able to create a working prototype which updates the list on remote changes. However, I'm facing an issue when trying to stop listening to remote changes.

**Comment by gino-m** [comment]
> I was able to create a working prototype which updates the list on remote changes. However, I'm facing an issue when trying to stop listening to remote changes.

Can you share as a draft PR?

**Comment by shobhitagarwal1612** [comment]
https://github.com/google/ground-android/pull/2027

**Comment by gino-m** [comment]
This is a bit different than what I had in mind I'll send a PR to clarify.
