### ISSUE TITLE
Hamburger menu missing on survey selector

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1988]
Once added, the "sign out" button shown when there are no available surveys can be removed.

![image](https://github.com/google/ground-android/assets/228050/0ca6cd3d-b526-4b2b-b99f-3b7368383c6f)

**Comment by shobhitagarwal1612** [comment]
When I press the back button, the app closes. Can you please confirm if that's the correct behavior or not?

**Comment by gino-m** [comment]
> When I press the back button, the app closes. Can you please confirm if that's the correct behavior or not?

In that case, there's no way for the user sign out? Perhaps we should just add the hamburger menu instead of back button as shown here? Ok to do this after other bug fixes.

![image](https://github.com/google/ground-android/assets/228050/9ca2fd71-60df-4ebb-ad89-e9004475a52c)

**Comment by gino-m** [comment]
@shobhitagarwal1612 Actually, I forgot we have the "sign out" button on the list now. That works as a workaround for now. I'll update this issue's desc to add the menu to the survey list.

**Comment by gino-m** [comment]
@vittorino and I spoke, he will update the designs so that the hamburger icon isn't needed here.
