### ISSUE TITLE
Job cards appear slightly off bottom of screen

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1990]
Seen on Pixel 7

**Comment by shobhitagarwal1612** [comment]
Unable to repro on pixel 7 (emulator)

![Screenshot_20231103_081123](https://github.com/google/ground-android/assets/8918023/cb2aa300-a528-4141-8f9d-4afd0e5a72fb)

**Comment by gino-m** [comment]
This still occurs on physical Pixel 7:
![Screenshot_20231109-151247.png](https://github.com/google/ground-android/assets/228050/45610dbb-b1ad-4a81-a6c6-9ab84c401ac0)

**Comment by gino-m** [comment]
@shobhitagarwal1612 And also on the emulator image you pasted above you can see the cards are clipped by a few pixels:

<img width="124" alt="image" src="https://github.com/google/ground-android/assets/228050/710b90c8-28ce-4ec3-915a-d04ac5ba7108">
