### ISSUE TITLE
Opening sync status screen with pending mutations crashes app

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1995]

**Comment by shobhitagarwal1612** [comment]
Unable to reproduce this bug. Could you please mention the steps?

**Comment by shobhitagarwal1612** [comment]
I'm still unable to reproduce the issue. 

[sync_screen.webm](https://github.com/google/ground-android/assets/8918023/d8b32d07-6624-4dda-b2f8-bcad73c5f296)
