### ISSUE TITLE
[Code Health] Implement RxLint checks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#203]
https://www.littlerobots.nl/blog/RxLint-a-lint-rule-for-RxJava/
https://medium.com/@peter.tackage/overriding-rxjava-schedulers-getting-it-right-with-rxlint-60cde12b3b00

**Comment by gino-m** [comment]
@shobhitagarwal1612 Do you think this is worth investigating?

**Comment by shobhitagarwal1612** [comment]
With kotlin migration, we should invest into moving away from Rx and replacing it with coroutines. So, this would become obsolete eventually

**Comment by gino-m** [comment]
That makes sense. Let's discuss, I'll close this for now.
