### ISSUE TITLE
Changes to remote LOIs not reflected in job cards

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2040]
@shobhitagarwal1612 PTAL?

@rachaprince FYI.

**Comment by scolsen** [comment]
Do we have more details here? I can't reproduce this, generally speaking. For example, if I add a custom name to an LOI the corresponding card is updated instantly.

**Comment by gino-m** [comment]
Perhaps this was already fixed by @shobhitagarwal1612 ? 

Please see also #1934.
