### ISSUE TITLE
[Persistence] Crash on UNIQUE constraint failure

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#2044]
After starting up the app post-hiatus I encountered the following crash:

```
java.lang.Throwable: UNIQUE constraint failed: offline_base_map_source.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
```

That's reasonable enough, but we probably shouldn't crash on this, esp. for offline basemaps, and instead handle the error gracefully. Filing this bug to track that.

**Comment by scolsen** [comment]
Looks like this is just a bug. We set a default ID of `0` on the `TileSourceEntity` but there are...[complications](https://stackoverflow.com/questions/70899422/room-unique-constraint-failed-for-primary-key-despite-autogenerate-true) when using this feature in Room. I'll figure out the right combination and send a fix.

**Comment by scolsen** [comment]
We need to use a default value of `null` to force the autogeneration. Room treats a `0` value as an explicit, intentional value for boxed types (which makes sense).

**Comment by gino-m** [comment]
> We need to use a default value of `null` to force the autogeneration. Room treats a `0` value as an explicit, intentional value for boxed types (which makes sense).

Nice sleuthing, thanks for the fix!
