### ISSUE TITLE
Drop a pin task not showing on Android

### ISSUE THREAD

**Issue by vittorino** [google/ground-android#2083]
**Describe the bug**
When a new job is created with drop a pin as a task, the task does not show up on Android.

**To Reproduce**
1. Create new Job
2. Add 'Answer question' and 'Drop a pin' tasks
3. Publish survey
4. On Android, collect data for this Job

**Expected behavior**
The 'drop a pin' task would be next in queue before job is completed.

**Actual behavior**
The job gets marked as completed before the task appears.

**Screenshots**
N/A

**Comment by gino-m** [comment]
"`drop_pin` not a supported type" on Android log. Likely out of sync w/web
