### ISSUE TITLE
[Data sync] Improve sync status UX

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2084]
Ideas:

- [ ] Auto-retry only on failures due to connectivity
- [ ] All other issues should be discoverable via the sync status UI
- [ ] Allow users to manually retry failed jobs

**Comment by amysorto** [comment]
My sync failed, this is the log for it: https://paste.googleplex.com/5870358003974144

**Comment by gino-m** [comment]
@scolsen has already made improvements to the sync status screen and this FR is too general to be useful. Closing.
