### ISSUE TITLE
Capture Location Info Helper Tells Users to Drag the Map

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#2088]
**Describe the bug**
During the capture location task the info button tells the user to drag the map, which is impossible for this task.

<img width="380" alt="Screenshot 2023-11-30 at 10 56 30 AM" src="https://github.com/google/ground-android/assets/11237600/d8acac9c-5f3a-4585-b5d1-3ae6656e1467">

**Comment by gino-m** [comment]
@amegantz What should the tooltip say for this flow? The map cannot be panned by design.

**Comment by shobhitagarwal1612** [comment]
> Do we still need the tooltip then? The top instructions seem explanatory enough (though I would change "at which you collected this data" to just "where you collected this data" for simplicity).

This message is defined by the survey owner.
