### ISSUE TITLE
Show user-defined task instructions prominently on all tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2089]
We do this for some task types:
![image](https://github.com/google/ground-android/assets/228050/d2e0dd38-8ebb-4008-a61e-8421a73c1db2)

But not others:
(TBD)

@scolsen Which ones?

**Comment by gino-m** [comment]
> Looks like we currently only have this in map tasks (capture, pin, polygon). Should we add it to all task types? I guess it's not clear what we'd present in non-map tasks once we render descriptions in task headers.

Just to be clear, I'm talking about the "question" or "instructions" defined by the survey organizer. I remembered not seeing it on some screens, but I may have misremembered, Need to check.

**Comment by scolsen** [comment]
> > Looks like we currently only have this in map tasks (capture, pin, polygon). Should we add it to all task types? I guess it's not clear what we'd present in non-map tasks once we render descriptions in task headers.
> 
> Just to be clear, I'm talking about the "question" or "instructions" defined by the survey organizer. I remembered not seeing it on some screens, but I may have misremembered, Need to check.

It's definitely not on the test task screen, and most others — I can take a look.

**Comment by gino-m** [comment]
> It's definitely not on the test task screen, and most others — I can take a look.

Thanks!

**Comment by gino-m** [comment]
Confirmed this is already WAI.
