### ISSUE TITLE
"Add point" button in "Draw polygon" task appears incorrectly

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2102]
When the task index is > 0, an additional button "previous" is added to the task for navigating to the previous task. This results in "Add point" button to look incorrectly due to insufficient space. 

![bug-app-point](https://github.com/google/ground-android/assets/8918023/5df9feed-12eb-4ea7-bfed-687de1f7def8)

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612! Do you have bandwidth for this one?

**Comment by shobhitagarwal1612** [comment]
Couple of other approaches considered:

1. Replace text buttons with icon based buttons
2. Dynamically reduce the size of the existing buttons as we add new buttons
3. Add more buttons vertically if we're out of horizontal space.

**Comment by gino-m** [comment]
We spoke. The "Skip" and revert icon are mutually exclusive, with the former being shown when there are zero vertices specified, the latter when N>=1. That should provide enough space for all buttons, in English at least.

![image](https://github.com/google/ground-android/assets/228050/f850f9eb-0f36-497a-b0c5-cce9d55d46d6)

![image](https://github.com/google/ground-android/assets/228050/80534513-eb00-4687-aa7e-63cef1649874)
