### ISSUE TITLE
Survey list jitters after tap

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2109]
This occurs when scrolling down and selecting a survey at the bottom of the list.

Ideally, rather than refreshing the list, we would show a modal spinner or separate loading screen while the survey is loading.

@shobhitagarwal1612 PTAL?

[Screen_recording_20231212_191324.webm](https://github.com/google/ground-android/assets/228050/fc11b619-8fc7-4df5-90f6-cfe2c94a61a5)

**Comment by scolsen** [comment]
I have a fix for this

**Comment by gino-m** [comment]
> I have a fix for this

@shobhitagarwal1612 FYI
