### ISSUE TITLE
[Code Health] Check for private keys at build time

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#211]
Is there an easy way to verify private keys have been set in the Gradle build? @scolsen and I both got `java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalArgumentException: Given String is empty or null` when pulling latest. The readme provides instructions, but it might be helpful to fail fast with a more obvious message. Thanks!

**Comment by shobhitagarwal1612** [comment]
It happens because of the empty `google-services.json` kept for cloud builds. I'm not sure how to customize the error message since it gets initialized by itself with the start of the application.
