### ISSUE TITLE
[Draw an area] Improve vertex selector UX treatment

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2110]
Three main issues with the current marker:

- It isn't visible on light imagery or maps
- It obscured the view of the underlying imagery
- It looks like a crosshairs, which has negative connotations

![image](https://github.com/google/ground-android/assets/228050/dfc2000a-c4a6-43c8-8a23-30d04aea044a)

**Comment by rawbzz** [comment]
testing

**Comment by rawbzz** [comment]
Designs [here ](https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?type=design&node-id=5076%3A15453&mode=design&t=1BrOFjFheJMmzsbU-1)

**Comment by gino-m** [comment]
Thanks @rawbzz ! Pasting design here.

![image](https://github.com/google/ground-android/assets/228050/570de812-8462-4ec4-9104-2d1224186f99)
