### ISSUE TITLE
Inconsistent hint text on offline map imagery list

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2118]
When no imagery downloaded, text says to tap "Select and download", but the fab label is "Select area".

**Comment by shobhitagarwal1612** [comment]
@gino-m What should be FAB label when there are no offline imagery?

**Comment by gino-m** [comment]
> @gino-m What should be FAB label when there are no offline imagery?

Can you paste screenshots for input from @amegantz ?

**Comment by shobhitagarwal1612** [comment]
![Screenshot_20240720_210721](https://github.com/user-attachments/assets/487048a3-9a89-4ab3-a955-2c1c6a5a61ea)

**Comment by gino-m** [comment]
@shobhitagarwal1612 Thanks! The designs have something a little different, but I suspect the text there should say "No map imagery downloaded for offline use":

![image](https://github.com/user-attachments/assets/047fa0fa-98b6-4899-b42c-582250cd2821)

@amegantz Can you confirm?

**Comment by amegantz** [comment]
![image](https://github.com/user-attachments/assets/1a12b812-d732-4ca4-b834-1e23dc77e070)
Works for me!
