### ISSUE TITLE
[Dev Setup] Gradle distribution changed by Android Studio

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#212]
Android Studio is trying to update `gradle-wrapper.properties` from:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-bin.zip
```

to:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

I assume this isn't an issue and can safely be checked in, but wanted to verify if you think it will have any adverse effects on Cloud Build. Thanks!

**Comment by shobhitagarwal1612** [comment]
It was an unintentional change. The `*-all.zip` contains the binary and the documentation. I haven't checked the size difference between the two zips but I'm assuming it's not significant enough to make a big difference.

**Comment by gino-m** [comment]
Ok, I'll submit with `-all` in the next PR. Thanks!
