### ISSUE TITLE
[Auth] UX issues with sign in flow on unstable connection

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2131]
When on an unstable connection in the subway/metro

- [x] #2161
- [ ] Sign in button appears and disappears depending on connection status as we had planned, but in retrospect this creates a UX race condition between the button click and network status. Instead when there's no connection, we should allow the click, but show a message saying "No connection. Connect to the internet to sign in." below the button (@amegantz to confirm/update).
- [ ] Sign in button can be tapped multiple times, which sometimes crashes the app. Instead we should ignore subsequent taps.
- [x] #2160

**Comment by amegantz** [comment]
No connection message: "Connect to the internet to sign in"

**Comment by scolsen** [comment]
+1, when I have no connection and start the app fresh all I see is this:



![Image](https://github.com/google/ground-android/assets/11237600/81b9058c-af7e-4004-9e7c-a2eb7b142601)

**Comment by shobhitagarwal1612** [comment]
>  Sign in button can be tapped multiple times, which sometimes crashes the app. Instead we should ignore subsequent taps.

I'm unable to repro this.

**Comment by gino-m** [comment]
> I'm unable to repro this.

Thanks for trying. We shouldn't try to sign in multiple times anyway - can we disable the button as soon as it's tapped once, and reenable if sign-in failed?
