### ISSUE TITLE
[Map] Show snackbar when first opening survey

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2132]
Show when cards are not visible:

- [ ] If any jobs have `strategy!=PREDEFINED`: "Zoom in to start collecting data", else:
- [ ] If all jobs have 0 LOIs : "Survey is read-only", else:
- [ ] "Zoom in to a data collection site to collect data"

@amegantz For exact copy.

Example UI:

![image](https://github.com/google/ground-android/assets/228050/f1ebc9bf-5fdf-45ab-9900-f8a0795ec855)

**Comment by amegantz** [comment]
If any jobs have `strategy!=PREDEFINED`: "Zoom in to start collecting data", else:
 If all jobs have 0 LOIs : "No data collection sites defined", else:
 "Zoom in to a site to start collecting data"

**Comment by gino-m** [comment]
> "No data collection sites defined",

Thanks! Might "No data collection sites defined" cause the user to think they can define them themselves? In this case, `strategy==PREDEFINED`, so that wouldn't be possible.

**Comment by amegantz** [comment]
Hmm, good point. Maybe "No data collection sites provided" instead? Trying to avoid "available" since as long as Earth exists, data collection sites are available haha

**Comment by gino-m** [comment]
> Hmm, good point. Maybe "No data collection sites provided" instead? Trying to avoid "available" since as long as Earth exists, data collection sites are available haha

😆 Maybe we should just say something like "Survey is read-only" so they don't try to figure out how to "provide" sites?

**Comment by amegantz** [comment]
Could they still perform other tasks even if 0 LOIs were defined?

**Comment by amegantz** [comment]
I'm ok with "Survey is read-only" here then. Might be worth exploring iconography for read-only states down the line

**Comment by scolsen** [comment]
@gino-m just for clarification, we want to show this on every survey switch, right? Not just on the first survey the user ever opens in the app

**Comment by gino-m** [comment]
Yes, I think that makes sense. Perhaps even better might be session scope; it will show again when zooming out of the app is restarted. This may also be easier to implement?

**Comment by jcqli** [comment]
@scolsen Is this clsoed as per https://github.com/google/ground-android/pull/2274?

**Comment by jcqli** [comment]
@shobhitagarwal1612 are you looking into this?

**Comment by shobhitagarwal1612** [comment]
> @shobhitagarwal1612 are you looking into this?

No. I haven't started looking into this
