### ISSUE TITLE
["Draw area" task] Simplify impl - Polygon and LinearRing not needed while drawing

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2143]
https://github.com/google/ground-android/blob/260e797d7010dddc7e834aac5822d41807d0b4e1/ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/polygon/PolygonDrawingViewModel.kt#L177-L186

While drawing, all possible states can be represented as a `LineString`, so we shouldn't need this additional logic.

@shobhitagarwal1612 Can you please confirm?

**Comment by shobhitagarwal1612** [comment]
This is because each of the above geometry is rendered differently.

**Comment by gino-m** [comment]
> This is because each of the above geometry is rendered differently.

Do the closed and marked complete renderings of the polygon not look correct with a plain old `LineString`?

**Comment by shobhitagarwal1612** [comment]
Visually, both of them look same. Implementation wise, they are handled differently. So, `LineString` should help simplify things.

**Comment by gino-m** [comment]
> Visually, both of them look same. Implementation wise, they are handled differently. So, `LineString` should help simplify things.

So am I understanding correctly that we don't need `Polygon` or `LinearRing` to render the draft polygon/area? If not I'll remove the usage here to simplify.
