### ISSUE TITLE
[Map] Clicking a marker (point LOI) does not select the LOI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2166]
Verified occurring at HEAD; this issue predates refactor #2157.

https://github.com/google/ground-android/assets/228050/71fc0a1b-9eb0-40bf-9ded-de817dfeb3ef

**Comment by shobhitagarwal1612** [comment]
I tried using the below code for adding click events for map markers, but it is not working. [Documentation](https://developers.google.com/maps/documentation/android-sdk/marker#marker_click_events)

```
map.setOnMarkerClickListener {
      Timber.d("Marker clicked" + it.toString())
      true
    }
```

**Comment by gino-m** [comment]
> I tried using the below code for adding click events for map markers, but it is not working. [Documentation](https://developers.google.com/maps/documentation/android-sdk/marker#marker_click_events)
> 
> ```
> map.setOnMarkerClickListener {
>       Timber.d("Marker clicked" + it.toString())
>       true
>     }
> ```

Did you add it to the markers being added by `PointRenderer`? If you add it to the ones created by `FeatureClusterRenderer` it won't work since those are not displayed.

**Comment by shobhitagarwal1612** [comment]
This listener is added to `GoogleMap` object and not the individual markers.

**Comment by gino-m** [comment]
> This listener is added to `GoogleMap` object and not the individual markers.

When I try this I get the following warning:

> Using this method may override behaviors set by the Maps SDK for Android Utility Library. If you are not using clustering, GeoJson, or KML, you can safely suppress this warning, otherwise, refer to the utility library's migration guide: https://bit.ly/3kTpQmY

Digging deeper, it appears `ClusterManager` is using a class called `MarkerManager` which overrides the default listeners.

To fix this, we should extend `MarkerManager`, overriding `onMarkerClick()`. The overridde impl should be passed through an update constructor of `FeatureClusterManager`, for ex, in `FeatureManager`:

```kt
fun onMapReady(map: GoogleMap) {
  ...
  clusterManager = FeatureClusterManager(context, map, MarkerManager(map) { 
    override fun onMarkerClick(m: Marker) = super.onMarkerClick(m) ||  this@FeatureManager.onMarkerClick(m)
  })
  ...
}
```

**Comment by shobhitagarwal1612** [comment]
Thanks Gino!
