### ISSUE TITLE
[Code health] Fix lint warnings

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#217]
1. Run lint check locally:

   1. Via Command-line:
     `./gradlew lintDebug`
    
   1. Via Android Studio
      - Expand `gradle` side-tab (top-right corner of Android Studio).
      - Click on `Execute gradle task` button (one with the gradle logo)
      - Type `lintDebug` and press OK

1. See the report:
 `gnd/build/reports/lint/lint-result.html`

1. Choose a lint warning and add it to `lint.xml` with severity as `error`

1. Fix the lint errors and check again (**Step 1**)

1. Submit PR

**Comment by gino-m** [comment]
Thanks for the instructions! One question - are the same linter and code analyzer used when running Analyze > Inspect code in Android Studio? Its interactive output in "Inspection Results" is very helpful.

**Comment by shobhitagarwal1612** [comment]
Yes. It's the same one. `lint.xml` just gives us the power of customisation.

**Comment by gino-m** [comment]
But can we let Android Studio use the custom `lint.xml`?  Same for PMD and checkstyle?

**Comment by shobhitagarwal1612** [comment]
I suppose we can add the IDE settings to the repository for sharing same configuration. Not sure about the details though

**Comment by gino-m** [comment]
Ok, let's close #219 for now and we can revisit IDE integration later.
