### ISSUE TITLE
[Code health] Move `flag` from `Feature.Tag` to `Feature`

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2171]
Only items which uniquely identify the Feature should live in Tag. @scolsen Any idea why this was added?

**Comment by scolsen** [comment]
We used it to calculate counts for the number of LOIs/features with some amount of data collected -- I think I named it such just to keep it maximally general. 

Basically, if this field is `true` we know the feature has *some* data collected on it, and we should count it in the cluster "has data or not" (e.g. 4/5) count.

https://github.com/google/ground-android/pull/1441 for context.
