### ISSUE TITLE
Update warning message for sign out dialog 

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2225]
**Unsaved data**
If you sign out, your unsaved data will be discarded.
[Cancel] [Sign out]

_Originally posted by @amegantz in https://github.com/google/ground-android/issues/2209#issuecomment-1928607989_

**Comment by gino-m** [comment]
@amegantz unsaved != unsynced - can we update to clarify?

**Comment by amegantz** [comment]
Apologies, misunderstood your point about unsaved/unsynced.

**Unsaved data**
If you sign out, any unsynced data will be discarded.
[Cancel] [Sign out]
