### ISSUE TITLE
[Release] API Level must be at least 33

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-android#2227]
https://developer.android.com/google/play/requirements/target-sdk?hl=en

**Comment by gino-m** [comment]
@rfontanarosa  Can you submit the change when you get a chance?

**Comment by gino-m** [comment]
@shobhitagarwal1612 to look at why build is failing on GCB.

**Comment by shobhitagarwal1612** [comment]
The root cause seems to be related to interaction with DrawerLayout in robolectric tests. Looking deeper now.
