### ISSUE TITLE
Deploy to Play Store

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2244]
Build, sign, deploy Open Foris Ground to Firebase + Play Store in advance of the March 21st announcement date

**Comment by gino-m** [comment]
@rfontanarosa Has done a first pass, but will need to cut a new release before the announcement. @jcqli  He will probably also need to do one before the field testing.

**Comment by jcqli** [comment]
@gino-m https://github.com/google/ground-android/issues/2245 for doing that prior to March 5.

**Comment by gino-m** [comment]
Let's reset db version to 0 as well. Follow-up on #932 on next release.

**Comment by jcqli** [comment]
Closing since this was done for the IDF date.
