### ISSUE TITLE
[Add LOI task] Add ability to name new LOIs when adding

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2250]

**Comment by rawbzz** [comment]
<img width="379" alt="Screenshot 2024-02-21 at 2 13 41 PM" src="https://github.com/google/ground-android/assets/108412767/1b574201-5c0f-4147-8431-442890881ce1">

**Comment by shobhitagarwal1612** [comment]
This was recently added by @sufyanAbbasi
