### ISSUE TITLE
[Bug] Time task doesn't load on app

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2257]
If a survey contains multiple tasks, then only time task isn't loaded in the data collection screen.

**Comment by gino-m** [comment]
> If a survey contains multiple tasks

Surveys contain jobs, and jobs contain tasks. Which did you mean here?

> only time task isn't loaded in the data collection screen.

Do you mean time tasks aren't shown, or that loading them throws an error?
