### ISSUE TITLE
[Add LOI tasks] Inconsistent behavior of Add LOI tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2275]
~The `addLoiTask` boolean has been deprecated. Instead we should:~

~- [ ] Stop assuming these special "add LOI" tasks appear as the field task~
~- [ ] Identify add LOI tasks by their ID (`$addLoi`)~
~- [ ] Remove the boolean flag `addLoiTask` on `Task`~

@sufyanAbbasi PTAL?

**Comment by sufyanAbbasi** [comment]
It seems like, for some reason, while the $addLoi task appears in the task list from Firestore, when we're retrieving the taks lists from the JobEntity in the local DB, that task is no where to be found. Investigating further.

**Comment by sufyanAbbasi** [comment]
After debugging some more, by changing the `$addLoi` ID to something like `$addLoi123` then setting the target LOUID task ID to `$addLoi123`, the feature began to work again as expected. With breakpoints, I can see that as we iterate over the surveys and store them into the DAO, when the same LOI task ID key is encountered, we store it there.

Given that the `taskDao` uses the `taskId` as the primary key, it gets overridden by the other tasks when loaded into the DAO. Inspecting the DB revealed the issue:

<img width="1327" alt="Screenshot 2024-02-28 at 6 34 18 PM" src="https://github.com/google/ground-android/assets/12646706/12b92ebe-5f36-4e85-89ab-6f3c273332a8">

Proposed fixes:
- Change it from `$addLoi` to `$addLoi<JOB ID>` and we can use a simple `startsWith()` check. 
- Do this transformation on the local DB side and remember to unparse it later at fetch time.
- Reconfigure the DB to use both a Primary and Secondary key, the task and job ID, something something?

**Comment by gino-m** [comment]
Great sleuthing, Sufy! What if we just go back to using the "addLoiTask" boolean? That way clients would be able to count on task IDs being UUIDs. @rfontanarosa does this complicate things much?

**Comment by sufyanAbbasi** [comment]
I wanted to report that option 3, having two primary keys, is a completely viable option: I modified the task table, multiple choice table, and option table to use the task ID and job ID as primary keys. I have no crashes and as long as task IDs are unique within a job, the solution actually works REALLY well. Furthermore, consider the scenario in which a sufficiently lazy survey creator wanted to just copy and paste a survey schema. With this solution, they could theoretically JUST change the job ID and the two surveys could coexist on the device. In the status quo scenario, doing the operation that I just described would be unsafe. 

The cost is a table schema update and more complicated key structures which would get in the way of migration.

**Comment by gino-m** [comment]
Update: We reevaluated this issue, and agreed instead on the solution outlined in https://github.com/google/ground-platform/issues/1530. For now, no changes are needed Android-side. We'll eventually deprecate `addLoiTask` boolean, but not in this version, so closing this for now.
