### ISSUE TITLE
Data collection hint snackbar obscures location lock button

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2285]
There should be a way to dismiss the snackbar, and the location lock should be repositioned so that it isn't obscured.

Expected:

![image](https://github.com/google/ground-android/assets/228050/851769e9-57a9-485a-9df9-964b5960399d)

Actual:

![Screenshot_20240301_154235](https://github.com/google/ground-android/assets/228050/223634f5-a9fc-4083-8be9-e6b1b0475b17)

**Comment by gino-m** [comment]
@scolsen PTAL?

**Comment by jcqli** [comment]
@scolsen Could you take a look at this?

**Comment by jcqli** [comment]
Closing since https://github.com/google/ground-android/pull/2304 is merged
