### ISSUE TITLE
Data collection snackbar hint doesn't go away when zooming in

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2286]
@sufyanAbbasi's repro steps:
1. Zoom in enough to be able to start collecting points.
1. Switch to a different menu item (e.g. sync menu).
1. Switch back to map view, see that the "Zoom in" message is triggered.

![Screenshot 2024-03-12 at 6 53 01 PM](https://github.com/google/ground-android/assets/12646706/f8916ff7-2640-4ad1-afda-f5e7ed723694)
![Screenshot_20240301_154314](https://github.com/google/ground-android/assets/228050/d36a7f23-fd72-4b7f-a1e6-6c9c35d24210)

**Comment by gino-m** [comment]
@scolsen PTAL?

**Comment by sufyanAbbasi** [comment]
I'll take a stab at this one, but @scolsen, feel free to snipe it if you can get it done faster.
