### ISSUE TITLE
[Data collection flow] Header doesn't show full label of LOI, only ID

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2291]
For example, an LOI with only ID 5 shows as "5" rather than "Point 5" as on the card.

@shobhitagarwal1612 PTAL?

**Comment by shobhitagarwal1612** [comment]
If LOI contains only "id", then the display name is "<Geometry type> (id)" e.g. Point (5)

If LOI contains only "name", then the display name is "name" e.g. "Loi Name"

My guess is that 5 is the name of the LOI and not ID. Can you please share more details? (survey id, loi id, etc.)

**Comment by shobhitagarwal1612** [comment]
@gino-m FYI

**Comment by gino-m** [comment]
@shobhitagarwal1612 The data collection flow header doesn't actually use that logic. You can see the incomplete impl and related TODO here:

https://github.com/google/ground-android/blob/956e9f110d75430f27633abb70f8bc9198ec2787/ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt#L40-L44
