### ISSUE TITLE
[Data collection hint snackbar] Add explicit "dismiss" action ("X") as per mocks 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2297]
@scolsen PTAL?

**Comment by jcqli** [comment]
@gino-m Based on https://github.com/google/ground-android/pull/2288#issuecomment-1976838989 I marked this as P2. OK to remove from Iteration 6? I think we have enough on our plates

**Comment by gino-m** [comment]
@jcqli Sgtm, I removed it.
