### ISSUE TITLE
[Active project] Indicate currently active project

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#230]
After selecting a project from the side-drawer, the title of the selected project is not shown anywhere in the app. 

I propose that, we add that info somewhere in the app or change the UI to make it more intuitive (For e.g. Instead of opening a dialog when selecting "Select Project", we expand it and highlight the one selected)

**Comment by gino-m** [comment]
How about showing the list of projects in a section in the left-side drawer (nav menu)? Then the active one can appear checked/selected.

**Comment by shobhitagarwal1612** [comment]
SGTM!

**Comment by gino-m** [comment]
..this could be similar to how Gmail Android displays labels: https://support.google.com/mail/thread/9052188). Instead of this we'd have something like:

PROJECTS
[icon] Project A
[icon] Project B
[gears] Join/leave projects

Wdyt?
