### ISSUE TITLE
[Data collection] Show message when draft is restored

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2303]
A snackbar with text: "The app was closed during data collection. Your unsaved draft has been restored."

@amegantz for copy. Note that the app can be closed by the OS when in the background to conserve resources, or the user could have force quit the app, and we have no way to determine which happened.

**Comment by amegantz** [comment]
I'd replace "draft" with "data," otherwise LGTM!

(Also I know "data" is technically plural, but it's basically singular now in common practice)

**Comment by gino-m** [comment]
> I'd replace "draft" with "data," otherwise LGTM!
> 
> (Also I know "data" is technically plural, but it's basically singular now in common practice)

SGTM! If we want to do this as a snackbar, how would we shorten this? Something like "App was closed. Unsaved data restored."?
