### ISSUE TITLE
[Geometry data collection] Add a way to return to LOI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2309]
When panning/zooming away from LOI, there's no easy way to get back it. @rawbzz any ideas?

**Comment by rawbzz** [comment]
@gino-m can you share a screencast of an example ? thank you!

**Comment by gino-m** [comment]
App is currently unstable, but essentially when you tap an LOI (card or geometry on map) you see this:

![image](https://github.com/user-attachments/assets/9be7e286-6f5a-4641-bd53-b6a3849e0e48)

The broader question is what should happen if you pan the map away from the selected LOI? I assume we should deselect the LOI in order to be consistent with the current behavior that only cards for LOIs within the viewport are shown?

**Comment by gino-m** [comment]
For simplicity, I propose we punt this in favor of https://github.com/google/ground-android/issues/2608
