### ISSUE TITLE
[Draw an area] Dialog shown only after adding point, text incorrect

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2311]
Screenshot pending

Expected:

![image](https://github.com/google/ground-android/assets/228050/d37eec88-b23a-4a2a-b3ab-f5f09a431d0f)

**Comment by sufyanAbbasi** [comment]
Note: I was unable to reproduce the issue where the dialog would only show up when the first point was added but I noticed that we were determining the task visibility state by overriding `setMenuVisibility()` which was a deprecated in newer versions of Android (+28). I decided to refactor by using `onResume()` instead.
