### ISSUE TITLE
[Layers bottom sheet] Label next and help icon incorrect

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2325]
Two minor issues

- [ ] Tapping the (?) help icon has no effect. We should remove this.
- [x] The offline map imagery toggle still contains placeholder text

@amegantz For actual text

![image](https://github.com/google/ground-android/assets/228050/35402501-a901-4acd-a5e7-0cddcf5a56b9)

**Comment by gino-m** [comment]
@sufyanAbbasi Could you squeeze this in today? For the help text, I'd suggest:

> Tap here to download and manage offline map imagery.

With "here" pointing to the "offline map imagery" UI. @vittorino @amegantz Is this ok?

**Comment by amegantz** [comment]
![image](https://github.com/google/ground-android/assets/112978024/28fc4e84-e17b-4823-95d0-c178fe9c81c3)

**Comment by sufyanAbbasi** [comment]
Sorry, I opened a duplicate for this bug: https://github.com/google/ground-android/issues/2345, fixed by https://github.com/google/ground-android/pull/2347.

Will close this bug when I remove the help icon.
