### ISSUE TITLE
[Compliance] Display licenses and ToS in app

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2326]
Potentially using https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

**Comment by sufyanAbbasi** [comment]
I'm on it!

**Comment by sufyanAbbasi** [comment]
Do we want to show the licenses trigger as a small link at the bottom of the menu, above the build version info?

**Comment by shobhitagarwal1612** [comment]
We can also put it in the settings screen.

**Comment by gino-m** [comment]
Please work with @rawbzz to determine the proper placement and UX. Thanks!

**Comment by rawbzz** [comment]
<img width="471" alt="Screenshot 2024-04-17 at 2 37 52 PM" src="https://github.com/google/ground-android/assets/108412767/a722a7e7-ea9f-4261-8f36-f7866a1fc8f0">

Android designs
