### ISSUE TITLE
Manually disabling location permissions then reopening app puts app in non-loaded state

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-android#2335]
**Describe the bug**
By manually removing app permissions and revisiting the app, the app doesn't load any data for some reason, even when the network is on.

**To Reproduce**
1. Ensure app has location permissions, click on a survey.
2. While in the survey map view, before clicking on "Collect", go into app settings and remove location permissions.
3. Then re-open the app using the "Open" button on the settings. 
4. See that app is in a weird state where nothing is loaded.

**Expected behavior**
App is loaded but with no location set.

**Actual behavior**
- No surveys or data are loaded.
- No user data is loaded in the sidebar menu.

**Screenshots**

![Screenshot 2024-03-12 at 3 58 43 PM](https://github.com/google/ground-android/assets/12646706/2e00df1b-a890-4890-9bcf-8e3618a308b9)
![Screenshot 2024-03-12 at 3 55 53 PM](https://github.com/google/ground-android/assets/12646706/a93bd3de-e6b0-4a91-85e6-a1c18233182e)
![Screenshot 2024-03-12 at 3 55 58 PM](https://github.com/google/ground-android/assets/12646706/dda6d29d-69e6-4bea-9afb-05577688d272)

**Comment by gino-m** [comment]
@jcqli for triage

**Comment by shobhitagarwal1612** [comment]
Upon further investigation, I found that `StartupFragment` isn't called when opening the app as per above instructions. Due to that, firebase authentication isn't properly setup and all coroutines which depend on current user e.g. fetching surveys, loading user info etc gets stuck indefinitely.
