### ISSUE TITLE
[Layers Drawer] Replace placeholder text

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-android#2345]
![image](https://github.com/google/ground-android/assets/12646706/278f48a7-bea0-409e-a77d-c51e7d079a13)

Currently: `This is an explanation of the offline overlay. \nThe images come from this source.`

**Comment by amegantz** [comment]
![image](https://github.com/google/ground-android/assets/112978024/974e37bf-c871-44af-9631-1c98af8c90b0)
```
Offline map imagery
Hide or show downloaded imagery
```
