### ISSUE TITLE
[Draw an area] Location lock doesn't disengage when map is manually panned

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2360]

**Comment by shobhitagarwal1612** [comment]
I'm unable to repro this.

**Comment by shobhitagarwal1612** [comment]
@gino-m Are you able to consistently repro this?

**Comment by gino-m** [comment]
Did you not see the same? It's possible I mixed up drop pin with capture location... if you can't repro please disregard!

**Comment by shobhitagarwal1612** [comment]
In capture location task, map cannot be panned.

**Comment by gino-m** [comment]
> In capture location task, map cannot be panned.

I know, I may have just gotten confused. Thanks!
