### ISSUE TITLE
[Draw area task] Add support for partial loads of drawn areas (works for completed ones)

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2373]
Split from https://github.com/google/ground-android/issues/708

**Comment by shobhitagarwal1612** [comment]
Remaining item: add support for draw polygon task

**Comment by gino-m** [comment]
> Remaining item: add support for draw polygon task

Hi @shobhitagarwal1612, that's the actual scope of the issue. Do you know how much work is involved, eg in terms of # days?

**Comment by shobhitagarwal1612** [comment]
I think it'll take atleast 1 week

**Comment by gino-m** [comment]
> I think it'll take atleast 1 week

1 day @ 20%

**Comment by sufyanAbbasi** [comment]
@shobhitagarwal1612 in the above PR said:

> This won't work if the drawn area isn't complete, right? My understanding was that we have to persist partial polygon as well, but that was causing some troubles as we create the task data only when the polygon is marked as complete. The current approach is a big improvement over not loading anything at all.

> @gino-m Can we confirm that we don't need to re-load partial polygons?

I think we can lower the priority of this feature to P2 to support partial loads.

**Comment by gino-m** [comment]
> @shobhitagarwal1612 in the above PR said:
> 
> > This won't work if the drawn area isn't complete, right? My understanding was that we have to persist partial polygon as well, but that was causing some troubles as we create the task data only when the polygon is marked as complete. The current approach is a big improvement over not loading anything at all.
> 
> > @gino-m Can we confirm that we don't need to re-load partial polygons?
> 
> I think we can lower the priority of this feature to P2 to support partial loads.

While being drawn, polygons spend more time being incomplete than complete, in which case the risk is the user will be more likely to have to start over again if they navigate away from Ground for a sec. I'd say this is P1.5, but ok to keep at P2 for now.
