### ISSUE TITLE
[Sync] Map zooms when LOIs are changed remotely

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2378]
**Repro**

While online:

1. Open a survey with LOIs
2. Modify an LOI manually in Firebase (e.g., update the position of a pin)

**Expected behavior**

Map reflects changes in remote db

**Actual behavior**

Map updates then zooms out 1-2 zoom levels

@shobhitagarwal1612 @jcqli @sufyanAbbasi FYI

**Comment by gino-m** [comment]
See #2563 for report by user.

**Comment by gino-m** [comment]
@shobhitagarwal1612 The app becomes unusable when multiple LOIs are updated remotely, bumping to P0

**Comment by shobhitagarwal1612** [comment]
The root cause is that we apply a padding of 100px when moving map camera using bounds. This was done to allow showing the LOIs on the edge of the screen for first opens.

**Comment by gino-m** [comment]
The padding is ok to keep - the problem is we should update the bounds on the first load of LOIs, not on every update.

**Comment by shobhitagarwal1612** [comment]
Raised https://github.com/google/ground-android/pull/2630
