### ISSUE TITLE
[ACLs] Add custom text and link to sign up form 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2402]
For now we can add `android:autoLink="web"` to the dialog `permission_denied_dialog.xml` and customize the `contact_survey_organizer_to_obtain_access` string in the of-ground fork. In the future we should read the url from Firestore `config/properties/signUpUrl` @rfontanarosa FYI

See also https://github.com/google/ground-platform/issues/1679

**Comment by rawbzz** [comment]
@gino-m  or @jcqli is there a screenshot of what screen this would need to live? ty!

**Comment by gino-m** [comment]
@rawbzz  There's currently a dialog which looks something like this:

<img width="187" alt="image" src="https://github.com/google/ground-android/assets/228050/538a0b5d-4910-4ef1-8c11-2d7931935f02">

Needs work!

**Comment by gino-m** [comment]
@rawbzz Much better! We should replace "Contact your system admin.." with the text explaining they don't have access and should sign up at the specified link. @amegantz for copy!

**Comment by amegantz** [comment]
![image](https://github.com/google/ground-android/assets/112978024/b7c3d91b-b526-42ad-8ef7-0c4105b38be5)
To continue, contact your system administrator to request access.
To continue, sign up to request access. 

If you sign out, all unsaved data will be lost.

**Comment by gino-m** [comment]
@lecrabe @rfontanarosa FYI

**Comment by jcqli** [comment]
@shobhitagarwal1612 Do you have capacity to look work on this one?

**Comment by shobhitagarwal1612** [comment]
@gino-m Is the product requirement that first dialog be shown if the sign up form link is missing else the second dialog (as per https://github.com/google/ground-android/issues/2402#issuecomment-2113585224)?

**Comment by gino-m** [comment]
> @gino-m Is the product requirement that first dialog be shown if the sign up form link is missing else the second dialog (as per [#2402 (comment)](https://github.com/google/ground-android/issues/2402#issuecomment-2113585224))?

That's correct!
