### ISSUE TITLE
[Survey list] Screen freezes while loading LOIs on slower connections

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2404]
[Screen_recording_20240322_161732.webm](https://github.com/google/ground-android/assets/228050/902b76c5-e775-4bc5-9c88-3c99613ae9de)

After tapping a survey, spinner is shown when loading, but then freezes while loading LOIs (I think). We should show the spinner until everything is loaded.

@jcqli FYI

**Comment by anandwana001** [comment]
@gino-m Tried with multiple surveys having LOIs, and it's working fine or me, it takes time in slower connection, and with our latest codebase where we keep showing the loading until everything is ready to use so nothing will go freeze

**Comment by gino-m** [comment]
@anandwana001  Great, closing this as fixed!
