### ISSUE TITLE
[Take a photo task] Do not allow to select photo from library

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2435]
Requested by @lecrabe

**Comment by scolsen** [comment]
This should be easy enough to change -- I can take it if no one else wants to do it!

**Comment by gino-m** [comment]
> This should be easy enough to change -- I can take it if no one else wants to do it!

Awesome, thank you!

**Comment by shobhitagarwal1612** [comment]
We recently added it back in https://github.com/google/ground-android/pull/2318

Are we removing it for all users or making it configurable?

**Comment by gino-m** [comment]
> We recently added it back in #2318
> 
> Are we removing it for all users or making it configurable?

It was previously in the designs but not the implementation. We added it, but after talking with partners they're convinced it's better to always require users to take an actual photo. In that case we can just remove it. Sorry for the churn.
