### ISSUE TITLE
[Draw area task] Location card obscures location lock button

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2442]
![Screenshot 2024-04-12 at 8 24 28 AM](https://github.com/google/ground-android/assets/228050/b73ecf40-5575-462c-8982-8eb387d2bbcc)

![Screenshot 2024-04-12 at 8 25 41 AM](https://github.com/google/ground-android/assets/228050/b7dced44-9a6c-4d5d-8fcb-6981c51301c7)

@rawbzz Is looking at this UI element now, may want to wait for final designs before fixing.

**Comment by gino-m** [comment]
To consider in context of new popup card design

**Comment by rawbzz** [comment]
<img width="516" alt="Screenshot 2024-04-19 at 1 30 26 PM" src="https://github.com/google/ground-android/assets/108412767/ecda83bf-c043-4cda-b610-6cccbe639153">

**Comment by gino-m** [comment]
I like it! @rawbzz Should we make the styling of the line more consistent with the blue dot styling (e.g., white?)

Also, Can you update the text of current location to show Lat Lng without Altitude, and with Accuracy being shown when location lock is enabled?

**Comment by rawbzz** [comment]
yes! how is accuracy measured? Also would i need to show lat lng if accuracy is shown? or just one or the other shows?

**Comment by gino-m** [comment]
> yes! how is accuracy measured? Also would i need to show lat lng if accuracy is shown? or just one or the other shows?

For now we can just show meters (m). In the future we will probably want to add a setting for other units.

Lat/lng would always be shown, since it applies both to manual selection and auto/current location. Accuracy only applies when location lock is enabled.

**Comment by gino-m** [comment]
For now we can just show meters (m). In the future we will probably want to add a setting for other units.

Lat/lng would always be shown, since it applies both to manual selection and auto/current location. Accuracy only applies when location lock is enabled.

**Comment by rawbzz** [comment]
Maybe something like this??

<img width="436" alt="Screenshot 2024-04-19 at 3 59 28 PM" src="https://github.com/google/ground-android/assets/108412767/55eb0746-31da-4a59-afe6-9b3601a5ff7b">
<img width="445" alt="Screenshot 2024-04-19 at 3 59 34 PM" src="https://github.com/google/ground-android/assets/108412767/297ca66e-9910-47de-a33f-6dd917196a1d">

**Comment by gino-m** [comment]
Looks great! One nit: Can the card w/accuracy be made to fit in two lines, perhaps by showing Accuracy right aligned?
