### ISSUE TITLE
[Capture location] Capture location button label truncated on some devices

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2443]
![image](https://github.com/google/ground-android/assets/228050/b3e1abdb-0459-4275-8958-fef1197572f1)

@rfontanarosa What device were you using for the demo today?

**Comment by gino-m** [comment]
@shobhitagarwal1612 @jcqli  Let's come back to this on the next iteration?

**Comment by shobhitagarwal1612** [comment]
I'm unable to reproduce this in Pixel 4 API 32 (4.65inch 720x1280). Can we have more details around the device configuration?

**Comment by jcqli** [comment]
Can't repro
