### ISSUE TITLE
[Bug] Blank screen after pressing back from home screen

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#245]
**Describe the bug**
Blank screen appears after pressing back button in home screen

**To Reproduce**
1. Go to home screen
2. Press 'back' button
3. White blank screen appears

**Expected behavior**
App should either close or show confirmation to exit

**Comment by shobhitagarwal1612** [comment]
We can apply a workaround to fix the behavior but that wouldn't be the best solution.
I've noticed that `popUpTo` and `popUpToInclusive` in nav_graph.xml aren't functioning as they are supposed to. @gino-m Is this behavior same from the beginning or did it break after some time?

**Comment by gino-m** [comment]
Those attributes have never behaved as I expected them to, but I haven't
figured out if we were using the API wrong or if it's a bug.
