### ISSUE TITLE
[Migration: protobuf for Firestore] Introduce new schema to app

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2467]
This issue is to track changes in the Android app that introduce the new schema, part of migration that is tracked in https://github.com/google/ground-platform/issues/1762

1. Update Android app to write submissions to new structure
2. Update Android app to read survey metadata and LOIs in new structure

**Comment by sufyanAbbasi** [comment]
@gino-m, lmk if this sounds correct to you:

Tasks:

### Reads
- [ ] Read survey list @sufyanAbbasi
- [ ] Read survey @sufyanAbbasi
- [ ] Read LOIs @sufyanAbbasi

### Writes
- [ ] Create LOIs @sufyanAbbasi
- [ ] Create submission @shobhitagarwal1612
- [ ] Delete code for old schema @sufyanAbbasi

Essentially, we want to use the `ProtobufToFirestoreExt.kt` and vice versa, `FirestoreToProtobufExt.kt` methods to replace the Kotlin dataclasses with protos. The Firebase server saves both the existing documents using the normal schema string keys and also the proto encoded schema using the proto index as key.

For the first pass, for reads. we can decode the protos and translate them into the intermediary Kotlin data classes (skipping the Firebase document rules), then later we can replace those Kotlin data classes with reference to the protos directly.

For the writes, we'll do the same thing as the platform server, publishing both normal schema and proto versions.

**Comment by jcqli** [comment]
@sufyanAbbasi @shobhitagarwal1612 @gino-m  I'll split those tasks outlined above into separate issues. Please LMK if there are any questions!

**Comment by jcqli** [comment]
The tasks above now have subtasks. I'll close this as done since we have identified each subtask and assigned them
