### ISSUE TITLE
[Code health] Add proto linter to `checkCode` Gradle target

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2472]
Perhaps bufLint would work? https://github.com/bufbuild/buf-gradle-plugin

@sufyanAbbasi FYI

**Comment by shobhitagarwal1612** [comment]
This is no longer valid as the proto files now live under ground-platform repo

**Comment by gino-m** [comment]
Filed https://github.com/google/ground-platform/issues/1903 to track
