### ISSUE TITLE
[Draw or walk perimeter] Instructions not shown on first use

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2479]
This was an add LOI task at 2nd position, just after capture location task

@regigeorge1 FYI

**Comment by gino-m** [comment]
@anandwana001 To verify

**Comment by anandwana001** [comment]
Instructions are visible on first use

<img src="https://github.com/user-attachments/assets/55d21b72-6949-4a7a-842d-c1597f73dfb2" width=220 height=420/>

**Comment by gino-m** [comment]
> @gino-m Instructions are visible on first use
> 
> <img alt="" width="220" height="420/" src="https://private-user-images.githubusercontent.com/25057618/361764706-55d21b72-6949-4a7a-842d-c1597f73dfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTA2MTAsIm5iZiI6MTcyNDc5MDMxMCwicGF0aCI6Ii8yNTA1NzYxOC8zNjE3NjQ3MDYtNTVkMjFiNzItNjk0OS00YTdhLTg0MmQtYzE1OTdmNzNkZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDIwMjUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjQ2M2VjMGE5MDRhMWYyYWIxYWJmZDMwNzA5OWNlMDQ4ZmRiNWQ0ODVkZDg3ZDc3ZjViMTUxZGZmNmFhZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dv1TDxszlR4rPtkG8sCuF7WPhQMF2FbSlzLUX6P3uNc">

Also when this isn't the first task in the job?

**Comment by anandwana001** [comment]
@gino-m Yes, working in both the cases, no matter draw  or walk permiter is coming at first in the task list or last. 

Hence verified, we can close the ticket.

**Comment by gino-m** [comment]
Thanks for confirming!
