### ISSUE TITLE
[Draw area task] Visualize plot area while drawing after 3 or more points are added

### ISSUE THREAD

**Issue by lecrabe** [google/ground-android#2491]
Users want to see the area of the plot they just collected
Can it be shown when the plit is collected ?

**Comment by gino-m** [comment]
@rawbzz PTAL?

**Comment by rawbzz** [comment]
hi @gino-m just seeing this! Isn't this what we do here? or is this referring to another flow?
![Uploading Screenshot 2024-08-16 at 1.28.37 PM.png…]()

**Comment by gino-m** [comment]
The image isn't visible but I do believe this is in the designs, it's just not implemented yet

**Comment by rawbzz** [comment]
In designs, but not yet implemented!
![Image](https://github.com/user-attachments/assets/31e6ae08-a61c-4db8-ad1b-a9bd2024fb26)

**Comment by gino-m** [comment]
> In designs, but not yet implemented! ![Image](https://github.com/user-attachments/assets/31e6ae08-a61c-4db8-ad1b-a9bd2024fb26)

The issue is referring to seeing the surface area in sq meters (@lecrabe or km?).

**Comment by gino-m** [comment]
Duplicate of #2096
