### ISSUE TITLE
Use protos when creating submissions

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2494]
Split from https://github.com/google/ground-android/issues/2467

Tracked in https://github.com/google/ground-platform/issues/1758

**Comment by shobhitagarwal1612** [comment]
We don't load submissions from remote firebase to the local app. I don't think there is any other item left to be migrated. 
@gino-m @sufyanAbbasi

**Comment by shobhitagarwal1612** [comment]
Actually, the app used to load submission in earlier versions. So, the code for reading submissions exists in the app but it is not being used anywhere. We potentially clean it up if there are no plans to load it in future either.

**Comment by gino-m** [comment]
We can delete the code since it's not being used now, thanks!

**Comment by gino-m** [comment]
@jcqli I think this issue was tracking something different than the proto migration, reverting title back to original and creating bug, @shobhitagarwal1612 please cmiiw.
