### ISSUE TITLE
Multiple selection option font is enlarged

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-android#2549]
**Describe the bug**
The multiple choice options are large compared the one option selection.

**To Reproduce**
1. Run local `google/ground-platform` server via `npm run start:local`
2. Create a new survey with a multiple choice selection at http://localhost:5000
3. Run local app in `localDebug` variant.
4. Start the task and see that the font is large

**Screenshots**
![Screenshot 2024-07-16 at 4 39 39 PM](https://github.com/user-attachments/assets/57097b2f-97f2-49a0-8014-ee579f6ee2bb)
![Screenshot 2024-07-16 at 4 42 51 PM](https://github.com/user-attachments/assets/dab1f5e7-f4eb-42c2-8d52-26677f66af8c)

**Comment by gino-m** [comment]
Thanks for filing, @sufyanAbbasi . The spacing also appears to be off. Designs:

[Select one](https://www.figma.com/design/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?node-id=2069-49498&t=QpzmpnECt4vo7iad-4)

![image](https://github.com/user-attachments/assets/3d2173e1-29c5-42a8-97e3-b8529a99089b)

[Select multiple](https://www.figma.com/design/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?node-id=2069-48207&t=QpzmpnECt4vo7iad-4)

![image](https://github.com/user-attachments/assets/3077b93e-ab77-4ed0-b597-b91b87915cba)
