### ISSUE TITLE
Cached Google Earth Imagery for offline useage

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2550]
Hey, it was great to see that satellite imagery can be downloaded for offline use. However, the zoom level of that Sentinel imagery is unfortunately unpractical for use in the field and disappears when zooming in closely.

Seeing that most Google satellite imagery is quite recent, can the cache be downloaded locally for offline use? I've seen it implemented in other apps.

Thanks for the consideration.

**Comment by gino-m** [comment]
Hi @jo-spek, thanks for the feature request!  The Earth satellite imagery is automatically cached locally when viewed, but unfortunately it cannot be downloaded explicitly. What apps have you seen that do this? I'd like to better understand what they're doing. Thanks!

**Comment by gino-m** [comment]
Thanks again. Are you sure they're download Maps imagery for offline use? I don't see a mobile app in that repo so it's hard to tell.

**Comment by jo-spek** [comment]
There is a commercial fork by the contracted developer on GooglePlay called INATrace Pro. You can use it as a guest and give it a try. 

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Jul 18, 2024 at 17:00, Gino ***@***.***> wrote:   


Thanks again. Are you sure they're download Maps imagery for offline use? I don't see a mobile app in that repo so it's hard to tell.

**Comment by gino-m** [comment]
> There is a commercial fork by the contracted developer on GooglePlay called INATrace Pro. You can use it as a guest and give it a try.  

I installed and tested it. I see it's using MapBox imagery, which actually can be downloaded offline:
https://docs.mapbox.com/help/troubleshooting/mobile-offline

Afaik this currently isn't possible with Maps/Earth imagery (beyond caching as mentioned).

**Comment by jo-spek** [comment]
Ah, too bad. That I wasn't aware of. Thanks for looking into it!
