### ISSUE TITLE
[Take a photo] Photos are not stored in their correct orientation

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2552]
Orientation is not respected when viewing photos in Android or web. Downloading the image and viewing in other viewers the orientation is also incorrect.

@shobhitagarwal1612 Do you have any ideas?

@lecrabe FYI

**Comment by sufyanAbbasi** [comment]
Oh no... this does not look super promising:
https://stackoverflow.com/questions/39896755/android-ensuring-that-photo-orientation-is-preserved-when-taking-photos-via-ca

https://github.com/react-native-camera/react-native-camera/issues/309

Essentially it seems like we need to do a better job of saving the orientation on the EXIF header, I will look into whether we are actually capturing that metadata, and if not, maybe we can inject it in?

**Comment by gino-m** [comment]
That thread is from 2016, I wonder if this has been solved since then.. does setting the orientation as per https://developer.android.com/media/camera/camerax/take-photo#take-photo help?

**Comment by sufyanAbbasi** [comment]
Good find, I'll take a look!

**Comment by anandwana001** [comment]
We tested both on emulator as well as on physical device, and things are correct, no repro.


<p>
<img width="1252" alt="Screenshot 2024-08-16 at 10 13 48 PM" src="https://github.com/user-attachments/assets/5d24cf11-00d2-453e-9a67-5f1a8199801b">
<img width="1320" alt="Screenshot 2024-08-16 at 10 13 39 PM" src="https://github.com/user-attachments/assets/3ff4edca-2376-4646-b59a-3d66ce208a4a">
<img width="1258" alt="Screenshot 2024-08-16 at 10 13 31 PM" src="https://github.com/user-attachments/assets/eb57048b-7c07-42a9-9021-96cbcc9ad324">
<img width="1285" alt="Screenshot 2024-08-16 at 10 13 21 PM" src="https://github.com/user-attachments/assets/ef6c48d9-0614-4286-8002-abcef62979b0">
<img width="1362" alt="Screenshot 2024-08-16 at 10 12 55 PM" src="https://github.com/user-attachments/assets/3d637fbc-00ac-4e20-a57e-3a6449c4aee3">
</p>

**Comment by gino-m** [comment]
@anandwana001 I was still able to repro on Pixel 7.

The issue I found is that we decompress the JPEG to raw bitmap without preserving the EXIF orientation bit. I'm not sure we need to do that except for visualization; we probably could just upload the image as it comes from the camera (filed #)

#2662 fixes this issue on my device by rotating the bitmap once decompressed. I don't quite understand how it worked from your device. Can you try that PR out on your device when you get a sec?
