### ISSUE TITLE
Map keeps zooming out from the location

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2563]
**Describe the bug**
During field testing in Kenya I saw this behaviour happening on different participants' phones and occasionally on mine as well: When zooming in in our pre-set surveys, on many phones the app would just incrementally zoom out almost to whole-Africa level. That made geodata-recording quite difficult, because participants had to zoom in again and again for every single point, and click "Add point" very quickly before the map would zoom out again.

**To Reproduce**
I made Gino a Survey Organizer of the surveys in question
--> "Coffee Kenya Field Campaign Points 2024-07-17" and "Coffee Kenya Field Campaign Polygons 2024-07-17"

I haven't found consistency in the behaviour, so I can't tell exactly how to reproduce this.
We first assumed that the rainy weather caused 'ghost hand' behaviour on peoples' screens, but it later happened in dry conditions on my phone, too, so that can probably be ruled out.
Another assumption is that having registered geolocations in different places far away from each other cause the map to zoom out to the aggregate level, where one can see the neat green summary circles.
Possibility 3 is that it has something to do with the downloaded Sentinel imagery.

I will update this if I find a clearly recognizable pattern to this behaviour. I might be able to give you information on the exact time and users to whom this happened if that's of any help. Let me know, and I will find it.

**Expected behavior**
Upon zooming in on maps, they should stay at the respective zoom-level and not start to zoom out autonomously.

Best, Jonas

**Comment by gino-m** [comment]
This is likely related to #2378 - when a user adds a new site, the app tries to sync LOIs and update the viewport. This viewport should not be updated on remote sync. Closing as dupe with reference to this description, thank you!
