### ISSUE TITLE
Target / Zoom-In button hidden behind map location pane

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2564]
**Describe the bug**
Field testing in Kenya I saw this on many participants' phones: 
The target button to zoom in to your current GPS location was hidden behind the map location pane. 

**To Reproduce**
Maybe try on some different phones.
I also saw this behaviour on an older person's phone which had a system-wide increased zoom.

**Expected behavior**
Target button next to 'Map location' pane.

**Actual behavior**
Target button beneath 'Map location' pane. Hard to see and hard to click.

**Screenshots**
Error as seen on a Samsung A13:

![1721657603978](https://github.com/user-attachments/assets/b338cb51-d645-40a7-a066-0a052d365456)

**Comment by gino-m** [comment]
@shobhitagarwal1612 Was this fixed? If so please close.

**Comment by shobhitagarwal1612** [comment]
Yes, this is already resolved.
