### ISSUE TITLE
[Date task] "Skip" button not shown for optional date tasks

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2612]
...and perhaps others?

**Comment by anandwana001** [comment]
When all the items are optional 

https://github.com/user-attachments/assets/6fffd388-1e9c-4a66-9970-cc3b579b482c


When only Date is optional

https://github.com/user-attachments/assets/1ce9b66e-3f12-45af-bbe1-1cab27da87a6

**Comment by anandwana001** [comment]
Also, Once the user selects the date, the SKIP button will no more visible on screen as that's not the case. Because, now the user cannot remove the input date, the date can only be change, not deleted, hence the skip button is no more their on the screen

**Comment by gino-m** [comment]
> @gino-m Also, Once the user selects the date, the SKIP button will no more visible on screen as that's not the case. Because, now the user cannot remove the input date, the date can only be change, not deleted, hence the skip button is no more their on the screen

That makes sense!

**Comment by anandwana001** [comment]
I think we can close this issue.

**Comment by shobhitagarwal1612** [comment]
> Also, Once the user selects the date, the SKIP button will no more visible on screen as that's not the case. Because, now the user cannot remove the input date, the date can only be change, not deleted, hence the skip button is no more their on the screen

Can we undo the response after selecting the date/time? That should restore the skip button as well.

**Comment by anandwana001** [comment]
> > Also, Once the user selects the date, the SKIP button will no more visible on screen as that's not the case. Because, now the user cannot remove the input date, the date can only be change, not deleted, hence the skip button is no more their on the screen
> 
> Can we undo the response after selecting the date/time? That should restore the skip button as well.


More of a product question

**Comment by shobhitagarwal1612** [comment]
I think this should be already implemented. Just curious if it is working as I'm hoping it to work.

**Comment by gino-m** [comment]
Looking at @anandwana001 's videos about this appears to have been fixed.
