### ISSUE TITLE
[Data collection] Changes to data on current screen not saved when app is minimized and "next" not yet clicked

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2623]
Please also check text and other types.

**Comment by anandwana001** [comment]
Supporting Video to this Issue


https://github.com/user-attachments/assets/5727671b-bd55-4830-bedf-b9ea7e9eaeda

**Comment by anandwana001** [comment]
So the correct bug we are seeing here is after resuming the application, the location/pointer moves back to the default place, not the place where we last left it.


https://github.com/user-attachments/assets/15dd523a-96a0-4e2a-b8dd-654aec139470

**Comment by anandwana001** [comment]
https://github.com/user-attachments/assets/df7e8e1b-4b27-49f5-b93d-e0ea0f55146c


Without Completing Polygon

**Comment by anandwana001** [comment]
@gino-m Tested all types of collection, and all are working fine. Check the attached video. I think we can close this issue.
I think I found is  with the other option text area, I will check and file other issue if anything required.


https://github.com/user-attachments/assets/0dc2d3e2-499b-4ab8-9ea2-3b708bed4000

**Comment by anandwana001** [comment]
should we close this and create a separate issue for app kill?

**Comment by gino-m** [comment]
Based on @anandwana001 's video I think we can close this one. What is the issue # of the "app kill" case? We should be sure to enumerate the remaining "draft" states to be saved in the issue.

**Comment by anandwana001** [comment]
> Based on @anandwana001 's video I think we can close this one. What is the issue # of the "app kill" case? We should be sure to enumerate the remaining "draft" states to be saved in the issue.

raised PR for kill case, which includes partial load, so kill case and partial load for all type of task will get done in one PR.

**Comment by anandwana001** [comment]
> Based on [@anandwana001](https://github.com/anandwana001) 's video I think we can close this one. What is the issue # of the "app kill" case? We should be sure to enumerate the remaining "draft" states to be saved in the issue.


Closing this issue.
