### ISSUE TITLE
[Add LOI] LOI names added to wrong field in db

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2626]
They're being added to `custom_tag`, which is reserved for imported ID. 

The desired proto path in LOI is `properties['name'].string_value`.

@shobhitagarwal1612 PTAL?

**Comment by gino-m** [comment]
From the looks of the LOI card, it appears it's being set in both customTag and name fields:

![image](https://github.com/user-attachments/assets/245924bf-b340-470f-9520-dda88fdccb61)

**Comment by sufyanAbbasi** [comment]
Sorry! This was my fault!

I filed: https://github.com/google/ground-android/issues/2576
and "fixed it": https://github.com/google/ground-android/pull/2577

I thought the customId was important but it wasn't as important as I thought...

**Comment by gino-m** [comment]
> Sorry! This was my fault!
> 
> I filed: #2576 and "fixed it": #2577
> 
> I thought the customId was important but it wasn't as important as I thought...

There are two things:

* `customTag`: User-defined (imported) ID for the LOI
* `properties.name` User-defined label for the LOI

These get displayed to the user as defined in https://github.com/google/ground-android/issues/1926.

Iiuc, the changes you implemented treat those as interchangeable in the db, whereas they should actually be kept separately; they are only combined using the rules in #1926 at render time.

**Comment by sufyanAbbasi** [comment]
Fixed by https://github.com/google/ground-android/pull/2645
