### ISSUE TITLE
Warn user that they won't be able to sign back in if they sign out while offline

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2643]
Currently we only warn that unsynced data will be lost. We should also inform the user that:

* Offline surveys will no longer be available until their sign back in
* They won't be able to sign in until they're back online

![image](https://github.com/user-attachments/assets/bf635854-559c-464f-8a76-e8e2fea3d030)

@amegantz Suggestions here?

**Comment by amegantz** [comment]
![image](https://github.com/user-attachments/assets/eb15ecdf-a27a-4bb9-81f0-286a802ab5a8)
If you sign out:
- Any unsynced data will be discarded
- You won't be able to sign in if you’re offline
- Offline surveys won’t be available until you sign in again

Are you sure you want to sign out?

**Comment by jcqli** [comment]
Need to add that you can't log back in if offline
