### ISSUE TITLE
[Capture location] Prompt for location permissions when capture location task is opened

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#2658]

**Comment by gino-m** [comment]
Capture location task may be replaced with "drop pin" task; we should get clarity on that before implementing this.

**Comment by gino-m** [comment]
As per @jo-spek we still need both capture location and drop pin as distinct task.

**Comment by anandwana001** [comment]
@gino-m  For Capture Location. Task, we have a location lock, so the permission dialog will always appear on the screen.

Do we need the same for Drop Pin & Draw or walk permiter?

<img src="https://github.com/user-attachments/assets/87b03d38-8689-42a5-8723-229bd1fa24ff" width=200 height=420/>

**Comment by gino-m** [comment]
The permissions should only be requested when needed, on those screens when the user taps the location lock, and immediately in the capture location screen.

**Comment by anandwana001** [comment]
ah, got it.

The current scenerio is,the permission dialog comes up at the first time, but if the user reject it, the location lock button is getting disabled by default and click is not working on it.

Let me check and raise a pr for this fix.

**Comment by anandwana001** [comment]
@gino-m if you could confirm the below user journey

Do we need to show the location permission if user moves back and forth? First time it is working fine. 


https://github.com/user-attachments/assets/e377cb35-86aa-4598-9e6e-bd7ffa801758

**Comment by gino-m** [comment]
For "capture location" tasks I would say yes.  Rather than showing "Map location" on those tasks when location is disabled perhaps we want to say "Allow location sharing to continue?"

**Comment by anandwana001** [comment]
@gino-m ok,

So, earlier we had kept the location button locked in the Capture Task, but now we have to keep to open so that user can click and get the permission dialog box, but if user disabled it keeping the device location enabled, we will not move forward.

Let me raise a PR for better understanding with user journey video

**Comment by gino-m** [comment]
@kenstershiro The question here is how to handle the case when the user refuses access to location during the "capture location" data collection tasks. The first solution that comes to would be to show a modal dialog that doesn't let the user proceed until location permission is granted. To dialog could have two buttons, something like "Try again" or "Discard changes". The former would re-request permissions, the latter would close the data collection flow. Wdyt?

**Comment by anandwana001** [comment]
@kenstershiro gentle reminder

**Comment by gino-m** [comment]
@anandwana001 For now let's assume the user is directed to the dialog in #2635. If they say "no, don't leave survey", they'll be prompted for location permission again.

@amegantz Should we show custom text here to the dialog in this case do the tune of "If you don't grant location permission you can't continue to collect data for this site...." Buttons: "Exit" | "Try again"?

**Comment by anandwana001** [comment]
https://github.com/user-attachments/assets/f825c5d1-5754-4927-8ff5-995389ef517e

**Comment by gino-m** [comment]
> @amegantz Should we show custom text here to the dialog in this case do the tune of "If you don't grant location permission you can't continue to collect data for this site...." Buttons: "Exit" | "Try again"?

@amegantz Gentle ping

**Comment by amegantz** [comment]
Sorry for the late response. How about this? Tried to connect it to the "Allow location" Android screen as much as possible.

Allow location sharing
If you don't allow Ground to access this device’s location, you won’t be able to continue collecting data for this site.
[Exit] [Allow location]

![Image](https://github.com/user-attachments/assets/6495821f-679a-45f5-94ab-dd28dfb6a82d)

**Comment by gino-m** [comment]
Back to you @anandwana001 !
