### ISSUE TITLE
Surveys with neither Free-form data collection nor Predefined sample sites; only Capture location

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2675]
Hi,

following up on yesterday's discussion the idea came to mind that it could be useful to have surveys where **"Capture location"** is the only possible way to record geodata.

It would probably be advantageous in many surveys to only allow collectors to create a point right on the spot, e.g. in field campaigns where every plot is visited individually and collectors are asked to go to the center of the plot. 
(Ideally including a GPS accuracy threshold as suggested in https://github.com/google/ground-android/issues/2565).

Currently it is possible to select neither **Free-form data collection** nor **Predefined sample sites** when creating a new job, but just continue and add **"Capture location"** as a task. However, opening it in the Android app, it says "Survey is read-only".

![image](https://github.com/user-attachments/assets/3aeb80ba-f2dd-4e27-9aa7-67839e00a49e)

**Comment by jo-spek** [comment]
This is less about the error and more about changing the current "Capture location" class from being one of the added survey tasks to instead being one of three geolocating options alongside Free-form polygon collection and Free-form point collection. In this one the thresholding could be implemented (but not in the others).

**Comment by gino-m** [comment]
> This is less about the error and more about changing the current "Capture location" class from being one of the added survey tasks to instead being one of three geolocating options alongside Free-form polygon collection and Free-form point collection. In this one the thresholding could be implemented (but not in the others).

I see. Would merging "Capture location" and "Drop pin" tasks address this?

**Comment by gino-m** [comment]
Let's pick this up in a meeting.

**Comment by jcqli** [comment]
This should be fixed on the web side, tracked in https://github.com/google/ground-platform/issues/1667 and https://github.com/google/ground-platform/issues/1798 which are both fixed. Going to close this one out
