### ISSUE TITLE
[Media upload] Upload stuck on "Media uploading" when returning from Airplane Mode

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2678]
This occurred on emulated Pixel 4. Repro steps:

1. Open survey
2. Enable Airplane Mode
3. Complete data collection flow for new site which includes photo task
4. Kill the app
5. Turn on Airplane Mode
6. Wait for data to be uploaded (check web app)
7. Open the app
8. Click "Data sync status"

Note that upload is stuck.

**Comment by shobhitagarwal1612** [comment]
While testing this, I found that the images are stored at incorrect path in firebase storage.

e.g.

```
user-media/surveys/SURVEY_ID/submissions//storage/emulated/0/Android/data/com.google.android.ground/files/Pictures/filename.jpg
```

**Comment by anandwana001** [comment]
Duplicate https://github.com/google/ground-android/issues/2689

@shobhitagarwal1612  we can close this, as per our discussion
