### ISSUE TITLE
Settings Screen - Upload Media Toggle reset after orientation changes

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2681]
**Describe the bug**
In Settings Screen, the toggle switch gets reset after the screen orientation gets change.

**To Reproduce**
1. Go to Settings
2. Click on Upload Media Toggle Switch
3. Change Orientation
4. Toggle Switch gets reset

**Expected behavior**
It should remember the toggle switch state

**Actual behavior**
orientation is not remembering the last state

**Screenshots**

https://github.com/user-attachments/assets/874dfea3-62fb-42d6-99c2-1d6834aadff4

**Comment by gino-m** [comment]
Nit: "Upload Media" -> "Upload photos"
