### ISSUE TITLE
If no surveys to fill out, back arrow in survey list is a no-op

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2692]
After logging in to the app, if there are no surveys for you to collect data for then the back arrow does not do anything

![Image](https://github.com/user-attachments/assets/1a3142d8-f8b3-4b08-8eb3-99342f2863a0)

**Comment by anandwana001** [comment]
Bit more detail 

1. For the very first time, the back arrow clicked, it recreates the fragment 
2. arrow click doesn't work


https://github.com/user-attachments/assets/993612c1-e4be-4c00-a3e0-4a31aaae27d3

**Comment by shobhitagarwal1612** [comment]
> What should be the expected behavior?

It should exit the app

**Comment by jcqli** [comment]
Hm exiting the app seems like an antipattern, are there other apps that do this? The current behavior for when there are surveys in the list is to sign to user out so maybe we should match that

**Comment by gino-m** [comment]
+1 @jcqli. The current design is obsolete, perhaps at this point it's just better to update the UI as per the new designs?

@rawbzz Can you paste in the latest here?

**Comment by gino-m** [comment]
New design includes the hamburger icon. Users can sign out from there if they have no surveys.

![image](https://github.com/user-attachments/assets/053aac00-618f-4957-83fd-5f1a4c6277e9)

@kenstershiro @rawbzz FYI

**Comment by anandwana001** [comment]
> New design includes the hamburger icon. Users can sign out from there if they have no surveys.

@gino-m So, user can able to open the drawer and able to explore the whole app, right? Or do we need to show only signout in the drawer?

**Comment by gino-m** [comment]
> > New design includes the hamburger icon. Users can sign out from there if they have no surveys.
> 
> @gino-m So, user can able to open the drawer and able to explore the whole app, right? Or do we need to show only signout in the drawer?

Yes, except the "Data sync status" option will be disabled:

![image](https://github.com/user-attachments/assets/da0b3854-b205-4dc9-afbe-d27b5c55465f)

**Comment by anandwana001** [comment]
@shobhitagarwal1612 
for this issue, we need to move our drawer layout from fragment to activity, as it is a good practice to let every fragment access the drawer.

Could you please confirm this approach, as this is bit sounds like a migration?
All the drawer responsibilities should be handled by main activity and its ViewModel and HomeScreenFragment and it's Viewmodel will only see the maps and all

**Comment by shobhitagarwal1612** [comment]
Let's prototype it once to understand the potential challenges we might face while doing this migration.

**Comment by anandwana001** [comment]
As per the last discussion with @shobhitagarwal1612 the plan from here is to sub-divide this issue:

1. Jetpack Compose Migration #2803 
2. Once the Migration completes, Introduce Navigation Drawer in the MainActivity and remove from HomeFragment
