### ISSUE TITLE
Address TODOs in proto converters

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2717]
After the proto migration, there are several TODOs outstanding in the proto converters related to inconsistency in some proto fields. Need to go through them and address them (remove, fix, document).

- [x] Add "skipped" field in taskData when the value is missing or task is skipped
~~Add "timestamp" in CaptureLocationResult~~
- [ ] Replace "isPredefined" with "Source" in LOI model.
- [ ] Rename "customId" to "customTag" in LOI model.

For full list of tasks, please refer to this [sheet](https://docs.google.com/spreadsheets/d/1Ognh710debgAEI01Z2qvl-jAIfOoxnH6O8z4npiL9_g/r/0-ZZ16BvSYLPvARlghXBtX4A/edit?gid=0#gid=0)

**Comment by jcqli** [comment]
FYI @shobhitagarwal1612 based on standup today

**Comment by shobhitagarwal1612** [comment]
@gino-m I've audited all proto converters when submitting data and added them to the below sheet. Please let me know your thoughts on whether we need these or not?

https://docs.google.com/spreadsheets/d/1Ognh710debgAEI01Z2qvl-jAIfOoxnH6O8z4npiL9_g/r/0-ZZ16BvSYLPvARlghXBtX4A/edit?gid=0#gid=0

**Comment by gino-m** [comment]
@shobhitagarwal1612 Answers in the sheet. HTH.
