### ISSUE TITLE
Card "Add data collection site" does not appear

### ISSUE THREAD

**Issue by jo-spek** [google/ground-android#2727]
As described by @jabramowitz5 yesterday, multiple collectors in the field in Ghana did not find the card "Add data collection site" appearing when zooming in, whilst other collectors did. All of them were participating in the same survey.

On my personal Android Device (Xiaomi Poco X3 NFC, Android 12 SKQ1.211019.001) in that same survey the card sometimes appears and disappears, with issues of moving the map (see https://github.com/google/ground-android/issues/2728).

I think this partially relates to the crash report under https://github.com/google/ground-android/issues/2725.

**Comment by jo-spek** [comment]
Copied from Google chat from @jabramowitz5 for some added context:

_could it be related to the app cache? For one user, they were not seeing the "add new data collection site" card, then they force stopped the app, then cleared their cache for Open Foris Ground app, then reopened app and the "add new data collection site" card appeared for them ... but that process does not seem to be working for everyone_

**Comment by jcqli** [comment]
Adding from notes that this was happening on the cloned survey

**Comment by jo-spek** [comment]
> Adding from notes that this was happening on the cloned survey

It happened on both, the original and the cloned survey. However, for me personally it only happened on the cloned survey.

**Comment by gino-m** [comment]
Closed by #2740

**Comment by gino-m** [comment]
Fixed by #2740. @jabramowitz5 can you please add the "verified" label to this issue if this works once users remove and reopen their surveys without clicking the survey multiple times?
