### ISSUE TITLE
Showing Raw Terms of Service Text 

### ISSUE THREAD

**Issue by anandwana001** [google/ground-android#2732]
![WhatsApp Image 2024-09-18 at 07 32 11](https://github.com/user-attachments/assets/a96872fa-68ac-46c4-9c99-40669fc050ec)

**Comment by gino-m** [comment]
The problem is actually in the config - the terms of service don't contain Markdown, but `#NEWLINE#` for new lines. 

@rfontanarosa Doesn't the web interface already support Markdown for ToS? If so, can the ToS be updated to use Markdown?

**Comment by anandwana001** [comment]
@rfontanarosa Gentle Ping
