### ISSUE TITLE
Lost datapoint

### ISSUE THREAD

**Issue by n-clinton** [google/ground-android#2738]
I collected a datapoint, named it, saved it.  Then it was gone.

I see a mystery point on the Data sync status screen.  But I don't know how to check to see if it's missing point or delete it.

**Comment by gino-m** [comment]
> I collected a datapoint, named it, saved it. Then it was gone.
> 
> I see a mystery point on the Data sync status screen. But I don't know how to check to see if it's missing point or delete it.

@n-clinton What was the sync status on that point? "Edit/delete" wasn't a priority for the project sponsors so it wasn't implemented.

**Comment by gino-m** [comment]
> I see a mystery point on the Data sync status screen. But I don't know how to check to see if it's missing point or delete it.

Also, does the name you gave the point appear on the sync status screen? Could you please share a screenshot?

**Comment by gino-m** [comment]
@n-clinton I pinged you. I suspect #2740 fixes this, but @rfontanarosa still needs to cut a release. In the meantime, would you able to try the workaround I sent on chat?

**Comment by jcqli** [comment]
@n-clinton we just made a release, could you let us know if it's still reproducible? v 0.1.10

**Comment by gino-m** [comment]
@n-clinton We discussed - turned out that the actual GPS location wasn't the main geometry for that site. I've proposed https://github.com/google/ground-platform/issues/2075 to make this scenario less likely, closing this for now.
