### ISSUE TITLE
Wrong location on datapoint

### ISSUE THREAD

**Issue by n-clinton** [google/ground-android#2739]
Collect a point in the field, name it, save it.

When I get to the office, check the point.  Wrong location.  Looks to be the location where the phone first gained signal again after collecting the point.

I see two points that are "Media syncing" on the Data sync status page, but now way to check whether one of them is the point in question.  Also, no way to delete the wrong point?

**Comment by gino-m** [comment]
Did you collect the point with the "Capture location" feature, or "Drop a pin"?

**Comment by gino-m** [comment]
@sufyanAbbasi How is this possible? I see `updateResponse()` is called synchronously in `CaptureLocationTaskViewModel` on "Capture" button click. `CaptureLocationTaskData` is mutable, so it seems impossible.

@n-clinton Can you share the URL of the point in the web UI?

**Comment by gino-m** [comment]
We chatted. @n-clinton's point is that the app shouldn't allow the pin to be dropped so far from the user's actual location.

I would argue that not needing to be physically present is a feature, not a bug. That said, we should add a feature allow organizers to limit how far users can be when adding a location manually.

This brings us back to the idea of always capturing location, even on manually added pins (see discussion on #2736). I  propose the solution described in https://github.com/google/ground-android/issues/2736#issuecomment-2364583147.

**Comment by gino-m** [comment]
I can't reproduce this issue on dev. Let's continue the discussion on #2736.
