### ISSUE TITLE
[Data collection flow] Text field not restored from draft 

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2753]
...and user is returned to previous (add polygon LOI) task:

[Screen_recording_20240920_170944.webm](https://github.com/user-attachments/assets/390fed69-843b-4045-bf26-042c5f1001d2)

**Comment by anandwana001** [comment]
This PR https://github.com/google/ground-android/pull/2720 is fixing this issue

**Comment by anandwana001** [comment]
https://github.com/user-attachments/assets/e9fc0979-705a-41f0-bab2-c751a2c2e630



Closing as this is working now
