### ISSUE TITLE
[UX Bug] Data submitted confirmation shown as modal

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2809]
As per UX designs, confirmation should be shown inline with no ability to go back to previous step:

![Image](https://github.com/user-attachments/assets/cc573bf5-119d-475f-991d-9996d2541ea2)

**Attribution should also be shown**

Follow-up to https://github.com/google/ground-android/issues/2798

@anandwana001 @rawbzz FYI

**Comment by anandwana001** [comment]
@rawbzz Required the Landscape design for this screen

**Comment by rawbzz** [comment]
I think this one can just go side by side like this !
![Image](https://github.com/user-attachments/assets/ac054bed-6f90-48bc-9552-d4366deb6667)
