### ISSUE TITLE
[Geometry data collection tasks] Geometry sometimes not visible on map when returning to task

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2847]
This occurs when the viewport is updated after the task is complete, usually by a subsequent geometry task. Returning the the previous task, the viewport of the previous map is restored, which doesn't necessarily have the collected geometry in focus.

Instead, if the task already has data, we should set the initial viewport to the bounds of the geometry, perhaps one zoom level up (Z-1).

https://github.com/user-attachments/assets/baec0821-c934-4ddf-a8f0-31c543b4d732

![Image](https://github.com/user-attachments/assets/442c2be9-0aa1-4fd9-936c-81e2c37730b3)

@kenstershiro @lecrabe @jabramowitz5 @anandwana001 FYI

**Comment by shobhitagarwal1612** [comment]
I'm unable to repro this locally. 
@gino-m Can we sync once for this issue?

**Comment by himanshukar** [comment]
the geometry should be cached in the data store with session token.
