### ISSUE TITLE
[Code health] Clean up `SurveyConverter.toSurvey()`

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2857]

**Comment by shobhitagarwal1612** [comment]
@gino-m Can you please add more details to this bug?

**Comment by gino-m** [comment]
> [@gino-m[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/gmiceli@google.com)](https://github.com/gino-m) Can you please add more details to this bug?

Sorry I didn't provide more details when I wrote this, but I think @2939 likely addresses what I had in mind.
