### ISSUE TITLE
[Data collection form] UI bugs in multiple choice selectors

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#2893]
- [ ] Horizontal dividers are missing
- [ ] The incorrect text field style is used in the "Other" field
- [ ] The "Other" text is shown again above the text "Other" field
- [ ] The font styling of the question and response options is incorrect

Actual:

![Image](https://github.com/user-attachments/assets/11577ea8-25d8-4436-ad23-e86488b48dab)

Expected:

![Image](https://github.com/user-attachments/assets/e0c978be-f123-4a63-a06f-abb04ee9e3af)

@shobhitagarwal1612 Do you have bandwidth for this fix?

**Comment by shobhitagarwal1612** [comment]
Sure, will take a look.
