### ISSUE TITLE
https://github.com/google/ground-android/issues/187#issuecomment-571411466

### ISSUE THREAD

**Issue by kh0kv** [google/ground-android#296]
https://github.com/google/ground-android/issues/187#issuecomment-571411466

**Comment by kh0kv** [comment]
https://github.com/google/ground-android/issues/187#issuecomment-571411466

**Comment by gino-m** [comment]
Was this posted in error? If you meant to file a feature request or bug, please use one of the templates available at https://github.com/google/ground-android/issues/new/choose.
