### ISSUE TITLE
[Auth] Mutations should be written to server using token of initiating user

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#299]
Currently this is done in the background worker by the currently logged in user.

**Comment by scolsen** [comment]
(to persist associations between users and mutations)

**Comment by scolsen** [comment]
@gino-m any clarification around this? We currently write and use the user that authored the mutation, but it's not clear to me yet if/where we check that this user has permissions to mutate the target object

**Comment by gino-m** [comment]
> @gino-m any clarification around this? We currently write and use the user that authored the mutation, but it's not clear to me yet if/where we check that this user has permissions to mutate the target object

Unless something changed, it's the token of the currently authenticated user that is used to do server writes. Even if the current user changes and still has write permission, it's obviously incorrect to write using a different principal than the one taking the action. That said, storing and refreshing per-user tokens is likely out of scope of our first release. 

Perhaps for now we can instead show a Big Scary Warning when users sign out and delete any pending mutations in the local db?

**Comment by scolsen** [comment]
Got it, that sgtm! Going to bump this down in priority for now and open a separate issue.

**Comment by gino-m** [comment]
Mutations are now removed when the user signs out, so there's no risk of the wrong user performing sync.
