### ISSUE TITLE
[Offline base map] Select and Download Offline Areas

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#308]
- [ ] Provide a selector UI for users to select regions of the map for offline viewing.
- [ ] Download selected offline areas to the device in the background.
- [ ] Notify users of download failures.
- [ ] Resume interrupted downloads. 

Related: #10 #20

@gino-m FYI

**Comment by shobhitagarwal1612** [comment]
Is it possible to show required space before the download starts? I ran out of space on my emulator while testing out this feature a couple of times. Then once we have a settings page, we can also show the total space occupied by the offline areas. Thoughts?

**Comment by gino-m** [comment]
@shobhitagarwal1612 this is planned, but just realized there wasn't a bug for it. Filed https://github.com/google/ground-android/issues/433 to track.

**Comment by gino-m** [comment]
@scolsen marking this one closed since we effectively now have this functionality working. Please cmiiw!
