### ISSUE TITLE
[Feature] Integrate Firebase Storage for uploading photos

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#310]
https://firebase.google.com/docs/storage/android/start

Add capability to upload photos to firebase storage.

- [x]  Prototype uploading images to Firebase Storage

- [x] Create new Field type, ‘photo’ - plumb through data model and local and remote persistence

- [x] UI for uploading photos / show thumbnails

- [x] Add storage runtime permissions

- [x] Capture photos / Select from local storage

- [x] Upload selected/captured photo to Firebase Storage

- [x] Fix storage path for the uploaded media

- [x]  Add photo field type to EditObservationFragment that allows photos to be uploaded, store on local device and db

- [x] Update EditObservationFragment to allow user to select existing images (and video if it’s easy), or to trigger camera to capture a new one using StaX design for inspiration. 

- [x] Store image path and uuid locally (in Observation and ObservationMutation).

- [x]  On remote sync of the relevant ObservationMutation, write photo to storage

- [x] Write photo to remote storage in LocalMutationSyncWorker.

- [x]  Update ObservationDetails to show tiny thumbnail of photo (tiny because this will eventually be moved to the observation list)

- [x] Use RxJava to broadcast upload state across the application for UI updates

- [ ]  Allow removing uploaded photo in relevant EditObservationFragment fields

- [ ] Add support for PHOTO field type to the form designer in the web client

- [x] Create mutation table for sync queue and merge with DataSyncWorker

Storage path:
Root > Uploaded Media > Project > Layer > Observation Id > [field no + element no]

**Comment by gino-m** [comment]
@shobhitagarwal1612 FYI:

Select photo UI:
![image](https://user-images.githubusercontent.com/228050/76426508-8b773d80-6381-11ea-90e5-09a89fce82bf.png)
(except link should say "ADD PHOTO", show in application accent color)

Thumbnail:
![image](https://user-images.githubusercontent.com/228050/76426684-c4171700-6381-11ea-8d5a-d41af06148f2.png)
Shown immediately below field label.

**Comment by gino-m** [comment]
@shobhitagarwal1612 I think this is done? Please reopen if not.
