### ISSUE TITLE
[CI] Checkstyle fails on google_maps_api.xml

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#336]
Error:
Missing a header - not enough lines in file.

@shobhitagarwal1612, do we need to set up checkstyle to explicitly ignore  local-only files?

**Comment by shobhitagarwal1612** [comment]
There is already an `excludes` section in checkstyle.gradle

https://github.com/google/ground-android/blob/master/config/checkstyle/checkstyle.gradle#L44

**Comment by gino-m** [comment]
Thanks! Actually I just realized `google_maps_api.xml` is obsolete, replaced with `secrets.properties`; I had an old copy on my work laptop, and was confused because we still mention it in `AndroidManifest.xml`.
