### ISSUE TITLE
[Feature sheet] Special treatment for layers with no observation form

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#354]
Consider reducing height of feature sheet or showing a message when no form is defined for a layer.

**Comment by gino-m** [comment]
@sergeydolgov1 Is it ok to show an empty feature sheet with the "+ Add observation" button disabled for layers with no form? (i.e. reference layers)? Or should this case get a special UI treatment? If so, is this something for MVP or release?

**Comment by sergeydolgov1** [comment]
@gino-m Suggest two potential flows depending on whether Adding new observations is enabled (have a form) or disabled (no form available)

- **[If Adding new observations enabled]** Empty Feature sheet has "There are currently no observation for this Point, you can add observation by tapping "Add Observation" button below" at the top

- **[If Adding new observations disabled ]** Empty Feature sheet has "There are no observation for this Point, adding observations for (Name) layer is disabled by Project owner " at the top. "Add observation button" is enabled but after tapping on it user sees a small modal dialog saying "Adding observations for (Name) layer is disabled by Project owner" with  "Ok" button to dismiss modal dialog

Suggest we add it to Release and for the pilot recommend to create a form (even with a single field) for each layer

**Comment by gino-m** [comment]
Flagged for inclusion in RC.

For layers where adding observations are disabled, perhaps we should hide the Add observation button all together? 

Also, one alternative to showing the descriptive text in the observation list could be to show a modified UI for these layers, e.g. showing a small card at the bottom of the map as is done in Google Maps?

**Comment by gino-m** [comment]
We will no longer allow jobs without tasks.
