### ISSUE TITLE
[Map] Visualize line and polygon map features

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#357]
These will be represented as GeoJSON in the db.

This involves:
- [ ] Reading GeoJSON from remote db
- [ ] Storing GeoJSON in local db
- [ ] Show lines and polygons on the map.

@daoyut could you kindly ping an example of the format used here?

**Comment by DaoyuT** [comment]
Example of the GeoJson to render https://storage.googleapis.com/mapsdevsite/json/google.json

**Comment by gino-m** [comment]
Duplicate of #534.
