### ISSUE TITLE
[Add polygon] Implement polygon drawing flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#358]
Click to see mock of full flow. Thanks @coreyleamon for the design!
![Option 4](https://user-images.githubusercontent.com/228050/111845304-f33c5e80-88da-11eb-9dd1-0162906d406a.png)

**Comment by sergeydolgov1** [comment]
Prioritized drawing a polyline (Lines + Polygons) for RC1. Latest mocks below:

![image](https://user-images.githubusercontent.com/20148684/89821845-18c2e780-db04-11ea-8c31-b07b0fdfb8e0.png)

![image](https://user-images.githubusercontent.com/20148684/89821861-211b2280-db04-11ea-9f66-85103f5ca9b7.png)

**Comment by gino-m** [comment]
Misplaced comment moved to https://github.com/google/ground-platform/issues/251#issuecomment-676608382.

**Comment by gino-m** [comment]
Hi @HemanParbhakar, based on our discussion today, I've been thinking about a remote db representation for polygons that will also be extensible to upcoming features.

I'd suggest encoding polygons in feature documents in Firestore by adding a field called `geometry` which will use GeoJson structure for polygons. In that case, a polygon feature in the db might look like:

```
{
  "featureId": "feature321",
  "layerId": "layer123",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [0, 0], [10, 10], [10, 0], [0, 0]
      ]
    ]
  }
}
```

See https://macwright.com/2015/03/23/geojson-second-bite.html#geometry for a nice explanation of GeoJson geometries. You probably won't want to model the entire GeoJson structure in `FeatureDocument`, in which case it's ok to use `Map<String, Object>`, which you should also be able to obtain from the JSONObject.

In a follow-up, we may refactor the `Feature` subclasses to make more sense (e.g., making a distinction between imported GeoJson and KML base layers vs features), but for now we can keep them in memory in the new `PolygonFeature` class as a `ImmutableList<Point>` as discussed.

No change to local db as per discussion, comma separated list of pairs is fine.

Please let me know if you have any questions!

**Comment by gino-m** [comment]
Discussed splitting into smaller PRs. Suggested split, change one application layer per PR:

1. Update model
2. Update local db entities
3. Update remote document
4. Implement load from remote db (incl. converters and unit tests)
5. Implement save to local db (")
6. Implement load from local db (")
7. Display loaded polygons on map (")
8. Implement polygon drawing UI (incl. unit tests for ViewModel)
9. Implement storing mutations to local db (incl. converters and unit tests)
10. Implement syncing mutations to remote db (")

**Comment by gino-m** [comment]
Pending issues from #968:


- [ ] Padding and spacing of "Get started" dialog incorrect:
  ![image](https://user-images.githubusercontent.com/228050/131730805-630aeca6-7c16-4f34-bd07-748b48013944.png)
- [ ] Line between last vertex and crosshairs is not visible while dragging map in drawing mode as expected:  
  ![image](https://user-images.githubusercontent.com/228050/131731052-fbc5c702-b344-45f7-8fa4-6b41a6c57a09.png)
- [ ] Vertex markers are only shown on first and last vertex, not all as expected. 
![image](https://user-images.githubusercontent.com/228050/131730962-74f45ff9-e245-40f8-98e9-5bd9d81552e9.png)
- [ ] "Get started" dialog is shown every time a polygon is added; it should only be shown the first time a user adds a polygo.
- [ ] Button style incorrect, buttons not top aligned:
  ![image](https://user-images.githubusercontent.com/228050/131730368-75b83845-570a-4d8f-8f9c-7f9eead8af82.png)
- [ ] It's not possible to close the polygon at lower zoom levels (zoomed out). This is because the threshold for overlap with last vertex is "m" and not pixels. To solve this, the threshold can be adjusted depending on the zoom level.
- [ ] After overlapping the crosshairs with the first vertex, the "Complete" button is shown as expected, but panning away from the first vertex does not restore the "Add point" button.
  ![image](https://user-images.githubusercontent.com/228050/131731455-8ec8d797-ec28-471b-bc96-9f3fefbfc231.png)

Could you please prepare a separate PR for each of these?

**Comment by shobhitagarwal1612** [comment]
Can we close this?
