### ISSUE TITLE
[Drop a pin] Make "drop a pin" task flow more intuitive

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#360]
The current "add feature" flow doesn't work well for polygon drawing, since the user will need to select the layer _before_ drawing the polygon. It's also surprising that a point gets added immediately after selecting the layer, without any prompt to select location.

The current flow:

1. Drag map to desired location
1. Click "+" fab
1. Select layer from popup
1. Feature is added to map and feature sheet is shown.

Desired flow:

1. Click "+" fab
1. Select layer from popup
1. Select feature type (point/polygon) if applicable. 
1. Map switches to "adding" mode, with "Drag map to desired location", "ADD", and "<-" actions in header. "+" button is disabled while in this mode.
1. On "ADD", feature is added to map and feature sheet is shown.

**Comment by sergeydolgov1** [comment]
@gino-m Should we merge this issue with #114?
[](https://github.com/google/ground-android/issues/114)

**Comment by gino-m** [comment]
@ngosue FYI

**Comment by scolsen** [comment]
@shobhitagarwal1612 assigning to you to check on the current state of this. Can we close this now that we've implemented the drop a pin task?

**Comment by shobhitagarwal1612** [comment]
We left it after the basic implementation as the UX wasn't finalised. Depending on that, we might have to make some changes here.

**Comment by gino-m** [comment]
Closing legacy issue.
