### ISSUE TITLE
[Feature sheet] Reenable map interactivity in feature sheet

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#362]
We previously locked the map when the sheet is expanded so that they user would always have context about the currently selected feature.  While demoing the prototype, we noticed users often try to tap other markers visible on the map or try to pan, are they're often surprised this doesn't work. Some ideas for a better solution:

- [ ] Do not [un]lock the map when sheet is expanded/collapsed
- [ ] On zoom or pan, collapse the feature sheet
- [ ] When a different map feature is tapped, rerenderr the feature sheet with the details for that feature

**Comment by gino-m** [comment]
@sergeydolgov1 Do you think is important to do for pilot?

**Comment by sergeydolgov1** [comment]
@gino-m I think this is a nice-to-have UX improvement. Suggest we deprioritize it for pilots and add it to RC. Will add this to the list of question to validate during pilots
