### ISSUE TITLE
[Map] Enlarge marker of selected LOI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#363]
It's currently difficult to understand which marker is selected.

Suggestion:
![image](https://user-images.githubusercontent.com/228050/74393841-34f5fe00-4dd9-11ea-916e-fbd9bcd385f3.png)

**Comment by rscottcarson** [comment]
Is this available to be worked on?

**Comment by shobhitagarwal1612** [comment]
Hello @rscottcarson and welcome to the project.
Yes, this is up for grabs. Please feel free to ask questions if you need any kind of help!

**Comment by gino-m** [comment]
@rscottcarson Thanks for taking this on! You may need to do a small update to the interface of our map adapter, the layer that abstracts the details of Google Maps API away from the application. As @shobhitagarwal1612 says, please feel free to ask us anything!

**Comment by SamarthAsthan** [comment]
@shobhitagarwal1612 @gino-m Is this issue still there? and if so can i work on it

**Comment by gino-m** [comment]
Sure, but you may want to wait until the big rename we're undergoing is complete in a week or so. Then you'll be able to stand up the web interface to create a survey.

Would you like to start by sending a draft PR with a rough sketch of what you had in mind?

You'll probably want to expose methods to set and clear the selected `LocationOfInterest` (LOI). 

Note that `MarkerIconFactory` already scales the icon based on zoom level, you can probably reuse the same approach for the selected LOI.

**Comment by gino-m** [comment]
@shobhitagarwal1612 @JSunde Was this resolved?

**Comment by shobhitagarwal1612** [comment]
Yes, this one was fixed by @scolsen
