### ISSUE TITLE
Automatically run code checks locally

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#374]
From comment https://github.com/google/ground-android/pull/370#pullrequestreview-359936471

- Run code check on commit instead 
- Realtime warnings in Android Studio (probably by using a plugin)

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612! Are we abandoning this one in favor of running checks manually, if I recall? If so we can close it.

**Comment by shobhitagarwal1612** [comment]
Can we reduce the priority to `p3` and mark it has `help needed`? Let's keep it open so we don't forget about it and re-visit it again sometime in future. Wdyt?

**Comment by gino-m** [comment]
Updated - also updated the description to be more broad, since we're not sure what the best solution is yet.

**Comment by anandwana001** [comment]
@shobhitagarwal1612 
Do we need any pre-commit analysis?

**Comment by shobhitagarwal1612** [comment]
I think it's a "good to have" feature but can leave it for now in favor of other high priority tasks.

**Comment by gino-m** [comment]
@anandwana001 We experimented with this awhile back and the latency introduced by the checks had a negative impact on developer velocity. I agree with @shobhitagarwal1612 we should punt on this.
