### ISSUE TITLE
spotbugs sometimes eats PMD and/or compile errors

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#377]
This may be due to other build issues (compile? PMD?) that cause there to be no classes generated, but spotbugs is being run anyway, masking the error.

**Comment by gino-m** [comment]
Shobhit and chance you could take a look at this or advise how to fix?

**Comment by dturner** [comment]
Ran into this issue as well. Then pulled down #376 and it went away.

**Comment by gino-m** [comment]
Let's see if building and running `checkCode` in separate steps helps. Note that `checkCode` target runs other all other post-build code checks (PMD, spotbugs, etc).

**Comment by shobhitagarwal1612** [comment]
Can be closed since we no longer run this check automatically
