### ISSUE TITLE
[View/edit observation] Improved toolbar header and breadcrumb

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#378]
Header currently shows the name of the current layer. Some improvements:
- [x] Vertically center toolbar header
- [ ] Show "Add/view/edit observation" for context
- [ ] Better treatment of layer name (show marker as well?)
- [ ] For View/edit, show creator and creation timestamp?

**Comment by sergeydolgov1** [comment]
This is how toolbar header looks today:
![image](https://user-images.githubusercontent.com/20148684/86301921-06c45f80-bbbc-11ea-9022-1b1bb167f1c0.png)

**Comment by gino-m** [comment]
That's actually the feature details sheet; this issue referred to what's shown when you're viewing or editing an individual observation.

**Comment by sergeydolgov1** [comment]
@gino-m thanks for correcting me. Updated screenshot:
![image](https://user-images.githubusercontent.com/20148684/86440440-4cb61c00-bcbf-11ea-8250-4754aee09e9e.png)

**Comment by sergeydolgov1** [comment]
@gino-m 
- It seems that the Toolbar header is already centered
- User is already viewing observation and we have "Edit" in the ellipsis
- Point marker is not necessary at this stage

Suggestion:
- Show Creator name and timestamp at the bottom of the sheet

**Comment by gino-m** [comment]
Thanks for the comments! 

> It seems that the Toolbar header is already centered

Good catch!

> User is already viewing observation and we have "Edit" in the ellipsis

"Edit" is an action to allow the user to switch from "View" to "Edit" screens; the point of this Issue was that it might not really be clear what the user is looking when they're in View mode - i.e. that they're viewing a single observation associated with a feature in a particular layer. I was fishing for better ways of providing clear context.

> Point marker is not necessary at this stage

Sgtm.

**Comment by sergeydolgov1** [comment]
> > User is already viewing observation and we have "Edit" in the ellipsis
> 
> "Edit" is an action to allow the user to switch from "View" to "Edit" screens; the point of this Issue was that it might not really be clear what the user is looking when they're in View mode - i.e. that they're viewing a single observation associated with a feature in a particular layer. I was fishing for better ways of providing clear context.

Ok, I see. "Breadcrumb" can be a potential way to show users where they are. Perhaps we can add this question to the list of things we are going to test/validate, no actual Eng work at this stage?

**Comment by gino-m** [comment]
Sgtm! Created #535 to track. Please add other open qs there as well!
