### ISSUE TITLE
[Feature] After opening a project the map should focus on the project area

### ISSUE THREAD

**Issue by dturner** [google/ground-android#382]
Currently when you open a project the map opens on Mali (presumably this is the centre point on a world map). It would be good if the map opened where the project was located e.g. zoomed in on any location pins on that map - that would save the user having to scroll and zoom to find their project's location.

**Comment by gino-m** [comment]
Our current assumption is that users will be mostly in the place where they will be collecting data. I thought I had file a bug about this but I can't find it; I probably only added a TODO in the code. Filed #383 to track.

**Comment by gino-m** [comment]
Closing this issue since it's roughly a dupe of #383.
