### ISSUE TITLE
FAB button is greyed out even after selecting a project

### ISSUE THREAD

**Issue by dturner** [google/ground-android#388]
**Describe the bug**
After selecting a project the FAB button on the home screen remains greyed out

**To Reproduce**
- Load ground app
- Choose a project

**Expected behavior**
FAB button changes color (green IIRC) and becomes active

**Actual behavior**
FAB button stays greyed out and does nothing when you tap on it

**Screenshots**
![image](https://user-images.githubusercontent.com/873212/76530624-e5543200-646b-11ea-9e1f-b9e535689a76.png)

**Comment by gino-m** [comment]
Can you repro with the latest at HEAD?

**Comment by dturner** [comment]
Fixed with latest HEAD. Apologies, must remember to `git pull` regularly!
