### ISSUE TITLE
[View/edit observation] Order of fields not consistent

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#396]
**To Reproduce**
1. Select "Plastic Frog Finder" project
2. Click on "+" to add observation

**Expected behavior**
Photo field should be at the last 

**Actual behavior**
Photo field is at position 3 

**Screenshots**
![image](https://user-images.githubusercontent.com/8918023/76799622-e2ed3180-67f7-11ea-8b1a-b0b54e060094.png)

**Comment by gino-m** [comment]
This will probably be fixed once we switch from semantic ordering (legacy schemas) to index-based ordering of form elements.
