### ISSUE TITLE
[AppFeatureNameHere] Improve UI for observation list in FeatureSheet

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#405]
Current state:
A list of observations along with the code of filled values are displayed (not all because of space constraints)

Displaying the value code doesn't look human friendly. Also, this cannot display all fields for longer forms.

Is there a better way to represent it? Some possible ideas:
 - Hide all field label / values
 - Only show total no of answered fields
 - Add an avatar or gmail dp of logged in user

![image](https://user-images.githubusercontent.com/8918023/77154292-6b522780-6ac1-11ea-8f7e-a76184a4aa79.png)

**Comment by gino-m** [comment]
Agreed.. we're planning to address this in #352. Let's continue discussion there!

Note - please be sure to replace "AppFeatureNameHere" with the name of the feature in question when creating issues.

**Comment by shobhitagarwal1612** [comment]
Thanks!
