### ISSUE TITLE
[Offline sync] Allow user to specify connection types required for syncing

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#408]
Allow user to enable "Wait for Wifi" for: Photos, Uploading observations, Downloading new features (wording and UX TBD). @coreyleamon FYI.

**Comment by sergeydolgov1** [comment]
Current Implementation:
![image](https://user-images.githubusercontent.com/20148684/86302729-6d4a7d00-bbbe-11ea-91ab-cad41c61624f.png)

**Comment by sergeydolgov1** [comment]
@shobhitagarwal1612 -- Do we need UX help on this?

**Comment by shobhitagarwal1612** [comment]
@gino-m has a question for you regarding the same in the PR. https://github.com/google/ground-android/pull/506#discussion_r447037477. Could you please take a look?

**Comment by gino-m** [comment]
I can't find that question now, but I think it was related to the language show in the UI - "WiFi" vs "Unmetered". Although the UI says "Only upload photos over WiFi", it really means "over an unmetered connection". This usually means Wifi but not always.

My opinion here is that "unmetered" may be too abstract for beginner users, but I'm may be wrong. I see apps like Photos use "Wifi", I believe as an approximation of "Unmetered" connection.

**Comment by gino-m** [comment]
@sergeydolgov1
