### ISSUE TITLE
[Code health] Decide whether to use OneTimeWorker in WorkerManager

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#409]
From https://github.com/google/ground-android/pull/404#pullrequestreview-378776788

@gino-m - "One note - it's not clear to me if we'd want to use one OneTimeWorker for each photo, or a single worker enqueued with enqueueUniqueWork and a queue in the db. The latter may be useful for having more control over the queue and tracking progress."

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612 , iirc we addressed using a single worker that will process the queue to completion. Closing now, but please cmiiw.

**Comment by shobhitagarwal1612** [comment]
Yes, it is fixed now.
