### ISSUE TITLE
[Photos] When editing observation, photo doesn't load from local storage

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#415]
**Describe the bug**
Photo field should be updated in EditObservationFragment after adding a photo, even if we are offline

**To Reproduce**
1. Turn off wifi/data
2. Create a new observation with photo field (e.g. FROGS)
3. Add a photo

**Expected behavior**
Thumbnail should be updated using the local stored photo

**Actual behavior**
Thumbnail doesn't update

**Comment by gino-m** [comment]
@shobhitagarwal1612 Thanks for tracking this! be sure to update or remove "Describe the bug" in the template when filing and to assign priority. Updated!

**Comment by shobhitagarwal1612** [comment]
Thanks! Fixed
