### ISSUE TITLE
Offline Areas Selector Layout Regression

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#416]
After some recent changes, it looks like the Offline Areas Selector UI broke:

<img width="410" alt="Screen Shot 2020-03-26 at 11 34 20 AM" src="https://user-images.githubusercontent.com/11237600/77665505-23fee780-6f56-11ea-8e71-c392e4280feb.png">

I suspect it's due to the twoline toolbar changes. Adding here so I don't forget to fix this!

**Comment by shobhitagarwal1612** [comment]
Yes, I checked just now and it seems like my changes caused this regression. Sorry about that!

Removing the below line from the xml fixes the issue.
https://github.com/google/ground-android/blob/9efcc6993dc2b6d4ea8aed22b28f06c22e096805/gnd/src/main/res/layout/offline_area_selector_frag.xml#L32

**Comment by scolsen** [comment]
No problem, thanks for the fix!
