### ISSUE TITLE
Switch Map Type Button Bleeds into Top Android Control Bar

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#422]
**Describe the bug**
In the current UI, on a Pixel 2 the switch map button bleeds into the Android controls:

<img width="412" alt="Screen Shot 2020-03-31 at 12 47 22 PM" src="https://user-images.githubusercontent.com/11237600/78053371-81c47280-734e-11ea-8fa2-dac6008d27c9.png">

## Virtual Device Details

```


Name: Pixel_2_API_28

CPU/ABI: Google Play Intel Atom (x86)
Target: google_apis_playstore [Google Play] (API level 28)
Skin: pixel_2
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_2
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 28
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel 2 API 28
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1920
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-28/google_apis_playstore/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_2_API_28
hw.lcd.density: 420
hw.arc: false
hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

**To Reproduce**
1. Open the app
2. Go to the home screen

**Expected behavior**
Button shouldn't bleed into other controls.

**Comment by gino-m** [comment]
@shobhitagarwal1612 the button padding or position may need to be adjusted based on when WindowInsets become available. You can find other examples of this by searching in the code for "WindowInsets". Could you PTAL?

**Comment by shobhitagarwal1612** [comment]
I missed this while building the feature because the emulator (android 10.0) I was using had resolution 480x800 and the button was well within the boundary. Thanks for pointing out the issue.
