### ISSUE TITLE
Map layer selection button is obscured under notification bar 

### ISSUE THREAD

**Issue by dturner** [google/ground-android#426]
The map layer selection button is obscured under the notification bar. 
 
Steps to repro: 
1. Run the app, wait for the map to load

Expected behaviour: 
Map layer selection button is clearly visible and not obscured by other UI elements

Actual behaviour: 
Map layer selection button is obscured by the notification bar

![image](https://user-images.githubusercontent.com/873212/78660777-9613ec80-78c5-11ea-8dc0-67232fb779ca.png)

**Comment by gino-m** [comment]
@shobhitagarwal1612 could you PTAL? It may need to have padding adding when WindowInsets emits a new value.

**Comment by scolsen** [comment]
See also #422 -- just so we remember to close both once we have a fix.
