### ISSUE TITLE
[Offline support] Show connection status on UI

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#434]
@coreyleamon any suggestions on how to show this? Should it be always visible, or should a notification appear when the connection is lost / restored?

**Comment by coreyleamon** [comment]
Part of Ground's story as a useful tool is that the user does not need to worry about the connection as they are actively collecting/working. The data should save locally, correct? In that case, it is less of a warning than it is a friendly reminder.

1) The device could be offline because it has been turned off manually. If this is the case, we could prompt: "Would you like to turn on WiFi or GPS to automatically sync project changes to the cloud?" with a push to settings on clicking "Yes" (or ideally it automatically checks for WiFi first, then GPS signal — but this goes beyond a P0).

2) If WiFi or GPS is on, but without connection, we could prompt: "Your device is offline. All project changes will be saved to your device and synced automatically once a connection is established."

**Comment by gino-m** [comment]
> Part of Ground's story as a useful tool is that the user does not need to worry about the connection as they are actively collecting/working. The data should save locally, correct? In that case, it is less of a warning than it is a friendly reminder.

Yes, correct on all counts.

> 1. The device could be offline because it has been turned off manually. If this is the case, we could prompt: "Would you like to turn on WiFi or GPS to automatically sync project changes to the cloud?" with a push to settings on clicking "Yes" (or ideally it automatically checks for WiFi first, then GPS signal — but this goes beyond a P0).

Right, I think we can safely assume if they've turned off WiFi they did it on purpose. Probably not within immediate scope.

> 2. If WiFi or GPS is on, but without connection, we could prompt: "Your device is offline. All project changes will be saved to your device and synced automatically once a connection is established."

I think this may be obviated by our discussion by long-running notifications (discussion in #430); the notification can say something like "Waiting for WiFi to upload photos" and similar to convey the same meaning.

**Comment by gino-m** [comment]
Combining Corey's previous comments with my own (especially #303), it seems in general we wouldn't want to show the connection status globally in the app, but in certain situations we may want to warn the user that what they're seeing is probably out of date. Some examples come to mind:

* List of available projects - when there are no projects we'd probably want to explain why, and this explanation may different if the user is offline.
* The same applies for the observation list shown when the feature sheet appears (user taps on point). We'll want to show a message when there are no observations for a place, but "No observations found" may be misleading if the user is offline.

**Comment by sergeydolgov1** [comment]
@gino-m I think we should try to avoid complicated logic where we would need to produce many different messages that explain what users see/don't see based on the combination of their connectivity state and available projects/observations. 

Have we considered persistent app notification that show current status of the app, e.g. "Online" / "Offline (last synced at XX)" "Online" (pls connect to WiFi to sync new photos)?

**Comment by gino-m** [comment]
@sergeydolgov1 I agree it would be ideal if we can avoid needing special language for these different scenarios. We considered showing a persistent message when the user is offline, but originally I steered us away from that. My assumption was that the user would be offline most of the time, and that message would become more noise than helpful. Happy to revisit this though.

What message / UI can we show in list of observations shown in the feature details sheet if there are none stored locally that would work both in online and offline states?

**Comment by sergeydolgov1** [comment]
> What message / UI can we show in list of observations shown in the feature details sheet if there are none stored locally that would work both in online and offline states?

Perhaps something like: 
- Online state: "There are no observations for this Point"
- Offline state: "There are no observations available for this Point. Please connect to the Internet to get the latest updates"

**Comment by sergeydolgov1** [comment]
@gino-m Regarding Global notification for Online/Offline state (based on a recent discussion with Corey):
- It doesn’t matter if user is Offline or Online. What important is to communicate to users the status of Data Sync (whether it is Synced or Not) and the last time it was synced

Potential solution (need to assess feasibility and cost to implement) can be to show persistent notification ([Notifications for foreground services](https://developer.android.com/guide/topics/ui/notifiers/notifications#foreground-service)) in the notification menu that shows current state of the app, e.g. "Online, All data is synced", "Offline, Data was last synced at XX on XX".

**Comment by gino-m** [comment]
+1. newer Androids require a persistent notification be shown to do long running work, so we'll need it anyway if we want to also download points, form updates, etc. in the background (think Spotify, Pandora, Citizen). Can we get a mock of what this persistent notification would look like?

**Comment by gino-m** [comment]
Closing this issue in favor of better notifications and inline messages as discussed above.

**Comment by sergeydolgov1** [comment]
@gino-m Do we have an open Issue for App Notifications so that I can comment/ add mocks when we have them?

**Comment by gino-m** [comment]
> @gino-m Do we have an open Issue for App Notifications so that I can comment/ add mocks when we have them?

Filed #549 for this purpose.
