### ISSUE TITLE
Reopening app disables add feature button

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#438]
**Describe the bug**
Minimizing the app and reopening disables the add feature button (+) on the home screen

**To Reproduce**
1. Open app. Notice that the '+' icon on the bottom right is orange and clickable
2. Minimize the app and reopen
3. '+' icon is turned gray and is not clickable anymore

Killing the app and then reopening fixes the problem

**Screenshots**
![Screenshot_1586617124](https://user-images.githubusercontent.com/8918023/79047244-0f4b7080-7c33-11ea-9efc-5492dfbb0b1c.png)

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612, I couldn't repro - are you able to repro with latest from `master`? What project are you using?

**Comment by shobhitagarwal1612** [comment]
Yes, I can consistently reproduce this bug. After a small digging, I found out that the cause of the bug and a few others (like features not loading as well, see above screenshot) is active project not getting returned back by ProjectRepository

**Comment by gino-m** [comment]
> Yes, I can consistently reproduce this bug. After a small digging, I found out that the cause of the bug and a few others (like features not loading as well, see above screenshot) is active project not getting returned back by ProjectRepository in the above mentioned scenario

Is it because `getActiveProject()` doesn't emit the current project to late subscribers (hot instead of cold observable)? I haven't looks at the impl yet, but maybe we need to use a `BehaviorProcessor` to back the current project, and rename `getActiveProjectOnceAndStream()`?

**Comment by shobhitagarwal1612** [comment]
> Is it because getActiveProject() doesn't emit the current project to late subscribers (hot instead of cold observable)? I haven't looks at the impl yet, but maybe we need to use a BehaviorProcessor to back the current project, and rename getActiveProjectOnceAndStream()?

The problem was flowable wasn't re-emitting the last value to subscribers. To fix that, I replaced it with BehvaiorSubject. PTAL

**Comment by gino-m** [comment]
As per discussion on #446, the solution was to set `.onBackpressureLatest()` on the project stream:

```
    // Load project when requested id changes, caching the last loaded project.
    this.activeProjectStream =
        activateProjectRequests
            .distinctUntilChanged()
            .doOnNext(id -> Log.v(TAG, "Requested project id changed: " + id))
            .switchMap(this::onActivateProjectRequest)
            .onBackpressureLatest()
            .replay(1)
            .refCount();
```

Please let me know if you'd like to me to take this one and I can break this up and add comments, or if you're already working on it.

**Comment by shobhitagarwal1612** [comment]
Yes, I closed my PR as you had already tested the fix in your local branch. I forgot to unassign myself. Please proceed. Thanks!
