### ISSUE TITLE
[Add/Edit Observation] Append "(optional)" next to labels of optional form fields

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#439]
@coreyleamon, and suggestions on how to do best do this? 

Example of current implementation; first field is required, second is option, but there's no way to tell this looking at the UI. Validation errors appear on save.

![Screenshot_1586704248](https://user-images.githubusercontent.com/228050/79072314-68a4b580-7cae-11ea-9417-9c6e2f1ff79a.png)

**Comment by coreyleamon** [comment]
Common practice is to use labels to indicate the exception. Since this is a 50/50 scenario, and not knowing how our input forms will scale in the future, my recommendation is to label it "Notes (optional)".

**Comment by gino-m** [comment]
Sgtm. Updated description to reflect this suggestion. Thanks!

**Comment by shobhitagarwal1612** [comment]
@gino-m Can we close this issue? Now we show asterisk next to required field labels.

![Screenshot_1593524390](https://user-images.githubusercontent.com/8918023/86133057-69a6ef80-bb05-11ea-88bf-2c1d69ce737d.png)
