### ISSUE TITLE
[Survey list] Allow users to manage synced surveys

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#450]
Moved from misplaced issue https://github.com/google/ground-platform/issues/243. See that issue for full thread.

Currently, "+ Join Project" appears above the list of locally cached ("joined") projects, and there is not "leave project option". It's not clear how frequently users will be switching projects, if at all - is this the best way to represent these concepts? How can we make this better?

![image](https://user-images.githubusercontent.com/228050/79897220-6261b800-83d7-11ea-8cb7-bf0c801f5ce7.png)

**Comment by gino-m** [comment]
@shobhitagarwal1612 @coreyleamon Carrying over the conversation from the Platform repo:

> To clarify: the intent of this list of projects is to show what has already been downloaded and therefore can be used offline? Or is it the list of projects that should have data downloaded any time there is a connection? Let me know if I'm misunderstanding.

For now it's just the former. In the future we would also like to sync project config (forms, layers) and map features for all of these projects either when the app is open or in the background.

> And what is meant by "active" or "inactive" projects? Is that as in, you are part of a project, or you decide to end participation?

"Active" here means the currently selected project (the one you're viewing). Open to suggestions on better/clearer names here.

> If I am understanding the intent, I am not sure that organizing a main navigational structure based on offline or online projects makes as much sense as simply having a list of projects I am a part of, regardless of connection. There should be a way other than navigation to indicate if a project is up-to-date and downloaded, or if it is set to do so when online. I need to understand more here to make a recommendation.

Being a "part" of a project doesn't really have meaning in Ground. Which projects the user has access to is implicit (public projects + projects shared with the user). I agree that which projects are available offline doesn't belong in a main sidenav; we just put it there as a temporary sol'n barring a proper UX design. Let's set some time to discuss?

**Comment by gino-m** [comment]
@coreyleamon This is another area where we're currently lacking a rational solution. One possible treatment could look something like this:

* The current project and a menu option "Manage projects" are always displayed in the nav drawer.
* A refresh icon is shown next to the current project to force a refresh (we don't yet have auto sync of project metadata).
* The "Manage projects" UI allows you to remove projects from your device. This will stop all background syncing of these projects.
* The "Manage projects" UI could also have an option to add/join a new project.

The polygon editing is still our main priority, but just wanted to have this on your radar. Thanks!

**Comment by gino-m** [comment]
This survey list in the sidebar will go away, surveys (synced and new) will appear in the main landing page. @ngosue Perhaps we can add an affordance there to remove them from the device / stop syncing?

**Comment by gino-m** [comment]
Update: This design is still a WIP, but will be defined soon. I'll update here once designs are stable. @shobhitagarwal1612 FYI.

**Comment by shobhitagarwal1612** [comment]
The new survey selector screen allows removing already synced projects. We can mark this one as done.
