### ISSUE TITLE
[Add/edit observation] Allow multiple choice fields to be shown inline

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#456]
The edit observation form currently shows multiple choice questions (option, checkbox) in a modal dialog, requiring two extra taps - one tap on the field to open the modal, and one on "APPLY" after value(s) are selected. Showing the checkboxes/options directly on the form would reduce friction during data entry. 

It's assumed we'd would want to preserve the modal for longer lists, possibly adding a search function in the future. This can be controlled by a flag in the form field definition (style: "INLINE")?

**Comment by sergeydolgov1** [comment]
Current implementation:
![image](https://user-images.githubusercontent.com/20148684/86302911-0ed1ce80-bbbf-11ea-8421-f438c86fa651.png)

**Comment by sergeydolgov1** [comment]
@gino-m 

Suggestions:
- Keep current layout because: 1) If we show the form inline, the list of questions can be potentially too long; 2) Tap to Modal dialog can be actually good for keeping users focused on the task
- Tweak "Add Button" styling so that it meets Accessibility standards (i.e. Contrast)

**Comment by gino-m** [comment]
> Keep current layout because: 1) If we show the form inline, the list of questions can be potentially too long; 2) Tap to Modal dialog can be actually good for keeping users focused on the task

Showing inline would in addition to being able to show as modal - it would optionally be specified in the form designer.

> Tweak "Add Button" styling so that it meets Accessibility standards (i.e. Contrast).

+1. This will be fixed with #486.

**Comment by gino-m** [comment]
Covered by #1146.
