### ISSUE TITLE
[Build] Long build times

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#460]
A semi-friend build can take 1m30s - 2m30s. Disabling firebase-perf plugin gets this down to 3-27s. We may want to conditionally disable this on "dev" builds (but maybe not "debug") builds:
https://stackoverflow.com/questions/47380524/firebase-performance-plugin-causing-slow-build-time

**Comment by shobhitagarwal1612** [comment]
Thanks @gino-m!
