### ISSUE TITLE
[Code health] Refactor AuthenticationManager to make testing easier

### ISSUE THREAD

**Issue by dturner** [google/ground-android#465]
Currently `MainActivity` has a dependency on `AuthenticationManager` which it uses to get the current user's signed in state (e.g. logged in) and direct the user to the relevant fragment.

`AuthenticationManager` has a dependency on Google Sign In. This presents a challenge for UI and integration testing because it's impossible to replace `AuthenticationManager` with a class which does not have these external dependencies. 

I propose refactoring `AuthenticationManager` into interface and implementation, then having a separate `FakeAuthenticationManager` which can be used for testing.

**Comment by gino-m** [comment]
Hi @dturner is this issue still valid?

**Comment by dturner** [comment]
Fixed in #569.
