### ISSUE TITLE
Not all features are loaded on activating project

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#470]
**To Reproduce**
1. Select project `Plastic Frog Finder`. (This one has a lot of dummy features)

**Expected behavior**
All features points (shown as map pins) should be displayed on the map

**Actual behavior**
Only a subset of points are shown. The count increases gradually whenever the app is restarted.

**Comment by shobhitagarwal1612** [comment]
On digging deeper, I found out that all remote features are successfully received by the app and make it to the Doc -> Feature converter. But don't get inserted into the local database. In the test project, out of 87 the total no of insert operations on multiple iterations varied. 
e.g.
1st --> 3 inserted
2nd --> 10 inserted
.... and so on

I suspect that it has something to do with the Rx chain. All the calls that are made to the LocalDataStore don't get to a conclusion. To confirm this theory, next I would like to do a non-Rx approach to insert data into room db.

**Comment by gino-m** [comment]
> On digging deeper, I found out that all remote features are successfully received by the app and make it to the Doc -> Feature converter. But don't get inserted into the local database. In the test project, out of 87 the total no of insert operations on multiple iterations varied.
> e.g.
> 1st --> 3 inserted
> 2nd --> 10 inserted
> .... and so on
> 
> I suspect that it has something to do with the Rx chain. All the calls that are made to the LocalDataStore don't get to a conclusion. To confirm this theory, next I would like to do a non-Rx approach to insert data into room db.

Could a subscription be getting disposed before the data is all written?

**Comment by shobhitagarwal1612** [comment]
I doubt that is the case. I am saying this because for all 87 features the Doc -> Feature conversion occurred but the result wasn't added to db. The entire list of features (from getFeaturesStream) is processed in a single batch and not one after another through upstream. So, if it was a case of premature disposal of subscription, then we wouldn't see all 87 conversions, right? 
https://github.com/google/ground-android/blob/master/gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java#L99

I'll try out other approaches and update my findings here.

**Comment by gino-m** [comment]
Good point. Could some of the inserts be failing, and errors be getting eaten at some point?

**Comment by shobhitagarwal1612** [comment]
If I block the thread after update/insert and run everything on main thread, then all entries get inserted as expected.

You were right, the subscription is getting disposed by the upstream before the entry gets inserted (added logs in onComplete, onSubscribe and onDisposed to validate this. only a few onComplete logs were visible before onDisposed was called)

I also found that `FeaturesCollectionReference` drop the most latest updates if the downstream can't keep up with the pace. But that seems unrelated to this problem. I thought this was a problem of having no buffer. But `flatMapIterable` for `Flowable` by default applies some buffer.

**Comment by shobhitagarwal1612** [comment]
I can't figure out what is missing here. It works only when the insert/update calls are blocking and on UI thread. Need help!
