### ISSUE TITLE
[Code health] Simplify applying window inset to components

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#476]
The main activity subscribes to window inset changes and all fragments listen to that and apply padding/margin/translationY to adjust themselves accordingly.

A lot of code, dedicated for this purpose can be replaced with tuning the xmls directly by separating the components that need adjustment from rest and setting `fitsSystemWindows` to `true`

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612 can we close this now?

**Comment by shobhitagarwal1612** [comment]
One or two instances are still remaining. See the linked PR for details

**Comment by shobhitagarwal1612** [comment]
`HomeScreenFragment` and `FeatureDetailsFragment` could also use similar refactoring.

**Comment by shobhitagarwal1612** [comment]
Closing this as obsolete.
