### ISSUE TITLE
[Add/edit observation] Colors incorrect after Material update

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#486]
From @shobhitagarwal1612:
 
![Screenshot_1590381265](https://user-images.githubusercontent.com/8918023/82778822-23100680-9e70-11ea-9950-3888c7477b62.png)
![Screenshot_1590381292](https://user-images.githubusercontent.com/8918023/82778827-286d5100-9e70-11ea-881a-8246aa6c01a9.png)

**Comment by gino-m** [comment]
This low priority but it irks me so I'll try to get this done in MVP Sprint 3, time permitting.

**Comment by pree-T** [comment]
Is this issue still open? May I work on it? Can someone help me as I am new to open source contribution.

**Comment by gino-m** [comment]
Obsolete as of #1146.
