### ISSUE TITLE
[Process] Robust automated testing in place

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#488]
- [x] Automated testing run via CI
- [x] Automated UI testing run via CI
- [x] Acceptable unit test coverage
- [x] Acceptable UI test coverage

**Comment by shobhitagarwal1612** [comment]
+1 for coverage

**Comment by scolsen** [comment]
@shobhitagarwal1612 assigning to you for now, please reassign back to me if needed!

**Comment by gino-m** [comment]
Automated testing is in place, adding coverage is a high-level concern owned by the whole team.
