### ISSUE TITLE
[UI Tweak] Fix color of status bar scrim

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#490]
From #477 

The system inset areas shows as grey instead of blue in Offline areas and Settings:
![image](https://user-images.githubusercontent.com/228050/82760079-534b9c80-9dbf-11ea-865e-18019c6bd474.png)

Ideal would be as in the expanded feature sheet:
![image](https://user-images.githubusercontent.com/228050/82760118-82620e00-9dbf-11ea-8068-b815ad4d4f77.png)

**Comment by diamondlee7** [comment]
@shobhitagarwal1612 I would like to address this issue. Can you please assign it to me?

**Comment by shobhitagarwal1612** [comment]
Thanks @diamondlee7! Please go ahead.

**Comment by arsundram** [comment]
Is it still available? If yes, I would like to work upon this issue.

**Comment by shobhitagarwal1612** [comment]
Hi @arsundram and welcome to the project! @diamondlee7 has already started working on this issue. But there are other [unassigned issues](https://github.com/google/ground-android/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) that you can take a look at. Please don't hesitate to ping if you need assistance.
Cheers!

**Comment by gino-m** [comment]
Hi @diamondlee7! Do you have an ETA of when you'd be able to send a PR for this issue? If you're not able to take this one on, please let us know and we'll reassign. Thanks for contributing!

**Comment by diamondlee7** [comment]
> Hi @diamondlee7! Do you have an ETA of when you'd be able to send a PR for this issue? If you're not able to take this one on, please let us know and we'll reassign. Thanks for contributing!

Please feel free to reassign. Thank you!

**Comment by gino-m** [comment]
Thanks for letting us know! If you have time to contribute in the future we'd love to accept your PRs!

@arsundram, still interested in taking this one?

**Comment by MohitMandalia** [comment]
Hi @shobhitagarwal1612 ,
Can I take this one? I would like to work on this one.

**Comment by SamarthAsthan** [comment]
@shobhitagarwal1612  Is this issue still there? and if so can i work on it

**Comment by gino-m** [comment]
We're restyling the app so closing this for now until we have the new UX. @ngosue FYI.

**Comment by SamarthAsthan** [comment]
@gino-m cool
