### ISSUE TITLE
[Add observation] Required fields show errors when form is opened

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#493]
**To Reproduce**
1. Add a feature
2. Add an observation for a form with required fields

**Expected behavior**
Blank required fields show errors immediately.

**Actual behavior**
Required fields do not show errors only on blur or when form is saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/228050/83787774-4736c900-a662-11ea-8982-5e5ed51a5f04.png)

**Comment by shobhitagarwal1612** [comment]
By @gino-m 
"We can show a * next to required field labels for now"
