### ISSUE TITLE
[Edit Record] Save button sometimes has no effect

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#5]
When many users are adding data, "Save" button sometimes stops working. Users observed this at G4G18 when editing the 'frogs' test project.

**Comment by shobhitagarwal1612** [comment]
@gino-m I haven't faced any issue with the "save" button. Can you please confirm if this issue is still active?

**Comment by gino-m** [comment]
I haven't seen it either. Let's close this for now and do a properly bug bash as a team once MVP is ready.
