### ISSUE TITLE
[Survey selection] Rationalize and simplify "join survey" flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#504]
Currently, we show a simple list of surveys shared with the user.

Is a browse experience the way we think users should discover and join surveys? 

Future entry points could include via a shared link, by entering a project ID and pin code, or by scanning a QR code. More work is needed here. @ngosue re our earlier discussion today.

**Comment by shobhitagarwal1612** [comment]
@gino-m Should we get rid of the list of offline synced surveys from the navigation drawer?

![image](https://user-images.githubusercontent.com/8918023/213907285-678d9942-427f-40e4-a12e-eaf36474c131.png)

**Comment by gino-m** [comment]
Yes, that would go as well. We'd still need a menu option to access to survey screen, perhaps something like "Change survey".
