### ISSUE TITLE
[Code health] Consolidate local and remote db services

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#51]
Currently, local db impl using Room lives in `com.google.android.gnd.repository.local`.

The remote db interface is in `com.google.android.gnd.service.RemoteDataService`, with Firestore impl under `com.google.android.gnd.service.firestore`.

This is inconsistent and arbitrary. I would suggest renaming and moving as follows:
* Remote db interface: `com.google.android.gnd.service.remotedb.RemoteDbService`
* Remote db impl: `com.google.android.gnd.service.remotedb.firestore.*`
* Local db interface: `com.google.android.gnd.service.localdb.LocalDbService` (TBD)
* Local db impl: `com.google.android.gnd.service.localdb.room.*`

@scolsen, @navinsivakumar, any thoughts?

**Comment by navinsivakumar** [comment]
Works for me. (And it's "just code", right? So it shouldn't be too hard to move things around later, with the help of an IDE/refactoring tools.)

**Comment by gino-m** [comment]
That's right. Just want to get it close to right since moving and renaming can create big ugly PRs. Thanks!
