### ISSUE TITLE
Manage lines and polygons [RC]

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#520]
- [ ] Draw
- [ ] Edit
- [ ] Delete

**Comment by gino-m** [comment]
@sergeydolgov1 for prioritization

**Comment by sergeydolgov1** [comment]
@gino-m Should we prioritize this for Release Candidate? I think we were inclined toward having only Representation layer in the pilot stage

**Comment by sergeydolgov1** [comment]
@gino-m @shobhitagarwal1612 
Manage lines and polygons is part of Release Candidate, de-prioritized for MVP
