### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#532]

**Comment by shobhitagarwal1612** [comment]
Is there a recommendation for how to approach this? Should we start migrating classes which already have unit tests or should it be used for new classes only?

**Comment by gino-m** [comment]
> Is there a recommendation for how to approach this? Should we start migrating classes which already have unit tests or should it be used for new classes only?

Hi Shobhit, we discussed starting with new classes, tests, and necessary dependencies, and once we’re comfortable, migrating existing classes and tests as we go. Wdyt?

**Comment by shobhitagarwal1612** [comment]
Since I don't have any active PRs, I thought of migrating one or two of the existing classes to kotlin. But adhering to using Kotlin for new/modified code also sounds reasonable. Can't wait to get my hands dirty.

**Comment by scolsen** [comment]
just an FYI, I'm already altering all of the mutation objects, so just a heads up to avoid selecting those -- I'll have a PR for that out today

**Comment by scolsen** [comment]
Think it's safe to consider this one done?

**Comment by shobhitagarwal1612** [comment]
:+1:

**Comment by scolsen** [comment]
Closing, while we're not 100% Kotlin just yet, much of the codebase has been migrated. We can continue to migrate classes over time if it makes sense.
