### ISSUE TITLE
[Offline base maps] Show place name in offline area list

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#536]
Place names can be fetched with https://developer.android.com/reference/android/location/Geocoder when downloading the areas.

This is low priority but adding here to tract - for now we'll show "Area 1, Area 2.." in the offline base map areas list.

@sergeydolgov1 Fyi, please cmiiw.

**Comment by sergeydolgov1** [comment]
I think this can improve UX. Just wonder what names Geocoder returns for remote/rural areas where users are likely to be offline (i.e something distinct and recognizable or a generic name for those areas)

**Comment by gino-m** [comment]
Duplicate of #538.
