### ISSUE TITLE
Not easy to add features at the top and bottom extremes of Earth

### ISSUE THREAD

**Issue by dturner** [google/ground-android#554]
When adding a feature you generally zoom out of the map until the crosshair is roughly over the location you want, then zoom in until you've got an accurate position. 

At the top and bottom extremes of Earth this isn't possible because you reach the limits of the map. 

**To Reproduce**
1. Zoom out fully on the map
2. Attempt to move the map so the crosshair is over [Svalbard](https://www.google.com/maps/place/Svalbard,+Svalbard+and+Jan+Mayen/data=!4m2!3m1!1s0x45a1cfdc4fa3c049:0x2bf373e71b35e875?sa=X&ved=2ahUKEwie_dDrzPfqAhVIXsAKHZ1yAXwQ8gEwJ3oECBgQBg)

**Expected behavior**
It's possible to position the crosshair over Svalbard

**Actual behavior**
It's not possible to position the crosshair over Svalbard because the limits of the map have been reached. 

**Screenshots**
![image](https://user-images.githubusercontent.com/873212/89039888-b9621c00-d33a-11ea-89e5-db12a217e728.png)

One option would be to add some extra space at the top of the bottom of the map so that the map can be zoomed out more, but disallow the positioning of the crosshair anywhere outside of Earth.

**Comment by gino-m** [comment]
I think we generally wouldn't be adding features zoomed out this far. @sergeydolgov1, wdyt?

**Comment by sergeydolgov1** [comment]
@gino-m @dturner We don't expect users adding features when the map is zoomed out this far.

**Comment by dturner** [comment]
To be clear, I'm not suggesting that users would add features when zoomed out this far as it's not accurate enough. What I mean is that it's more difficult to zoom in to your desired location at the top or bottom of the earth because you cannot manoeuvre the map so that you zoom directly in on it; you have to zoom in, drag the map back to the centre, then repeat (and that's _if_ you figure out that's what you need to do - it took me a second to realise it was even possible). 

It's only a minor thing but I don't see why the app should be more difficult to use depending on _where_ you're adding data - especially as it may be that the app does get used in these locations as they are most affected by climate change (ice caps melting, etc).

**Comment by sergeydolgov1** [comment]
@dturner @gino-m Don's latest comment makes sense. This can be a potential issue longer term, not for initial pilot

**Comment by gino-m** [comment]
+1. Updated priority, release, pipeline. Please edit freely.
