### ISSUE TITLE
Not possible to sign out

### ISSUE THREAD

**Issue by dturner** [google/ground-android#555]
It's not possible to sign out.

**Steps to reproduce**
- Load the app, sign in using gndtestuser
- Expand the side bar
- Tap Sign out

**Expected behavior**
gndtestuser is signed out and user is taken back to the sign in page

**Actual behavior**
Nothing happens when tapping the Sign out button

**Comment by dturner** [comment]
Clean and rebuild, now seems to be working 🤷

**Comment by gino-m** [comment]
> Clean and rebuild, now seems to be working 🤷

#weird.. seems changing keys is always a little flaky due to caching, etc. Glad it's working!
