### ISSUE TITLE
[Add/edit observation] Multiple choice options sometimes missing

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#557]
* Add/edit observation using example Firebase scheme
* in layer001, options not shown for third question:

![Screenshot_1596492374](https://user-images.githubusercontent.com/228050/89231794-069cf280-d5b4-11ea-98e0-cdbed9700cd4.png)

**Comment by shobhitagarwal1612** [comment]
I was unable to reproduce the bug. The options loaded consistently each time.
![Screenshot_1602155759](https://user-images.githubusercontent.com/8918023/95451677-c415de80-0985-11eb-86a7-cbb74e565767.png)

Please feel free to reopen the bug if it happens again.

**Comment by gino-m** [comment]
Ok, let's see if it recurs during manual testing. Thanks!
