### ISSUE TITLE
[Add/edit observation] Values selected in app don't correspond to what's show in web app

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#559]
Edited in app:
![Screenshot_1596493026](https://user-images.githubusercontent.com/228050/89232505-8d060400-d5b5-11ea-8536-cdce5d31c306.png)

In web app:
Updated demo: https://gnd-dev.web.app/p/example#f=pIPl6J1vCz4h8xzgVZL1

**Comment by shobhitagarwal1612** [comment]
Can you please verify that the bug is still active? 
I did not face any trouble while presenting the demo during the GVC.

**Comment by gino-m** [comment]
I haven't been able to repro either, so marking closed for now.
