### ISSUE TITLE
[Code health] Consider simplifying model objects

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#564]
Rebooting the discussion in #517 with a broader scope.

Lately, I've been regretting two design choices made fairly early on - using `@AutoValue` instead of Protocol Buffers, and serializing all data locally as separate table rather than as serialized protos. As is stands right now, it's painful to add a single field to our schema because three version of the model need to be updated, as well as conversion logic in each direction for each layer (6x). The initial intent was that we want each layer to be independent to guarantee backwards compatibility, and data modeling that's appropriate for each layer and supporting API (e.g. local db uses generated ids, remote uses uuids, etc). But as we can see this has become burdensome in practice.

If we use protos, would could also in theory use the same representation for core data throughout the app, wrapping them to provide behavior and additional state to get the best of both worlds.

I was initially steered away from using protos by someone on Android DevRel for our domain model objects, and I understand why; as I understand it, protos aren't designed as a drop-in replacement for application domain model classes. That said, I feel like some level of reuse would be helpful here.

If we used protos for the local datastore, we could write the serialized `Project`, `Feature`, and `Observation` protos, and we wouldn't need separate tables for each sub-entity. If we use the same protos in the application model, we also could simplifying conversion of model objects between remote and local datastore layers. 

@scolsen @shobhitagarwal1612 @dturner any thoughts on this?

**Comment by shobhitagarwal1612** [comment]
Keeping a common core schema sounds very exciting to me. So, does that mean the clients (both web and mobile) need to do the conversion between JSON <-> protobuf? Or does firestore allow storing protobufs directly?

**Comment by gino-m** [comment]
> Keeping a common core schema sounds very exciting to me. So, does that mean the clients (both web and mobile) need to do the conversion between JSON <-> protobuf? Or does firestore allow storing protobufs directly?

Firebase client APIs unfortunately don't support convert remote data to/from protos. This step would eventually be done by our Ground server-side component (TBD). In the meantime, we could continue to do this on the client using the existing code.

If we do use the same proto everywhere, we need to be very careful to never make breaking changes to the proto defs, and to build backwards compatibility into our clients when those protos or when other representations (local, remote) do change.

I wonder if we can use https://github.blog/2016-02-01-working-with-submodules/ to share the protodefs among clients and eventual server..

@scolsen @dturner Any thoughts?

**Comment by gino-m** [comment]
Punting on this for now. We can consider introducing nested protos if we move to a separate server-side component.
