### ISSUE TITLE
[Code health] Editor config doesn't match continuation indentation

### ISSUE THREAD

**Issue by dturner** [google/ground-android#570]
Android Studio uses `.editorconfig` file to format code, wrapping lines which are too long to look like this:
 
```
@UninstallModules({AuthenticationModule.class, RemoteStorageModule.class,
  LocalDatabaseModule.class})
```

`checkstyle` then checks the formatting of that code, specifically using the `lineWrappingIndendation` [rule](https://github.com/google/ground-android/blob/master/third_party/checkstyle/google_checks.xml#L241) which fails because [2 spaces are added instead of 4](https://github.com/editorconfig/editorconfig-jetbrains/issues/57). 

The fix/workaround is to add `continuation_indent_size = 4` to `.editorconfig`.

**Comment by gino-m** [comment]
@dturner Is this also the case when using the `google-java-format` plugin?
