### ISSUE TITLE
[Code health] checkstyle reports indentation error when using @Rule annotation

### ISSUE THREAD

**Issue by dturner** [google/ground-android#571]
Consider the following code: 

```
  public @Rule(order = 0)
  HiltAndroidRule hiltRule = new HiltAndroidRule(this);
```

Running `checkstyle` on this returns an error: 

```
'HiltAndroidRule' has incorrect indentation level 2, expected level should be 6. [Indentation]
```

This is not correct, since the indentation of both lines is correct (2 spaces).

**Comment by dturner** [comment]
Workaround is to move `public` next to `HiltAndroidRule`: 

```
  @Rule(order = 0)
  public HiltAndroidRule hiltRule = new HiltAndroidRule(this);
```

Which is more readable in any case.

**Comment by gino-m** [comment]
Wouldn't we generally put the visibility modifiers (public) after the annotations?

**Comment by shobhitagarwal1612** [comment]
Is this still actionable or can it be closed?

**Comment by gino-m** [comment]
> Is this still actionable or can it be closed?

@dturner? If not we can close it.

**Comment by dturner** [comment]
It will be fixed as soon as the [UI tests PR](https://github.com/google/ground-android/pull/569) is merged.

**Comment by gino-m** [comment]
#569 merged so closing. Please reopen if necessary.
