### ISSUE TITLE
[Code health] Define happy paths for UI tests

### ISSUE THREAD

**Issue by dturner** [google/ground-android#572]
We should define the "happy paths" for UI tests to ensure maximum coverage. Examples/ideas: 

The user can: 

- select a default project the first time the app is run
- add a feature to the map [works offline as well]
- scroll to all extents of the map [works offline as well]
- download map tiles
- zoom in and zoom out fully and imagery is displayed at all levels [works offline if map tiles have been downloaded]
- add an observation to an existing feature
- log in
- log out

**Comment by dturner** [comment]
@sergeydolgov1 Gino thought you'd be best placed to answer this.

**Comment by gino-m** [comment]
I think the golden path would be as follows (in order):

1. Open app
2. Sign in
3. Select project
4. Select "offline areas" - select an area and press "Download", wait for download to complete*
5. Tap crosshairs button - accept required settings and permissions changes to enable GPS lock*
6. Go someplace where there's no signal*
7. Click "+" (Add feature), select a layer
8. Click "Add observation"
9. Enter responses for text, select one*, select many*, and photo* fields and tap save.
10. Click new data shown in observation list - values appear in view mode.

Starred (*) steps can be implemented independently of the main path.

@sergeydolgov1 @dturner wdyt?

**Comment by sergeydolgov1** [comment]
@gino-m @dturner Gino's proposed path lgtm

**Comment by dturner** [comment]
SGTM. I'll get working on that.
