### ISSUE TITLE
[CI] Builds failing with 'repository 'tmp' does not exist'

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#588]
On GCB #585 was failing with:
```
Already have image (with digest): gcr.io/cloud-builders/git
Cloning into 'tmp'...
mv: cannot move 'tmp/.git' to './.git': Directory not empty
```

I tried pushing a no-op change and received the same error in #587.

I deleted all caches in Cloud Storage, and now builds fail with:
```
Starting Step #0 - "Copying gradle build cache tar from GCS"
Starting Step #2 - "Copy .git directory for versioning"
Step #2 - "Copy .git directory for versioning": Already have image (with digest): gcr.io/cloud-builders/git
Step #0 - "Copying gradle build cache tar from GCS": Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #2 - "Copy .git directory for versioning": fatal: repository 'tmp' does not exist
Finished Step #2 - "Copy .git directory for versioning"
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/git" failed: step exited with non-zero status: 128
```

I tried rebuilding the image with `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ANDROID_VERSION=28` and received the same error.

@shobhitagarwal1612 could you kindly take a look or point me in the right direction? Could this be related to #584?

**Comment by shobhitagarwal1612** [comment]
I see the following error when running the remote builds.

`Caught non-retryable exception while listing gs://gradle_cache_bucket/: BucketNotFoundException: 404 gs://gradle_cache_bucket bucket does not exist.`

For some reason the bucket where we store our build cache no longer exists. Recreating that should fix the problem. 
But why did it get removed automatically? Thoughts?

**Comment by shobhitagarwal1612** [comment]
I also can't see `artifact_bucket` where we store our build reports. @gino-m Can you see the buckets?

**Comment by shobhitagarwal1612** [comment]
I think they got deleted and it is not a problem of visibility. 
Created both buckets.

**Comment by shobhitagarwal1612** [comment]
Getting new errors now:

```
Step #1 - "Extracting tar": error pulling image configuration: unknown blob
ERROR: failed to pull because we ran out of retries.
ERROR
ERROR: build step 1 "gcr.io/ground-android-gcb/android:base" failed: error pulling build step 1 "gcr.io/ground-android-gcb/android:base": generic::unknown: retry budget exhausted (10 attempts): step exited with non-zero status: 1
```

**Comment by shobhitagarwal1612** [comment]
Publishing a fresh docker image
