### ISSUE TITLE
[Location lock] Crosshairs lags behind blue dot on map when walking

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#592]
To repro, load https://www.gpsvisualizer.com/examples/google_gpx.html in emulator and play back at 1x speed, enabling location lock.

![Screenshot_1602860690.png](https://images.zenhubusercontent.com/5f062d0f25250e63f9559a02/5678abe9-67ba-4aa6-acaf-286e08cdd1a3)

**Comment by SamarthAsthan** [comment]
@gino-m can you tell in a little more detail?

**Comment by gino-m** [comment]
> @gino-m can you tell in a little more detail?

Hi @SamarthAsthan Are you still interested in looking into this one?

**Comment by gino-m** [comment]
Obsolete as of #1146; crosshairs will be removed, but this may pop up again when dropping a pin.
