### ISSUE TITLE
[Map pin] Show pin while dragging

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#596]
Current the pin only updates after dragging stops.

**Comment by gino-m** [comment]
Thank for filing this!

**Comment by gino-m** [comment]
@ngosue FYI

**Comment by scolsen** [comment]
@shobhitagarwal1612 do we support this in the drop a pin task?

**Comment by shobhitagarwal1612** [comment]
Not yet. I was hoping to get the UX finalized before implementing any news UI changes.

**Comment by scolsen** [comment]
Part of the revamp work @shobhitagarwal1612 is currently engaged in.
