### ISSUE TITLE
[Feature sheet] Bottom sheet does not appear when tapping pins

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#603]
This is expected for features for layers without forms but this happens for all layers.

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612 do I remember correctly that you recently added a logic to hide the sheet if the layer had no forms? I couldn't find that PR. Could you PTAL?

**Comment by shobhitagarwal1612** [comment]
Sure.

**Comment by shobhitagarwal1612** [comment]
> I remember correctly that you recently added a logic to hide the sheet if the layer had no forms? I couldn't find that PR

That was regarding visibility of add feature button. But I agree that this regression wasn't seen before. Maybe they are related in some way

**Comment by shobhitagarwal1612** [comment]
Ok, I have found the culprit. It happens only when the GeoJSON is rendered to the map

**Comment by gino-m** [comment]
> Ok, I have found the culprit. It happens only when the GeoJSON is rendered to the map

Excellent! Thanks for the quick response!
