### ISSUE TITLE
[Map] Viewport is reset after returning from other Fragments

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#605]
For example after hitting "Save" on the add/edit observation fragment.

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612! Would you be able to take a look? Does it have anything to do with recent changes to the MapAdapter to support polygons?

**Comment by shobhitagarwal1612** [comment]
Yep

**Comment by dturner** [comment]
I'm not sure I can reproduce. When I tap on a feature the map automatically zooms in to the highest zoom setting, and this doesn't change when I save an observation. 

Would it be more desirable to just center on the feature when tapping on it, keeping the current zoom setting, then keep this zoom setting throughout any extra navigation (like adding an observation)?

**Comment by dturner** [comment]
@gino-m Please could you clarify what the issue is?

**Comment by gino-m** [comment]
Hmm. I can no longer repro either- the viewport was completed reset after adding a new observation. Perhaps this was related to one of @shobhitagarwal1612's recent fixes also fixed this? Let's close this one for now then. Thanks for checking it out!

**Comment by gino-m** [comment]
Zoom level and viewport is lost on orientation change.

**Comment by dturner** [comment]
There is a TODO which explains a navigation controller bug which, if we fix, may also fix this.

**Comment by dturner** [comment]
Steps to repro: 

- Load app, load project which contains existing pins
- Tap on any pin, feature details will load with map fully zoomed in
- Tap back
- Pinch to zoom out a few times
- Rotate device

Expected outcome
- Zoom level is retained

Actual outcome
- Map is fully zoomed in on the previously tapped feature pin

**Comment by gino-m** [comment]
Hi @dturner, one repro is when returning from the Offline Areas UI. Built at `master`:

![Screen Recording 2020-11-28 at 5 26 39 PM](https://user-images.githubusercontent.com/228050/100519433-daf6d700-3165-11eb-8cd9-c6e7bce10978.gif)

**Comment by dturner** [comment]
This bug explains why there's so many customisations to navigation: https://github.com/google/ground-android/issues/245

**Comment by dturner** [comment]
AI: Investigate the best practices for navigation wrt our current nav_graph.xml
