### ISSUE TITLE
Offline base maps sometimes don't completely download

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#629]
Sometimes downloaded base maps display black boxes instead of imagery, but we've confirmed the source tiles are not corrupt.

We should take a look at the download worker, likely some tiles are silently failing to download completely.

**Comment by gino-m** [comment]
@scolsen We discussed - this appears to only be happening with tiles surround the outer boundary of the dowloaded imagery - could there possibly be a bug calculating or downloading these particular tiles?

**Comment by gino-m** [comment]
@scolsen This issue has been inactive for awhile and we haven't seen this reoccur so closing for now. Please reopen if relevant!
