### ISSUE TITLE
[Edit observation] Changes not reflected on View Observation after saving changes

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#638]
**To Reproduce**
1. Edit an existing observation and click "Save".
2. View observation screen doesn't reflect changes. Changes appear in observation list and after returning to view observation screen.

@shobhitagarwal1612 would you be able to take a look? 🙏

**Comment by shobhitagarwal1612** [comment]
I followed the same steps as mentioned in the description but wasn't able to repro the error.
Can you please check the exact steps again?

**Comment by shobhitagarwal1612** [comment]
Can we close this?

**Comment by gino-m** [comment]
Yes, it seems this issue hasn't recurred so closing now. Thanks!
