### ISSUE TITLE
Keep RX Streams as "Pure" as Possible?

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#67]
At the moment, there are some places in which streams and so called "side effects" (operations that use some value from the stream but *don't* modify the stream's contents i.e. aren't operations like map, and co.)  are intermingled. For example, the `addFeatureDialogFragment.show` function:

```
Observable<Feature> featureStream =
        showFeatureDialogRequests.flatMapMaybe(
            fragmentManager -> addFeatureDialogFragment.show(fragmentManager));

```

does two things: it calls show on the fragmentManager, and returns an entirely new PublishSubject:

```
public Maybe<Feature> show(FragmentManager fragmentManager) {
    addFeatureRequestSubject = MaybeSubject.create();
    show(fragmentManager, TAG);
    return addFeatureRequestSubject;
  }
```

This obfuscates the semantics somewhat and makes reading some functions difficult. For example, I would expect `show` to be "effectful" only, and not to return a new Maybe.

Instead we can refactor this to use RX semantics to achieve the same thing. 

```
Observable<Feature> featureStream =
        showFeatureDialogRequests.doOnNext(fragmentManager -> show(fragmentManager, TAG)).flatMapMaybe(__ -> addFeatureDialogFragment.toSubject());
```

An approach like this keeps side effects and transformations separate and immediately obvious when reading the sequence of stream operations. This way we can essentially keep data transformations and ui actions 'distinct'. 

This is preferential of course, so please let me know if you disagree!

**Comment by scolsen** [comment]
@gino-m @navinsivakumar

**Comment by gino-m** [comment]
The idea here was that the Maybe returned to `show()` would complete with the outcome of the dialog. The fact we create a new `Subject` every time is probably a smell, or at least an incorrect implementation.

To your point about not changing the streams, this particular example does, in fact; it starts out with just a click, and then ends up with a new `Feature` created by the new feature dialog selector (also probably incorrect; if anything it should return a FeatureType.

I think to model this particular case correctly, we'd probably just need to fix the smells/bugs mentioned above. I don't know if using a side effect, then joining the outcome of that side effect to the main stream is the right approach either...

**Comment by scolsen** [comment]
Ahhhhh, I see. I misunderstood `Dialog.show()` --I missed the crucial reference to `this` in its body. So, you're right, this wouldn't work in this case since it'd actually reference the wrong fragment, but `Dialog.show()` happens to have meaningful effects on the stream contents in this case because of calls to `onCreate` etc. that do all the work to kick off transformations/initialization.

Agreed that the particular case can be refactored as well. I wonder whether it makes more sense to return data streams from ViewModel's only, limiting, as much as possible, fragments to "action" streams (clicks, triggers, and what nots). In this particular case we'd have to point both fragments (home screen and dialog) to a shared VM and return data to the fragments as needed from there. In this case we'd need to rig something up so that the Fragment is not longer returning a MaybeSubject, but instead kicking off a process in the VM that returns the MaybeSubject (or simply emits on it, which the necessary fragments would then subscribe to).

**Comment by scolsen** [comment]
It looks like the Android docs recommend using a shared viewmodel for precisely this sort of parent/child fragment relation: https://developer.android.com/topic/libraries/architecture/viewmodel.html#sharing.

I think(?) this should  work here. We cold give that a try. Alternatively we could take the HomeScreen/MapContainer approach. Both take a dataRepository and have separate references to the active project (as of now the active project is the only this the addFeatureDialog fragment needs from the HomeScreenFragment).

**Comment by gino-m** [comment]
I wouldn't spend too much time on this particular case, since we'll probably end up rewriting the add feature flow once our new volunteer Interaction Designer gets done with it. But yes, a separate shared view model does sounds like a valid alternative. Would it be possible to continue with the subscription fixes as you've been doing and revisiting once we redesign this piece?

**Comment by scolsen** [comment]
Okay, sounds good! Yes, it's definitely possible to keep going, this isn't a blocker, just something I wanted to open to consideration. I'll close this for now.
