### ISSUE TITLE
[Code health] Hide MapBoxOfflineTileProvider from internal API

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#691]
Currently `MapBoxOfflineTileProvider` is exposed by `MapAdapter`. We should instead expose a generic representation of this. @scolsen let's discuss.

**Comment by scolsen** [comment]
sgtm, there's currently a note about needing to do so in order to call close, but I suppose we can just provide a generic wrapper.

**Comment by scolsen** [comment]
We'll likely not need this after a migration to COGs. I'll keep track of it for now.

**Comment by gino-m** [comment]
This was deleted
