### ISSUE TITLE
[Add observation] Dialog reappears unexpectedly on config change

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#695]
**To Reproduce**
1. Add a feature and observation, click save
2. User is returned to map instead of feature panel (see #694).
3. Rotate the device

Form reappears. Closing the form causes the app to force quit.

@shobhitagarwal1612 PTAL?

**Comment by gino-m** [comment]
@shobhitagarwal1612 Bottom sheet still doesn't show, but this issues appears to be fixed.

**Comment by shobhitagarwal1612** [comment]
Let's add more tests!
