### ISSUE TITLE
[Code Health] Simplify View Models

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#71]
There are a number of TODOs lying around regarding VM simplification. We should address these! Creating an issue so that we can reference it in each TODO.

@gino-m

**Comment by gino-m** [comment]
Great idea, thank you!

**Comment by scolsen** [comment]
I've tagged each VM with a TODO in issue-71/master. 

Turns out we actually didn't have as many preexisting comments related to this as I suspected. Still worth taking a look at each VM, though, so I'll mark this as a question as well.

**Comment by scolsen** [comment]
I think this issue is a bit broad, plus, there are no references to it in the codebase. I'll close it for now.
