### ISSUE TITLE
[Code health] Introduce enum to represent base map types in MapProvider

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#714]
Replace `int mapType`

**Comment by chaqui** [comment]
can i collaborate?

**Comment by gino-m** [comment]
Sure, we'd be happy to have your contributions! Please be sure to sign the CLA before getting started:
https://cla.developers.google.com/clas

If you'd like to send a small draft PR for initial comment (maybe just add comments of what you plan to add where) please go ahead.

**Comment by gino-m** [comment]
@shobhitagarwal1612 Iirc you already did this? If so please mark as closed.
