### ISSUE TITLE
[offline maps download] add in map labels

### ISSUE THREAD

**Issue by karistenneson** [google/ground-android#734]
For the offline basemaps, when the user is take to the satellite imagery to select an area, it would be great to have some geographic labels to help orient the user to locations. Also an option to zoom to current location would be helpful. These are available for the analysis and navigation windows, but not to select study region for imagery download.

**Comment by scolsen** [comment]
Thanks, Karis! Will do!

**Comment by gino-m** [comment]
Thanks for filing this, @karistenneson!

> For the offline basemaps, when the user is take to the satellite imagery to select an area, it would be great to have some geographic labels to help orient the user to locations.

Would showing the Google Maps default basemap when selecting offline areas instead of satellite view help here?

> Also an option to zoom to current location would be helpful. These are available for the analysis and navigation windows, but not to select study region for imagery download.

Filed #739 to track.

**Comment by scolsen** [comment]
> Thanks for filing this, @karistenneson!
> 
> > For the offline basemaps, when the user is take to the satellite imagery to select an area, it would be great to have some geographic labels to help orient the user to locations.
> 
> Would showing the Google Maps default basemap when selecting offline areas instead of satellite view help here?

Yeah we just need to render in `hybrid` instead of `satellite` if I'm understanding the request correctly.

**Comment by gino-m** [comment]
@karistenneson Just cleaning old issues up and came across this one. Was the cloudless S2 imagery useful during the pilot? I had the impression it wasn't actually used. If so, maybe the data collectors were using a cached version of the Google Maps basemap imagery?

**Comment by gino-m** [comment]
Let's show to hybrid basemap and figure out a way overlay the tile extents (semi-opaque mask?).
