### ISSUE TITLE
[Offline area download] Show GPS lock toggle button when selecting offline areas

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#739]
Forked from #734 filed by @karistenneson.  

 @scolsen I think showing the same "location lock" toggle shown on the main map view would work here. Is that what you had in mind as well?

**Comment by scolsen** [comment]
yep, sg!

**Comment by karistenneson** [comment]
Yep, I like these ideas!

**Comment by shobhitagarwal1612** [comment]
In the current iteration, we don't show the gps lock button in "Offline Area" screen. Should we enable the gps as soon as the screen is loaded?

**Comment by gino-m** [comment]
> In the current iteration, we don't show the gps lock button in "Offline Area" screen. Should we enable the gps as soon as the screen is loaded?

I think we just want to show it, not auto-enable. Sorry for the original wording.
