### ISSUE TITLE
[Code health] Add RX utility for handling errors and displaying them in the UI

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#743]
@gino-m proposed adding an RX converter called `handleErrors` that would effectively serve the role of `doOnError`, `onErrorReturn`, and friends and do the following:

1. Catch an error emitted by a stream.
2. Log an exception
2. (if applicable) show an error message in the UI in a consistent manner.

It'd be used (roughly) as follows:

```java
offlineBaseMapRepository
            offlineBaseMapRepository.getOfflineAreasOnceAndStream())	            
              .getOfflineAreasOnceAndStream()
              .compose(handleErrors("Error loading base map", ImmutableList.of()));
```

See Gino's [original comment](https://github.com/google/ground-android/pull/731#discussion_r580745539) for more info.

**Comment by gino-m** [comment]
Similarly, we could add a helper called `logErrors` that reports them to logcat, but doesn't actually eat the error.
