### ISSUE TITLE
[Code health] Handle photo fields when deserialized from remote db

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#755]
Expected to see photos here, but instead they're handled as text fields:
https://github.com/google/ground-android/blob/21e2292da587e068916abe641d90a51ce978f7e4/gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/ObservationConverter.java#L71

@shobhitagarwal1612 Any idea how we can move the deserialization logic into the same place?

**Comment by scolsen** [comment]
@shobhitagarwal1612 assigning to you for the moment, please reassign if needed!

**Comment by gino-m** [comment]
Closing legacy issue.
