### ISSUE TITLE
[Data collection] Support "capture location" data collection task

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#774]
Capture "latitude, longitude, altitude in meters, and accuracy radius"

Show values in form. In the future we can visualize the location on the map and show calculated distance from feature location.

Steps:

- [ ] Add scaffolding and basic UI - #1861 
- [ ] Parse the task from Firebase
- [ ] Saving the data back to local and remote storage

**Comment by scolsen** [comment]
@JSunde to update the status on this -- please reassign if needed!

**Comment by JSunde** [comment]
How does this differ from the DropAPinTask? @gino-m

**Comment by JSunde** [comment]
+@shobhitagarwal1612 for context

**Comment by shobhitagarwal1612** [comment]
We haven't created this task type yet. The idea is it will open the map with gestures disabled. The pin will get automatically point to the user's current location and show the accuracy number somewhere it the UI.

**Comment by JSunde** [comment]
@shobhitagarwal1612 do you mind taking this one since you worked on the DropAPinTask?

**Comment by shobhitagarwal1612** [comment]
Sure

**Comment by shobhitagarwal1612** [comment]
@gino-m Do we need this for the Oct code freeze?

**Comment by gino-m** [comment]
Hi @shobhitagarwal1612! Are you still working on this one? I'm creating several demos and realized this wasn't wired up yet. Lmk when it's ready and I'll add it to the demo survey!
