### ISSUE TITLE
[Edit Observation] Can't type in Number fields due to sporadic cursor movement

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#785]
While typing and backspacing the cursor moves unexpectedly. See screencap attached.

![bugrepro](https://user-images.githubusercontent.com/228050/118507022-d914d600-b6fb-11eb-8720-1670eef4cff1.gif)

@scolsen Could you PTAL?

**Comment by scolsen** [comment]
So, this seems to partially just be quirky behavior with the way the text field handles decimal places. I'm trying a couple of different kludges but some result in being unable to type a `.` at all, which is also very unexpected.

**Comment by scolsen** [comment]
I think the only option at this point is to push string->num conversion down the stack. Trying to perform the conversion at VM/response level seems to create a bunch of problems.

**Comment by gino-m** [comment]
Fixed by #787.
