### ISSUE TITLE
[Data collection] Add support for "Other" option in multiple choice questions

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#794]
If "other" is a valid multiple choice option allow data collectors to add a free text field to specify details

![Image](https://github.com/google/ground-android/assets/228050/dfe0c209-681e-4e0a-8be8-bc4c7c354298)

**Comment by scolsen** [comment]
@JSunde to update the status on this.

**Comment by gino-m** [comment]
This is a new feature specific to the new Ground.

**Comment by JSunde** [comment]
What is the expectation for this new functionality?
1) Will the Survey organizer need to enable the "Other" option for Multiple Choice tasks when they are defining the job? Or will it always be available?
2) Will there be a text field beside the option for the user to specify what the other category is?
3) Will we allow multiple "Other" options for the Checkbox use case?

**Comment by JSunde** [comment]
@gino-m

**Comment by JSunde** [comment]
I took a look and I still think that most of these questions are not directly answered by the mocks, should I follow up here or on Figma?

**Comment by gino-m** [comment]
> I took a look and I still think that most of these questions are not directly answered by the mocks, should I follow up here or on Figma?

Thanks for following up on the Figma. Reiterating my reply there, for the initial version we should aim for min viable functionality and simplest possible experience for the organizer. To that end, I'd suggest having a special multiple choice value with fixed "Other" label, and an optional free text for the data collector to qualify the "other" value. Does that make sense?

**Comment by shobhitagarwal1612** [comment]
Also fix the UX for radio button

**Comment by gino-m** [comment]
It's not clear whether this will be needed for field testing. Let's reassign once we have clarity.

**Comment by gino-m** [comment]
To coordinate with @os-micmec and @gino-m

**Comment by gino-m** [comment]
See https://github.com/google/ground-android/issues/2202 for schema

**Comment by gino-m** [comment]
We can handle https://github.com/google/ground-android/issues/2219 separately.

**Comment by jcqli** [comment]
@justinkimtang Is this closed now that https://github.com/google/ground-android/pull/2340 is merged?
