### ISSUE TITLE
[Feature details] Map not shown in some areas when feature is selected

### ISSUE THREAD

**Issue by coreyleamon** [google/ground-android#838]
**Describe the bug**
Android version 8.0.0.
Signed in as non-owner.

When viewing details of a data point, the map does not load. As a result, the menu to move/delete the data point is also not visible due to white text on white background.

**To Reproduce**
1. Select existing data point
2. See data point details screen

**Expected behavior**
The map should load and the menu to move or delete the point should be visible as a result.

**Actual behavior**
The map is not loading in the background, behind the point. As a result, the menu to move or delete is also not visible.

**Screenshots**
![Screenshot_20210601-151848_Ground](https://user-images.githubusercontent.com/22535879/120388219-aebc3e80-c2df-11eb-88bb-238a640111e0.jpg)

**Comment by gino-m** [comment]
This is because there were no base map tiles at the default zoom level for the selected location. Where was the pin added, out of curiosity?

**Comment by coreyleamon** [comment]
Can't remember specifically but I was dropping onto US land. Probably near where I was, in AZ at the time!
