### ISSUE TITLE
[Add/edit observation] App shows splash screen and freezes after taking photo

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#851]
After going through the permissions flow, taking a photo, and tapping the checkmark, app displayed splash screen and freezes.

Observed while profiling on physical Pixel 4, Android 11, API 30.

"App not responding" prompt appears after some time. No errors are logged to Logcat.

**Comment by shobhitagarwal1612** [comment]
I was able to reproduce the bug on Pixel 4 (API 30) only once. But it wasn't enough to debug the problem.
Are you able to consistently see the issue?

**Comment by gino-m** [comment]
> I was able to reproduce the bug on Pixel 4 (API 30) only once. But it wasn't enough to debug the problem.
> Are you able to consistently see the issue?

It only occurs after the grant photo permissions flow. You'll probably need to reset the permissions to repro again.

**Comment by shobhitagarwal1612** [comment]
Tried again with a fresh installation. Couldn't repro
