### ISSUE TITLE
[Authentication] Implement synchronous currentUser() method

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#86]
At present we can only access the current user through an `Observable`. While this is great for most cases, there are some interactions for which we need a fixed reference to the current user (the most recently emitted user from the AuthManager's Observable) for the duration of the interaction to prevent mis-attributing users to interactions that complete after the initial user to initiate them has signed out (in practice either highly unlikely or impossible, but we'd like to account for the case semantically). 

We should:

* Implement a synchronous method `currentUser` to get a reference to current user.
* Use an anonymous user as the default value in the AuthManager's user stream

@gino-m

**Comment by gino-m** [comment]
Updated issue description based on naming convention discussion, "[functional area]" prefix precedent

**Comment by gino-m** [comment]
Blocking `currentUser()` method exists in `AuthenticatonManger` so marking closed.
