### ISSUE TITLE
[Code health] Error running instrumentated tests in Android Studio

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#889]
Running `androidTest` package or individual classes with the `staging` variant enabled, I get:

```
Task 'assembleStagingAndroidTest' not found in project ':gnd'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

@shobhitagarwal1612 Any idea what I could be missing?

**Comment by shobhitagarwal1612** [comment]
Use command `connectedDebugAndroidTest` when running tests locally as default `testBuildType` is debug.
To use a different test variant, we'll need to pass the flag `-PtestBuildType=staging`

**Comment by shobhitagarwal1612** [comment]
Now, it should also be possible to test using the `run` button next to class name or right-clicking the tests directory.

**Comment by shobhitagarwal1612** [comment]
Is this still active?

**Comment by gino-m** [comment]
> Is this still active?

I don't see the "run" icon next to the test class, and when trying to run the package I see the following:

![image](https://user-images.githubusercontent.com/228050/124135988-5600d280-da52-11eb-8724-19ecb46caecd.png)

**Comment by shobhitagarwal1612** [comment]
I see this on the latest `master` branch.

![image](https://user-images.githubusercontent.com/8918023/124137382-4493e680-daa3-11eb-9f1c-5366a49064c4.png)

**Comment by gino-m** [comment]
It could be my environment.. Do they complete successfully when you click Run?

**Comment by shobhitagarwal1612** [comment]
Yes, I had a pair debugging session with Heman as well. And it was working for him too. 
Maybe try `invalidate cache & restart`?

**Comment by gino-m** [comment]
Will do. If you confirmed this is working we can close it for now. Thanks again!
