### ISSUE TITLE
[Sign in] Sign in button not visible on tablet

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#890]
Model: SM-T650
OS: Android 4.4.4

**Comment by shobhitagarwal1612** [comment]
Created an emulator for tablet 9.6"
Sign in button visible. 

![image](https://user-images.githubusercontent.com/8918023/126690035-09efed22-b891-428c-bc1f-fe8c0c7b27cc.png)

**Comment by JSunde** [comment]
Sounds like this is not an issue
