### ISSUE TITLE
[Add/Edit Observation] Photos thumbnails sometimes appear sideways

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#898]
Reported by @shobhitagarwal1612 

Physical device : Pixel 4a (android 11)

**Comment by gino-m** [comment]
@shobhitagarwal1612 Is this still an issue?

**Comment by shobhitagarwal1612** [comment]
I'm not sure. Reassigning to @JSunde as he recently worked on it.

**Comment by gino-m** [comment]
> Okay yes this seems to be the case, but I also kind of think that would be the expected/desired behavior, right? If the user captures a photo in landscape mode then it should be rendered in landscape orientation in Ground. Thoughts?
> 
> @gino-m @shobhitagarwal1612

Does the camera capture the orientation in the EXIF metadata? How do other image viewers behave when displaying these photos?

**Comment by gino-m** [comment]
> 

Iirc in Photos the image rotates when the device is rotated so that it's always shown "right-side up".

**Comment by JSunde** [comment]
I believe that's the behavior I've been seeing in Ground, at least in the new photo capture task, so I think this is fixed.
