### ISSUE TITLE
[Local Storage] Local db wiped when app is updated to a newer version

### ISSUE THREAD

**Issue by scolsen** [google/ground-android#932]
Will add further details here once we determine if this is needed.

**Comment by gino-m** [comment]
Bumping to P0 since this will be needed for future updates to TerraBio prototype.

**Comment by gino-m** [comment]
> Will add further details here once we determine if this is needed.

This will be needed once users have real data in the local db.

**Comment by scolsen** [comment]
Looking through https://developer.android.com/training/data-storage/room/migrating-db-versions it doesn't seem like there's really a meaningful way for us to start doing this until we have an actual migration to perform.

**Comment by shobhitagarwal1612** [comment]
@gino-m We should probably remove `fallbackToDestructiveMigration` to prevent clearing the app data automatically if the schema is updated.

**Comment by gino-m** [comment]
@shobhitagarwal1612 +1. Reframing this as a P0 bug so we can fix it before the next release.
