### ISSUE TITLE
[Terms of Service] App crashes due to lack of permissions to ToS

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#958]
At HEAD the Android app currently is unusable since the app cannot access to `tos` is Firestore based on the deployed rules. See https://github.com/google/ground-platform/issues/786 for more info.

**Comment by HemanParbhakar** [comment]
adding this into firestore rules fixes it.
match /config/tos {
    	allow read: if canAccess(email());
    }

**Comment by gino-m** [comment]
Fixed in https://github.com/google/ground-platform/pull/758
