### ISSUE TITLE
Show confirmation dialog when deleting feature / observation

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#973]
Current behaviour deletes it directly without user confirmation.

**Comment by gino-m** [comment]
@nmhung00 Would you like to take this one as your first FR?

**Comment by shobhitagarwal1612** [comment]
@gino-m Do we have mocks for how that should look like?

**Comment by gino-m** [comment]
> @gino-m Do we have mocks for how that should look like?

Unfortunately not. As a first step we could show an alert dialog with something like the following text:
> Delete [feature label]
>
> This will also delete all associated observations. This change cannot be undone. Are you sure?
>
> Delete | Cancel

Wdyt?
