### ISSUE TITLE
[Nav Drawer] Profile image appears higher than expected

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#997]
The (G) appears to overlap with the top system bar, and is far from the user name. Ideally it would be positioned closer to the user's name. Some experimentation may be necessary to find the correct position, but I believe a 16dp gap between the two may be sufficient.
![image](https://user-images.githubusercontent.com/228050/130643382-3503b346-a8d8-4a21-a9b7-9d16d8b539f8.png)

@shobhitagarwal1612 PTAL?

**Comment by shobhitagarwal1612** [comment]
Could this be an android specific thing? I tested on my personal device and it was working fine. 
https://github.com/google/ground-android/pull/989#issue-712558185

I'll take a look. Thanks for filing the bug.

**Comment by gino-m** [comment]
> Could this be an android specific thing? 

Could be.. I was testing in the emulator with Nexus 5X API 29.

**Comment by shobhitagarwal1612** [comment]
This bug is only reproducible on API 29.

**Comment by gino-m** [comment]
@shobhitagarwal1612 Would you like to take this one on?

**Comment by gino-m** [comment]
We my replace this with the survey title and description - @rawbzz working on designs

**Comment by gino-m** [comment]
Obsolete given new design in #2238
